### ISSUE TITLE
create_order error - unorderable types: NoneType() > int()

### ISSUE THREAD

**Issue by jdogresorg** [CounterpartyXCP/counterparty-core#1025]
There appears to be an issue with the `create_order` API. The following error is thrown unless the `create_order` request includes `fee_required` and `fee_provided` params.

`Error composing order transaction via API: unorderable types: NoneType() > int()`

### Request using only required `create_order` fields... fails
![image](https://user-images.githubusercontent.com/376028/35371485-4b7b0104-0149-11e8-8ce2-547b16ea1f14.png)

### Request with `fee_required` and `fee_provided` params... success
![image](https://user-images.githubusercontent.com/376028/35371488-554792e2-0149-11e8-9ec8-8a0071b91f6f.png)

**Comment by chiguireitor** [comment]
Confirmed, this is critical as the documentation doesn't offers clue about it.

**Comment by jdogresorg** [comment]
Seems that `fee_required` is a required field tho the documentation does not indicate it is.... The `create_order` API call seems to work without `fee_provided`

**Comment by herrmoltke** [comment]
The documentation does not match the code. The code has `fee_required` as a required arg (see [here](https://github.com/CounterpartyXCP/counterparty-lib/blob/master/counterpartylib/lib/messages/order.py#L328). But the documentation doesnt have that (see [here](https://counterparty.io/docs/api/#create_order)). @jdogresorg mentioned there may be disagreement about whether the code or the docs are right. i dont have an opinion on that.

**Comment by adamkrellenstein** [comment]
related to #1327

**Comment by ouziel-slama** [comment]
`feer_required` is a required argument of `order.compose()`. With this PR https://github.com/CounterpartyXCP/counterparty-core/pull/1678 the error is explicit:
```
$ curl -X POST http://localhost:4000/api/ --user rpc:rpc -H 'Content-Type: application/json; charset=UTF-8' -H 'Accept: application/json, text/javascript' --data-binary '{ 
    "method" : "create_order",
    "params" : {
        "source": "1JDogZS6tQcSxwfxhv6XKKjcyicYA4Feev",
        "get_asset": "BATMANPEPE",
        "get_quantity": 1,
        "give_asset": "PEPECASH",
        "give_quantity": 100000000,
        "expiration": 5000
    },
    "jsonrpc" : "2.0",
    "id" : 0
    }' | python -m json.tool
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   458  100   144  100   314  20770  45290 --:--:-- --:--:-- --:--:-- 76333
{
    "error": {
        "code": -32001,
        "message": "Error composing order transaction via API: missing parameters: fee_required"
    },
    "id": 0,
    "jsonrpc": "2.0"
}
```

Do we want `fee_required` to be 0 by default in `order.compose()` function ?
