### ISSUE TITLE
[feat] API refinement on Monaparty 

### ISSUE THREAD

**Issue by cryptcoin-junkey** [CounterpartyXCP/counterparty-core#1152]
Hello,

We Monaparty applied API refinement based on our XMPIP-0021.
https://github.com/monaparty/XMPIP/blob/master/XMPIP-0021.md
Even though It causes a tiny breaking changes, it can expose more contract information.

The final aim to this refinement is to replace Counterblock and Counterwallet.
I'm not sure if you want drop them. But only I can some contributes code if you are interested in this improvement.

Are you interested in?

**Comment by adamkrellenstein** [comment]
I think we're open to extending the `counterparty-server` API to make it easier for downstream projects to use! I dunno if we'll be able to get rid of `counterblock`, but maybe!

See #1327

**Comment by adamkrellenstein** [comment]
Obviated by API v2
