### ISSUE TITLE
Add support for `custom_outputs` in advanced create parameters

### ISSUE THREAD

**Issue by jdogresorg** [CounterpartyXCP/counterparty-core#1214]
We currently support `custom_inputs` which allows a user to specify exactly what inputs to use in the transaction. We should also add support for a new `custom_outputs` parameter where a user can specify a list of additional outputs to add to the transaction.

https://docs.counterparty.io/docs/develop/api#advanced-create_-parameters

I can think of many use-cases for this new advanced feature, including the ability for services to tack on per-transaction fees.

In the future when we have a VM, we will want to be able to support a royalties functionality in the VM, and the VM will only be using native CP actions (issue, send, order, etc). Being able to specify custom outputs to CP transactions would enable support for this type of functionality.

**Comment by jotapea** [comment]
`custom_outputs` sound like a useful feature.

But I don't agree with "when we have a VM" as this is already a certainty. But that is a separate issue.
