### ISSUE TITLE
Insufficient BTC

### ISSUE THREAD

**Issue by B0BSmiths** [CounterpartyXCP/counterparty-core#1288]
I see the error message about insufficient btc when its not true - the address i am using has plenty of confirmed coin in a single utxo yet the insufficient btc error still shows

it is an intermittent fault that can not be easliy be replicated on demand and seems to go away if you just wait a moment.  i am seeing it on a create_issuance command that a few seconds later results in the api returning txhex and not the error - nothing changed on the address so its something API side

"error": {
        "code": -32001,
        "message": "Error composing issuance transaction via API: Insufficient BTC at address 1xyz1234. (Need approximately 0.0004 BTC.) To spend unconfirmed coins, use the flag `--unconfirmed`. (Unconfirmed coins cannot be spent from multi‐sig addresses.)"
    },
    "id": 0,
    "jsonrpc": "2.0"
}

**Comment by adamkrellenstein** [comment]
I'm seeing this as well with `create_send`.

**Comment by ouziel-slama** [comment]
fixed with https://github.com/CounterpartyXCP/addrindexrs/pull/23
see https://github.com/CounterpartyXCP/counterparty-core/issues/1481#issuecomment-2018710813
