### ISSUE TITLE
Scale Read-Only Backend API

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#1300]
With basic threading / multi-processing, `counterpartyd` should be able easily to handle the workload necessary to act as the backend for a popular Counterparty block explorer. (It's all read-only!)

**Comment by jotapea** [comment]
I once tried to find a seamless way to create a SQLite DB read replica, and was not successful. Maybe it exists nowadays?

The approach [xcp.dev](https://xcp.dev) takes is just reading the SQLite table [directly](https://github.com/CNTRPRTY/xcpdev/blob/0ffba5d2c7df514757b0a4032c89fc57b1cc7977/server/express_server/src/index.js#L24) with my own custom performant queries. And it works great!!

**Comment by adamkrellenstein** [comment]
That works too! Maybe shout if there's something that could be added to `counterpartyd` that could make your backend even more performant.
