### ISSUE TITLE
Inconsistent Ledger, Message Hashes

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#1309]
we probably want a long-running CI job that just randomly rolls back to different block indexes!

cf. #1330

*Ledger Hash* Reparse from Start
![telegram-cloud-photo-size-4-5843820094956883749-y](https://github.com/CounterpartyXCP/counterparty-lib/assets/6189829/eb5412ed-0d7c-4dc2-b897-83227d3736f2)

*Message Hashes*

xcp.dev
![Screenshot 2024-01-14 at 11 39 45 AM](https://github.com/CounterpartyXCP/counterparty-lib/assets/6189829/e3b9a53c-2e31-46f7-90b0-453807e7e469)

CoinDaddy (and XChain.io)
![Screenshot 2024-01-14 at 11 40 20 AM](https://github.com/CounterpartyXCP/counterparty-lib/assets/6189829/e477d6d2-3a3f-4cce-b867-3ddbebbe2d88)

<img width="508" alt="Screenshot 2024-01-15 at 11 24 36 PM" src="https://github.com/CounterpartyXCP/counterparty-lib/assets/6189829/a784e6d1-ebb6-419a-8174-e5c788d98555">

**Comment by jotapea** [comment]
UPDATE:

After completing a `rollback`, my (test) xcpdev node IS matching all 3 hashes with @JavierCervilla (JA Universelle).

`
federatednode-counterparty-1  | [2024-01-17 00:52:34][INFO] Block: 826075 (24.13s, hashes: L:5782a / TX:ec9be / M:bae3a)
`

Will update the production website asap, as it seems we are mostly in sync (only messages hashes off with xchain... until a minute ago lol seems like he just updated and now none are matching wtf lol)

**Comment by adamkrellenstein** [comment]
Great! Where did you start the parse and how many rollbacks (and to which blocks) did you do?

**Comment by jotapea** [comment]
My last block before the rollback was 825982. The [command](https://github.com/CounterpartyXCP/counterparty-lib/issues/1334#issue-2084668614): `fednode rollback 819500 counterparty`.

I got it to complete in the 3rd attempt. One stop because it felt stuck, and the other to confirm it didn't run in the background (maybe something to fix?).

> If the hashes are matching and then not matching again, we have some non-deterministic code we need to find ASAP

Maybe is better to just ask @jdogresorg directly, is more like it was coincidence that he was updating the xchain node at the same time. And answer why the change in the hashes...

**Comment by jotapea** [comment]
UPDATE:

I got a second node, which after `fednode rollback 819500 counterparty` + `fednode start counterparty` commands, is matching my previous node (xcp.dev).

```
federatednode-counterparty-1  | [2024-01-18 18:40:41][INFO] Block: 826293 (76.67s, hashes: L:1a269 / TX:c9ada / M:e78ef)
```

**Comment by jotapea** [comment]
Related: https://github.com/CounterpartyXCP/counterparty-lib/issues/1346

(Also: https://github.com/CounterpartyXCP/counterparty-lib/issues/1306)
