### ISSUE TITLE
Re-Enable DB Integrity Check

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#1315]
#1192 

Can we do this in the background in a separate thread?

**Comment by adamkrellenstein** [comment]
Hmm, what if we just used `PRAGMA schema.quick_check;` instead? https://www.sqlite.org/pragma.html#pragma_quick_check

And maybe a full integrity check after bootstrap.

I don't know if we need a separate command, since the user can just do the integrity check with the `sqlite3` REPL if they want.

**Comment by ouziel-slama** [comment]
FWIW there is already command `check-db` which do an integrity check.
