### ISSUE TITLE
Merge `counterparty-cli` and `counterparty-lib` to create `counterparty-core`

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#1328]
What should we call the new repo? 🧐

**Comment by jotapea** [comment]
I like it, `counterparty-core`.

Then integrate `addrindexrs`?

**Comment by jotapea** [comment]
Maybe eventually, if core is moved to rust… not that I have anything against python. I love simple.

Just for this it makes sense to keep them separate. The fednode solves this well.
