### ISSUE TITLE
`message_hash` ??

### ISSUE THREAD

**Issue by ouziel-slama** [CounterpartyXCP/counterparty-core#1332]
It's never checked, see https://github.com/CounterpartyXCP/counterparty-lib/blob/develop/counterpartylib/lib/check.py#L96-L147

et it's calculated with an empty array (`database.BLOCK_MESSAGES`):

https://github.com/CounterpartyXCP/counterparty-lib/blob/develop/counterpartylib/lib/blocks.py#L217-L219

**Comment by ouziel-slama** [comment]
I missed this line https://github.com/CounterpartyXCP/counterparty-lib/blob/develop/counterpartylib/lib/database.py#L72

but a global variable doesn't seem appropriate here.

**Comment by adamkrellenstein** [comment]
okay so we just want to refactor the code?

**Comment by ouziel-slama** [comment]
yeah unless I'm mistaken I don't think this works with the current code. The question is why 3 hashes? especially without checkpoints this is not really useful. In my opinion we should have just one and possibly add data to calculate it. But I don't know the history and the reasons why there are 3 today.

**Comment by adamkrellenstein** [comment]
So the goal was to be able to distinguish between different *kinds* of consensus breaks: breaks in credits/debits (user-facing), breaks in the message log (downstream application-facing), and another kind (I forget what!) I think that makes sense. It doesn't cost much to calculate all three!

**Comment by adamkrellenstein** [comment]
no they're all terrible! I don't think that one kind of hash is definitely sufficient to detect every kind of consensus break, and I want to make sure we cover every possibility.

I also don't think we should be worried about v. minor perf optimization yet... let's wait until we've dealt with the big stuff first and seen whether it's sufficient or not. Also if there's a significant performance hit, and if we want to get that extra bit of speed, we could just calculate at least two of these hashes in a separate thread.

**Comment by ouziel-slama** [comment]
yeah.. not really convinced ;-) what matters is not the number of hashes, but what we use to calculate it.. in all cases I found where the BLOCK_MESSAGE variable is reset and that should work.. so let's focus for the moment on adding checkpoints to ensure that what exists is useful and we can discuss it again if one day we refactor this part...

**Comment by jotapea** [comment]
I do see value in the separation of 3 hashes. The ledger is the most important in terms of the core financial aspect of the protocol, all participants following the same truth.

Transactions makes sense also, which subset of all the Bitcoin transactions are part of the CNTRPRTY universe.

Messages, can then become the one where nodes can confirm they are doing things the same way. But, if I find a way to optimize my database schema to improve my use cases, then the messages hashes COULD become acceptable to be different.

But I've been thinking about this, and the messages being different becoming "acceptable" is not yet possible. There could be other aspects I'm not thinking about, but definitely, the assets' issuer will have to be moved into the ledger hash. After this is done, I believe it can become acceptable to have messages hashes differ.

Makes sense?

**Comment by adamkrellenstein** [comment]
I don't think it's okay for two nodes ever to have different message hashes, eg, but I do think that a retroactive protocol change could be allowed to change the message hashes.

**Comment by jotapea** [comment]
Is not like we have to make this choice now, but I agree with this point of @ouziel-slama:

> yeah.. not really convinced ;-) what matters is not the number of hashes, but what we use to calculate it..

**Comment by adamkrellenstein** [comment]
Leaving it in for now, even though it'll change (without it being a protocol change)
