### ISSUE TITLE
Not enough memory in CircleCI to run test book

### ISSUE THREAD

**Issue by ouziel-slama** [CounterpartyXCP/counterparty-core#1335]
Exited with code exit status 137
"Exit Code 137 errors happen when a container or pod was terminated due to high memory usage"

I had a similar problem on my computer where swap was not activated.

**Comment by adamkrellenstein** [comment]
Do we just want to use a bigger machine for now? Feel free to scale it up! See https://circleci.com/product/features/resource-classes/ for our options.

**Comment by adamkrellenstein** [comment]
Per https://github.com/CounterpartyXCP/counterparty-lib/issues/1343, we can reduce the mainnet test book

**Comment by adamkrellenstein** [comment]
Is this solved?

**Comment by ouziel-slama** [comment]
yes done with github action
