### ISSUE TITLE
Graceful Shutdown

### ISSUE THREAD

**Issue by ouziel-slama** [CounterpartyXCP/counterparty-core#1344]
* Kill everything if a thread dies.

* Close all DB connections, and use `PRAGMA optimize;`

* `ctrl-c` does not work with `counterparty-server start`

<img width="776" alt="Capture d’écran 2024-01-18 à 16 32 55" src="https://github.com/CounterpartyXCP/counterparty-lib/assets/4574979/d13350a5-8028-4705-9a4f-9aa60a0a4d99">

**Comment by mattmarcello** [comment]
@ouziel-slama @adamkrellenstein think this can be closed pending your :+1:
