### ISSUE TITLE
Refactor `get_tx_info()` and Run `list_tx()` concurrently

### ISSUE THREAD

**Issue by ouziel-slama** [CounterpartyXCP/counterparty-core#1345]
This function is critical and must remain easily maintainable and testable. Today it's almost 500 lines with lots of duplicated code, generic `except`, functions nested within others, etc..

1. Ensure that all transaction types are well tested.
2. Move all pure functions to a separate file.
3. Make a first pass on the functions to see if we can extract other pure functions and move them.
3. Ensure that all pure functions are tested.
4. DRY
5. Return to step 1 until you are OK.

**Comment by adamkrellenstein** [comment]
<img width="1477" alt="Screenshot 2024-02-01 at 10 35 37 AM" src="https://github.com/CounterpartyXCP/counterparty-lib/assets/6189829/a9c14cbe-aa22-43a4-a804-c8c032129dd7">

![profile13](https://github.com/CounterpartyXCP/counterparty-lib/assets/6189829/e2540abd-b21b-4bf9-8858-0593b6327ea6)

**Comment by adamkrellenstein** [comment]
![profile13](https://github.com/CounterpartyXCP/counterparty-lib/assets/6189829/6131d49e-8f97-49ee-9257-65c82c8aed5d)

**Comment by adamkrellenstein** [comment]
<img width="1507" alt="Screenshot 2024-02-07 at 9 09 25 AM" src="https://github.com/CounterpartyXCP/counterparty-lib/assets/6189829/4d06af59-66c8-4b8a-8f56-c020205a2884">
