### ISSUE TITLE
Add Warning with Confirmation Dialogue to `bootstrap` Command

### ISSUE THREAD

**Issue by jotapea** [CounterpartyXCP/counterparty-core#1346]
**Describe the Problem**

The bootstrap download should be optional. Relying on a centrally made bootstrap is opposite to a decentralized trust-less network. And, it seems the current bootstrap has erroneous data.

**Steps To Reproduce**

1. Compare hashes between a [trust-less-default](https://github.com/CNTRPRTY/federatednode) node and a [bootstrap-default](https://github.com/CounterpartyXCP/federatednode) node.

**Screenshots and Logfiles**

CNTRPRTY/federatednode:
```
federatednode-counterparty-1  | [2024-01-20 16:33:29][INFO] Block: 826570 (24.79s, hashes: L:8e372 / TX:1dde6 / M:1e31a)
```

CounterpartyXCP/federatednode:
```
counterparty_1  | [2024-01-20 16:33:31][INFO] Block: 826570 (25.40s, hashes: L:efc60 / TX:4dbd1 / M:cef75)
```

**Comment by adamkrellenstein** [comment]
In particular, we should remark that `bootstrap` should never be used for commercial or public-facing nodes.

And we should recommend the `kickstart` function, which is a more performant way of catching up.

**Comment by ouziel-slama** [comment]
+1
I think we should also remove the default urls and add a mandatory argument `--bootstrap-url`.

**Comment by adamkrellenstein** [comment]
> +1 I think we should also remove the default urls and add a mandatory argument `--bootstrap-url`.

I don't think there's any need as long as the files are signed.

I think all we need are a warning and confirmation dialog for `bootstrap`

**Comment by ouziel-slama** [comment]
done
