### ISSUE TITLE
Drop AddIndexRs Entirely

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#1373]
Cf. https://github.com/CounterpartyXCP/counterparty-lib/issues/1352

1. https://github.com/CounterpartyXCP/counterparty-lib/blob/master/counterpartylib/lib/messages/dispenser.py#L195
2. https://github.com/CounterpartyXCP/counterparty-lib/blob/master/counterpartylib/lib/backend/__init__.py#L224

```
counterpartylib/lib/backend/addrindexrs.py
443:        "method": "blockchain.scripthash.get_utxos",
506:        "method": "blockchain.scripthash.get_history",
523:        "method": "blockchain.scripthash.get_oldest_tx",
```

We could maintain our own list of pubkeys... or we could maybe rely on centralized services for it? (We'd be able to verify the results trivially.) We could also just deprecate P2PKH support.

**Comment by ouziel-slama** [comment]
> We could also just deprecate P2PKH support.

+1!

**Comment by Jpja** [comment]
> We could also just deprecate P2PKH support.

Wait, remove the legacy "1" address format? It is the most common address format – for **emotional** reasons, I believe. Wallets (at least FreeWallet) support bech32.

**Comment by adamkrellenstein** [comment]
Ah are P2PKH the only addresses starting with `1`? Agreed then...

**Comment by adamkrellenstein** [comment]
Superseded by https://github.com/CounterpartyXCP/counterparty-core/issues/1764
