### ISSUE TITLE
Transactions not detected (randomly?)

### ISSUE THREAD

**Issue by ouziel-slama** [CounterpartyXCP/counterparty-core#1386]
<img width="1130" alt="Capture d’écran 2024-02-03 à 12 51 02" src="https://github.com/CounterpartyXCP/counterparty-lib/assets/4574979/996f40ac-2c07-45ee-a9f7-3ef71a16dd37">

This transaction https://testnet.xchain.io/tx/c986494f7128c0a90608a63d0713d8a6301684fcb7e9b05c16887138daf5a8c5 is sometime not detected when parsing `testnet`. Haven't found an explanation for this yet.

**Comment by Jpja** [comment]
The dispenser address `mvThcDEbeqog2aJ7JNj1FefUPaNdYYGqHt` has a pretty high tx count (909) with many of these having large amounts of unspent msig outputs. May this somehow result in inconsistent parsing?

https://www.blockstream.info/testnet/address/mvThcDEbeqog2aJ7JNj1FefUPaNdYYGqHt
