### ISSUE TITLE
Remove `supported` field from `transactions` table ?

### ISSUE THREAD

**Issue by ouziel-slama** [CounterpartyXCP/counterparty-core#1392]
We never use this field and this allows us to avoid, during block parsing, numerous UPDATEs on one of the tables which grows the fastest.

**Comment by jotapea** [comment]
Being a transaction stored by the software CAN already be considered the "support". There will be a validity check afterwards. Whatever was "not-supported" before, could become a new kind of invalid.

And is not relevant for non CNTRPRTY message transactions, like dispenses, right?

**Comment by ouziel-slama** [comment]
It's relevant for all transaction inserted in the db. It's an interesting info but never used and it slows down parsing.

**Comment by adamkrellenstein** [comment]
@ouziel-slama is this still necessary?

**Comment by warrenpuffett** [comment]
Given the discussion I'm going to close this as a won't fix.

**Comment by warrenpuffett** [comment]
Given the discussion I'm going to close as won't fix.
