### ISSUE TITLE
Force a new base for the next release

### ISSUE THREAD

**Issue by ouziel-slama** [CounterpartyXCP/counterparty-core#1394]
By changing the name of the default file or making a backup of the old database.
In this way we can:
- clean all `messages.*.initialise(db)` functions and only keep the latest version of the schema.
- enforce a full reparse for everyone (with the new reparse 10x faster and the kickstart for those who want, this is less problematic than before).

**Comment by adamkrellenstein** [comment]
I thought that when we bump the major version, it automatically triggers a full reparse...

In any case, I think we'd have to do this with a confirmation dialogue and an automatic backup of the existing database.

I also don't think we can ask this of users before a full mainnet reparse takes less than 8 hours, say. (Unless it's actually necessary to maintain consensus, of course.)

**Comment by ouziel-slama** [comment]
With the new database structure for the no UPDATE a full reparse is mandatory.. you might as well take advantage of it to clean up the `initialise(db)` functions..

yep I agree but in the meantime is there still the bootstrap!? We could use it with a confirmation dialog box and an automatic backup of the existing database.

**Comment by adamkrellenstein** [comment]
I think we don't want to *rely* on the bootstrap, even for performance's sake, so we should make sure a full, true reparse is fast before we have any requirement for it. FWIW, I think we can make that happen!

**Comment by ouziel-slama** [comment]
When a rollback is requested before BLOCK_FIRST we now do a `DROP TABLES ..` followed by a `block.initialize()` instead of doing a `DELETE FROM TABLE ..`
