### ISSUE TITLE
Refactor logs

### ISSUE THREAD

**Issue by ouziel-slama** [CounterpartyXCP/counterparty-core#1400]
For now we use the sqlite rowtracer to analyze each SQL query and try to understand the action performed. It would be much simpler and cleaner to call the `logger.info` function directly from the contracts, just after the line which performs the action in question.

**Comment by ouziel-slama** [comment]
...then remove `logging-format-interpolation` from `pytlintrc`

**Comment by adamkrellenstein** [comment]
Merged with https://github.com/CounterpartyXCP/counterparty-core/issues/1486
