### ISSUE TITLE
Where are the logs??

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#1401]
<img width="711" alt="Screenshot 2024-02-12 at 12 03 25 PM" src="https://github.com/CounterpartyXCP/counterparty-lib/assets/6189829/a899e883-8963-46a0-a608-90f6e460e6ff">

**Comment by ouziel-slama** [comment]
fixed here https://github.com/CounterpartyXCP/counterparty-core/pull/1485
