### ISSUE TITLE
Addrindexrs not reliable

### ISSUE THREAD

**Issue by ouziel-slama** [CounterpartyXCP/counterparty-core#1426]
<img width="1243" alt="Capture d’écran 2024-02-18 à 20 21 35" src="https://github.com/CounterpartyXCP/counterparty-lib/assets/4574979/1ba72795-efbb-45b0-be52-c845b11d85ea">
<img width="1246" alt="Capture d’écran 2024-02-18 à 19 57 19" src="https://github.com/CounterpartyXCP/counterparty-lib/assets/4574979/675a8f69-d29e-469d-89ce-eb54e885b247">
<img width="1245" alt="Capture d’écran 2024-02-18 à 19 49 25" src="https://github.com/CounterpartyXCP/counterparty-lib/assets/4574979/769b9714-6364-49b3-b927-c79114b7793d">
<img width="1238" alt="Capture d’écran 2024-02-18 à 19 49 09" src="https://github.com/CounterpartyXCP/counterparty-lib/assets/4574979/6fc2d06d-5fe6-46b6-896f-a43152ee8dad">

Obtained with this code with a few minutes intervals each time:

```
check_addrindexrs = backend.get_oldest_tx("34qkc2iac6RsyxZVfyE2S5U5WcRsbg2dpK")
print("check_addrindexrs: ", check_addrindexrs)
exit()
```

**Comment by adamkrellenstein** [comment]
will be obviated by #1377
