### ISSUE TITLE
Fix `messages` Table

### ISSUE THREAD

**Issue by ouziel-slama** [CounterpartyXCP/counterparty-core#1445]
I broke them with the no UPDATE change... (UPDATE are now INSERT..)

* [ ] Make sure that this PR is obviated and thet counterblock now works.

**Comment by adamkrellenstein** [comment]
The `messages` table is part of the API, so we need to formalize its design. I know you don't like it @ouziel-slama but I think it's actually useful. I think we need to discuss what it should look like in the long run.

**Comment by ouziel-slama** [comment]
Table message is OK. Replaced by https://github.com/CounterpartyXCP/counterparty-core/issues/1400
