### ISSUE TITLE
Random bug ?

### ISSUE THREAD

**Issue by ouziel-slama** [CounterpartyXCP/counterparty-core#1449]
During a first kickstart only the second transaction was taken into account and resulted in a consensus break. I restarted the kickstart to diagnose the problem and this time only the first transaction was taken into account (like on xcp.dev) and the kickstart passes checkpoint 821000.

The two transactions are chained and a priori the difference is in the `satoshirate` field (475000 for the first, 480000 for the second).

https://blockstream.info/tx/81a3ca538c0dcf2d8e186638e2c498b40864b8c98071519f3515aa5c0589367a?expand
https://blockstream.info/tx/4a1c9a172ede7b2aae10510fa4525be0f546b5fa4f31c5e970c023733c594ca8?expand

**Comment by adamkrellenstein** [comment]
Done I think
