### ISSUE TITLE
Protocol change to fix truncated bech32 script

### ISSUE THREAD

**Issue by ouziel-slama** [CounterpartyXCP/counterparty-core#1452]
Ideally we need a Rust function that reproduces the bug. For the moment our function reproduces the bug thanks to a mapping.
In all cases before the next release you must make a protocol change to use the non-bugged version.

**Comment by adamkrellenstein** [comment]
Since this is a protocol change, moving to v11.0.0.

**Comment by adamkrellenstein** [comment]
Dupe of https://github.com/CounterpartyXCP/counterparty-core/issues/1512
