### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#1473]
* [x] Architectural guarantees, like the `messages` table ~ logs relationship.
* [x] Move fednode docs to fednode repo.

**Comment by adamkrellenstein** [comment]
[CounterParty-20240323T010734Z-001.zip](https://github.com/CounterpartyXCP/counterparty-core/files/14736450/CounterParty-20240323T010734Z-001.zip)

Here's a backup of the old counterparty.io/docs btw.

**Comment by ouziel-slama** [comment]
done!
