### ISSUE TITLE
Impossible to restart `addrindexrs`

### ISSUE THREAD

**Issue by ouziel-slama** [CounterpartyXCP/counterparty-core#1513]
<img width="1061" alt="Capture d’écran 2024-03-13 à 21 47 45" src="https://github.com/CounterpartyXCP/counterparty-core/assets/4574979/67252372-c8df-4da8-b8f6-8d48dab53b31">

just hangs..

**Comment by adamkrellenstein** [comment]
yeah I mean we're going to remove it!

I assume `kill -9` works in the meantime?

**Comment by ouziel-slama** [comment]
I mean I can restart but then it freezes..
I let him like this all the night and in the morning it works..

**Comment by ouziel-slama** [comment]
it's just super super slow.. using this in my local version as a workaround: https://github.com/CounterpartyXCP/addrindexrs/commit/0c461d688b1fcbf3fdd2bc789ebb3e5bf52a6672
