### ISSUE TITLE
Add `bootstrap` to Dockerfile

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#1520]
We can't do `kickstart` with Docker, so we need a faster way of getting a node up and running... that means we need a way to check if the node has already been bootstrapped.

Actually it looks like we don't run `counterparty-server start` in the Dockerfile, but we should. That is, we should be setting `ENTRYPOINT` and `CMD` for the Counterparty, AddrIndexRs and Bitcoind Dockerfiles, and those have to gel with the `simplenode` values.

**Comment by ouziel-slama** [comment]
Let's add two flags to the `start` command:
- `--catch-up-mode`: normal | bootstrap | kickstart
- `--bitcoind-start-cmd`
if the database does not yet exist we use `--catch-up-mode`. If the user chooses `kickstart` he can provide the command to restart `bitcoind` automatically.

**Comment by ouziel-slama** [comment]
Also a `kcikstart` should  be possible with simplenode and shared folders.

**Comment by ouziel-slama** [comment]
> ah how? that's not obvious to me!

something like this:
```
docker-compose up bitcoind
docker-compose up addrindexrs
```
wait.. then
```
docker-compose stop bitcoind
docker-compose run --entrypoint='counterparty-server kickstart' counterparty-core 
```
wait.. then
```
docker-compose up bitcoind
docker-compose up counterparty-core 
```
> ah I like the idea of having a flag for bootstrap (--catch-up=bootstrap) but I don't love the idea of counterparty-server running bitcoind itself... :/

yep me niether ;-) but I also don't like the idea of `--catch-up=bootsrap` being the default..
Maybe a little shell script `run-simplenode.sh --catch-up=bootsrap|kickstart` which takes care of all that with `docker-compose` ?

**Comment by adamkrellenstein** [comment]
ach yeah okay I meant doing it *within* Docker Compose...

I think we should just support `--catch-up=bootstrap` for now and then see what things look like performance-wise once we move the addrindexrs functionality into Counterparty... then I think `start` will be a *lot* faster.

**Comment by ouziel-slama** [comment]
sounds good!

**Comment by ouziel-slama** [comment]
> Actually it looks like we don't run `counterparty-server start` in the Dockerfile, but we should. That is, we should be setting `ENTRYPOINT` and `CMD` for the Counterparty, AddrIndexRs and Bitcoind Dockerfiles, and those have to gel with the `simplenode` values.

hum.. the same image is also used for  `counterparty-client`.. it's more flexible to let the `ENTRYPOINT` and `CMD` in the yaml imho.

**Comment by adamkrellenstein** [comment]
hm yeah my understanding is that best practice is that it should be possible just to do `docker run counterparty` and have it work :)

I also don't think we need a docker image for the client... docker is really more for services

**Comment by ouziel-slama** [comment]
> hm yeah my understanding is that best practice is that it should be possible just to do `docker run counterparty` and have it work :)

:-)) ok I think we can do that if you are using only default values for configuration! will add an entrypoint.

> I also don't think we need a docker image for the client... docker is really more for services

Agreed! Let's call the image `counterparty-server` so!

**Comment by ouziel-slama** [comment]
done
