### ISSUE TITLE
Dispenser Opening TX Not Showing on Block Explorers

### ISSUE THREAD

**Issue by davestaxcp** [CounterpartyXCP/counterparty-core#1534]
We have a user in the Freewallet chat wondering why two different 'open dispenser' tx's do not show up on Counterparty Block Explorers

the first tx was (user used FW v0.9.25): 2bc048ed3dc67136458cc488f0cdaaf2c062dfc6d8d4934f03e7729cac116e1e

the user then upgraded to the most recent version of FW (0.9.29) and tried again, this was their second tx: d8a0294c89a333851dc46714c0214b9ed77413175bd7ea2d7df35480bcc9dd5f

1. Using Freewallet to open a Dispenser
2. xcp.io shows tx as unconfirmed when mempool.space shows it as confirmed
3. Strange 404 error code when looking it up on xcp.dev
4. tx not shown on xchain as a valid xcp tx

I asked Jdog if this may be wallet related, but he mentioned:

"the tx exists in the CP`transactions` table.... so the keyword is detected and data is decoded... can't speak to why CP isn't actually processing the tx... tho gut says prolly related to all this extra space (highlighted in blue)...

FYI... this is not a freewallet specific issue (freewallet just talks to CP API to generate transactions).... this is a counterparty specific issue... so the counterparty devs should be the ones to ask about what is happening, etc."

![image](https://github.com/CounterpartyXCP/counterparty-core/assets/136373423/f847f2fc-3f9e-46ec-b881-72fbb30ac834)

![image](https://github.com/CounterpartyXCP/counterparty-core/assets/136373423/5cde6c57-4382-440c-b5f3-8a8b1a4ab7e4)

**Comment by davestaxcp** [comment]
looks like one tx was done for a card that the address was the owner of (token issuance ownership) and the other was a Dank Rare card (not his own art)....... 

though it looks like he was also using the function in which you can start a dispenser from a specific address in which you hold the asset, but the dispenser is deployed on a new address...

so in these cirumstances the 'source' address is not the same as the 'origin' address

as shown on this screenshot, in this circumstance A ≠ B

![image](https://github.com/CounterpartyXCP/counterparty-core/assets/136373423/ebed25dd-9ed2-46b1-990e-f1ac95f17fa0)

**Comment by ouziel-slama** [comment]
> though it looks like he was also using the function in which you can start a dispenser from a specific address in which you hold the asset, but the dispenser is deployed on a new address...
> 
> so in these cirumstances the 'source' address is not the same as the 'origin' address

Please check that the dispenser address has no confirmed transactions. From block 819300 the dispenser address must be new.

**Comment by davestaxcp** [comment]
What do you mean by the "dispenser address must be new" - does that mean to use the A ≠ B source/origin process they have 'create a new address' first in the UI? Basically the user will have to use an address not in the first 10 generated by the wallet?

and that rule started at block 819300 (or is it any address created since block 819300)?

and is this related in anyway to users seeing the "Public key was neither provided nor published in blockchain" issue that sometimes arises when creating dispensers with FW?

**Comment by ouziel-slama** [comment]
> What do you mean by the "dispenser address must be new" - 

no transaction..

> does that mean to use the A ≠ B source/origin process they have 'create a new address' first in the UI? Basically the user will have to use an address not in the first 10 generated by the wallet?

yep or use a never used address..

> 
> and that rule started at block 819300 (or is it any address 'added' in the UI since block 819300)?

the rule started at block 819300
see https://github.com/CounterpartyXCP/counterparty-core/blob/master/counterparty-lib/counterpartylib/lib/messages/dispenser.py#L241

> and is this related in anyway to users seeing the "Public key was neither provided nor published in blockchain" issue that sometimes arises when creating dispensers with FW?

I don't know but I don't think so... will check..

**Comment by davestaxcp** [comment]
good the know thank you for the clarification

**Comment by ouziel-slama** [comment]
> and is this related in anyway to users seeing the "Public key was neither provided nor published in blockchain" issue that sometimes arises when creating dispensers with FW?

nope!
