### ISSUE TITLE
addrindexrs_1        | WARN - failed to connect daemon at 0.0.0.0:8332: Connection refused (os error 111)

### ISSUE THREAD

**Issue by blocklack** [CounterpartyXCP/counterparty-core#1536]
**Describe the Problem**
while starting bitcoin node, addrs indexer cant connect
`addrindexrs_1        | WARN - failed to connect daemon at 0.0.0.0:8332: Connection refused (os error 111)`

after a certain time the bitcoin node synchronization is terminated and prints this on the screen.

`
addrindexrs_1        | WARN - failed to connect daemon at 0.0.0.0:8332: Connection refused (os error 111)
addrindexrs_1        | WARN - failed to connect daemon at 0.0.0.0:8332: Connection refused (os error 111)
counterparty-core_1  | [2024-03-20 09:01:57][INFO] AddrIndexRs connecting...
`

**Steps To Reproduce**
1.  docker-compose -f simplenode/compose.yml up

**Screenshots and Logfiles**
![image](https://github.com/CounterpartyXCP/counterparty-core/assets/115724219/0c08375b-d221-4c86-acc8-c124d86e2d32)

![image](https://github.com/CounterpartyXCP/counterparty-core/assets/115724219/1cc193f0-b3af-40d2-904f-6ac559a92c51)

<html>
<body>

AMD EPYC 7401P | NIC 1 Gbit- Intel I350
2x SSD SATA 256 GB |  
2x SSD SATA 1,92 TB Datacenter |  
4x RAM 32768 MB DDR4 ECC reg.

<br class="Apple-interchange-newline">
</body>
</html>

Os: Ubuntu 22.04.2 LTS base

**Comment by ouziel-slama** [comment]
shoud be fixed on the branch `develop` with https://github.com/CounterpartyXCP/counterparty-core/commit/23a99bcee9372365c1a31d672b4a0b3d6b993a6d

**Comment by ouziel-slama** [comment]
need also https://github.com/CounterpartyXCP/addrindexrs/pull/20
