### ISSUE TITLE
Missing Data in Messages Table

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#1546]
<img width="723" alt="Screenshot 2024-03-22 at 7 48 12 AM" src="https://github.com/CounterpartyXCP/counterparty-core/assets/6189829/9315c164-0008-4366-b13e-4fb8d8910be1">

**Comment by ffmad** [comment]
At first I did a bootstrap sync and thought it could be due to this, but after removing the database and doing a normal sync the same error was still present.

How are the binding data gathered?

**Comment by ouziel-slama** [comment]
fixed
