### ISSUE TITLE
Missing Dispense?

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#1575]
<img width="722" alt="Screenshot 2024-03-31 at 8 33 37 PM" src="https://github.com/CounterpartyXCP/counterparty-core/assets/6189829/0db435d6-0979-47c1-a94f-e36afc63ea14">

**Comment by ouziel-slama** [comment]
it's a bug in xchain.io.
https://www.xcp.dev/tx/f69bc132ee99518f2ab12e10991f3083ec8a90211cd1ed21b277e01a781b3c73
xcp.dev displays 5 credits for the address `bc1qsteve3tfxfg9pcmvzw645sr9zy7es5rx645p6l`
