### ISSUE TITLE
MPMA issue with confirmed btc tx using Freewallet 0.9.29

### ISSUE THREAD

**Issue by davestaxcp** [CounterpartyXCP/counterparty-core#1609]
looks like a user is having an issue with an MPMA send not showing up in the xcp database (using Mac OS and most recent version Freewallet Desktop (0.9.29)

**Steps to reproduce the behavior**
1. use Freewallet Desktop 0.9.29 on Mac OS
2. create an MPMA send. ex:

1N2Js4WPg9j64sNYPbo9cXT37Q5F6gJd5Y, GIVEKUDOS, 888, PEPE.CO 888
17dHymDAk2wkzQGRrggT4Pv1drj4Nf6GCL, GIVEKUDOS, 888, PEPE.CO 888
18CtfmVT1hH1vKstHm4TTD5HDMCvvB8nUd, GIVEKUDOS, 888, PEPE.CO 888
12iRwtafSCEjxeM63ALfvxQv2BGRdHCyPx, GIVEKUDOS, 888, PEPE.CO 888
1BVwbixQmHPWhwVgmuyQQsCXFfpWuiFaLD, GIVEKUDOS, 888, PEPE.CO 888
1BNjuv8wnUEJXdF1Bq1Y792t6t4rukWxJS, GIVEKUDOS, 888, PEPE.CO 888
1Tips9o1pgZjyNdsSg6LFuZXR7MfGGKfk, GIVEKUDOS, 888, PEPE.CO 888

3. Freewallet sees that info as valid
4. Send tx
5. Wait for btc confirmation
6. see tx info on various xcp block explorers:

https://www.xcp.io/tx/28bd1626a21d6a5ccae60dd9b44ad95580dba829114a6dfef81b4e60cafb4bde

https://xchain.io/tx/28bd1626a21d6a5ccae60dd9b44ad95580dba829114a6dfef81b4e60cafb4bde

https://www.xcp.dev/tx/28bd1626a21d6a5ccae60dd9b44ad95580dba829114a6dfef81b4e60cafb4bde

^ only explorer that shows some info related to xcp data

7. see tx is confirmed on btc side of things but not xcp side of things:

https://blockstream.info/tx/28bd1626a21d6a5ccae60dd9b44ad95580dba829114a6dfef81b4e60cafb4bde

https://mempool.space/tx/28bd1626a21d6a5ccae60dd9b44ad95580dba829114a6dfef81b4e60cafb4bde

---

Juan commented in the dev chat:

"You can see the hex of the transaction here, which was stored on the Counterparty DB:

https://www.xcp.dev/tx/28bd1626a21d6a5ccae60dd9b44ad95580dba829114a6dfef81b4e60cafb4bde

But there were no messages stored. And after further debug, no entries in the sends table either.

This is a bug in the protocol it seems, maybe is an invalid mpma send. There should at least be an insert of the invalid send (and its entry in the messages table).

The decoding of the hex for mpma transactions is not yet done in xcpdev, but it should be added and it would have been very helpful in a case like this."

Joe commented:

"or just a malformed message, its difficult to decode MPMA data manually"

---

**Comment by mattmarcello** [comment]
On my DB, `tx.data` is empty

| tx_index|tx_hash|block_index|block_hash|block_time|source|destination|btc_amount|fee|data|supported
|--------|--------|--------|--------|--------|-------|--------|--------|--------|--------|--------|
| 2724764|28bd1626a21d6a5ccae60dd9b44ad95580dba829114a6dfef81b4e60cafb4bde|838333|00000000000000000000677f4778e411dcf0957b5c908caac44547e5b7201984|1712597424|1Cpx1CBqxd7ATUQCsiyav2wdXf5GHb6xpJ||0|33333||1

**Comment by adamkrellenstein** [comment]
Closing until there are more reports of this issue
