### ISSUE TITLE
v10.0 first impressions, differences to v9.61

### ISSUE THREAD

**Issue by jotapea** [CounterpartyXCP/counterparty-core#1614]
Running v10.0.0-rc1, installed with Docker Compose following https://docs.counterparty.io/docs/basics/getting-started/.

First of all just want to congratulate on the effort and work done to get to this release. Many good things in it. But there seems to be some changes I would like to discuss here.

Starting with maybe the most critical find. I see that the `messages` table is now including `blocks` category, and there is a new `parse` command. After being fully synced, these `blocks` stop using the `parse` command and use `insert` instead.

Isn't this a clear source for non-determinism for the messages hash? Nodes will sync at different blocks, so later nodes will have `parse` while the old ones will have `insert` for the same blocks.

Also, I think that the messages table could just not include the blocks and this issue will be solved. v9.61 does not have blocks in the messages.

Will follow up on other findings based on the response to this.

**Comment by adamkrellenstein** [comment]
Informal reviews of the software should be published elsewhere, for instance on the [project forums](https://forums.counterparty.io), and each bug report should have a separate issue (see https://github.com/CounterpartyXCP/counterparty-core/issues/1616).

**Comment by adamkrellenstein** [comment]
Obviously a minor bug in the messages table doesn't warrant a CIP, and a GitHub issue tracker is not the appropriate place for "first impressions" of a software release.
