### ISSUE TITLE
No detailed README

### ISSUE THREAD

**Issue by b1u3y** [CounterpartyXCP/counterparty-core#1615]
**Describe the Problem**
The README was overwritten and does not contain install instructions. 

**Steps To Reproduce**
1. Look for the README.

**Comment by adamkrellenstein** [comment]
Yeah this was intentional, in order to not duplicate documentation between the README and the official documentation. The README clearly points users toward the latter: https://docs.counterparty.io/docs/basics/what-is-counterparty/

**Comment by b1u3y** [comment]
Surface web documentation needs updating if that is the case. Surface web manual install still references -cli for example.
