### ISSUE TITLE
Non-Determinism in Messages Table

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#1616]
The `blocks` messages can have two different values for the `command`: `parse` or `insert`.

**Comment by jotapea** [comment]
Thanks for creating this as its own specific issue, based on https://github.com/CounterpartyXCP/counterparty-core/issues/1614. Adding the relevant part of the issue description here.

> Starting with maybe the most critical find. I see that the messages table is now including blocks category, and there is a new parse command. After being fully synced, these blocks stop using the parse command and use insert instead.
> 
> Isn't` this a clear source for non-determinism for the messages hash? Nodes will sync at different blocks, so later nodes will have parse while the old ones will have insert for the same blocks.
> 
> Also, I think that the messages table could just not include the blocks and this issue will be solved. v9.61 does not have blocks in the messages.

**Comment by ouziel-slama** [comment]
Normally, there should be one "insert" and one "parse" per block (corresponding to `NEW_BLOCK` and `BLOCK_PARSED` events). I'll check that this is indeed the case. It is recommended to use the event name rather than `command` and `category` (which is actually the table name). These two fields, which expose the SQL schema, should disappear in API v2.

**Comment by ouziel-slama** [comment]
I checked there is indeed a problem. I think it comes from the kickstart filling the block table first.. I'll take care of that.

**Comment by jotapea** [comment]
Is there a purpose for now including the blocks as a message? v9.61 didn't...

**Comment by ouziel-slama** [comment]
fixed here https://github.com/CounterpartyXCP/counterparty-core/pull/1687
