### ISSUE TITLE
Different ledger hashes from block 835513

### ISSUE THREAD

**Issue by jotapea** [CounterpartyXCP/counterparty-core#1631]
Node running v9.61:
https://www.xcp.dev/blocks#835510

Node running v10.0rc1:
http://v10.0.0-rc.1.preview.xcp.dev.s3-website-us-east-1.amazonaws.com/blocks#835510

You can compare both and see they are consistent until block 835513.

**Comment by jotapea** [comment]
Found the problem.

This order is expired in v9.61, as it should:
https://www.xcp.dev/tx/e928918dd9a0605dc737eca5034cc444080d20f4ff7a7090b11f10d2a8e637e6

But it is still showing as open in v10:
http://v10.0.0-rc.1.preview.xcp.dev.s3-website-us-east-1.amazonaws.com/tx/e928918dd9a0605dc737eca5034cc444080d20f4ff7a7090b11f10d2a8e637e6

**Comment by ouziel-slama** [comment]
yeah it's visible here:
https://www.xcp.dev/block/835513
http://v10.0.0-rc.1.preview.xcp.dev.s3-website-us-east-1.amazonaws.com/block/835513

**Comment by ouziel-slama** [comment]
Fixed here: https://github.com/CounterpartyXCP/counterparty-core/pull/1633

**Comment by jotapea** [comment]
Ok so v9 also has an issue, but is only for a single block. Didn't notice this, good find!

In https://github.com/CounterpartyXCP/counterparty-core/pull/1633#issue-2237873558 you mention:

> It can therefore happen that an order with the status filled, and therefore not expired, is re-opened because of an expired order_match.

But this doesn't necessarily apply to this order, because in v9 XCP is credited back in the expiration. And then this XCP can start changing hands in v9 while still being locked in the order in v10, leading to ledger inconsistencies between versions.

Mentioning this because this seems serious to the point that v10 should not be used until this is "fixed" at least to temporarily have the same flawed "expired one block later" as v9 has...

Reopening the issue just to bring attention to this, but if my concern is not warranted because your explanation needed more details then we could close this again.

**Comment by ouziel-slama** [comment]
@jotapea the PR fixes the hash mismatch not the bug to not have inconsistencies between versions.
This https://github.com/CounterpartyXCP/counterparty-core/issues/1634 will fix the bug.
