### ISSUE TITLE
Cannot Construct Dispense Transactions due to Encoding Error

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#1648]
The same request works against v9.61.3 (tested against http://api1.counterparty.io:4000).

**Comment by adamkrellenstein** [comment]
<img width="730" alt="Screenshot 2024-04-12 at 11 24 12 PM" src="https://github.com/CounterpartyXCP/counterparty-core/assets/6189829/3741e6fa-7799-47fb-95e3-39cc67f4a16f">

**Comment by DerpHerpenstein** [comment]
The following call is being used to make a buy from a dispenser
`{
  method: 'create_send',
  params: {
    source: 'bc1qy25gwr9vdrvxx0w35wa9vrpc3hc5h6rd0p56f4',
    destination: 'bc1q7ra8ec9nmzfw96rnayss83lqzcz78gd0hsp2j0',
    asset: 'BTC',
    quantity: 69420,
    allow_unconfirmed_inputs: true,
    extended_tx_info: true,
    fee: 35925
  },
  jsonrpc: '2.0',
  id: 0
}`

The transaction fails to be generated correctly with the following error:

> {
    "error": {
        "code": -32001,
        "message": "Error composing send transaction via API: Constructed transaction does not parse correctly: ('bc1qy25gwr9vdrvxx0w35wa9vrpc3hc5h6rd0p56f4', 'bc1q7ra8ec9nmzfw96rnayss83lqzcz78gd0hsp2j0', b'') ≠ ('1JDogZS6tQcSxwfxhv6XKKjcyicYA4Feev', 'bc1q7ra8ec9nmzfw96rnayss83lqzcz78gd0hsp2j0', b'\r\\x00')"
    },
    "id": 0,
    "jsonrpc": "2.0"
}

The parsed address is incorrect, and the desired empty byte array is being compared to the parsed null terminated string containing only a carriage return

Immediately retrying the request, the error slightly changes and the parsed address is now correct, but the empty byte array/carriage return issue remains

> {"error":{"code":-32001,"message":"Error composing send transaction via API: Constructed transaction does not parse correctly: ('bc1qy25gwr9vdrvxx0w35wa9vrpc3hc5h6rd0p56f4', 'bc1q7ra8ec9nmzfw96rnayss83lqzcz78gd0hsp2j0', b'') ≠ ('bc1qy25gwr9vdrvxx0w35wa9vrpc3hc5h6rd0p56f4', 'bc1q7ra8ec9nmzfw96rnayss83lqzcz78gd0hsp2j0', b'\\r\\x00')"},"id":0,"jsonrpc":"2.0"}

When a create_send is made with BTC as the asset, i think the desired_data is set to b"" at line 833 of transactions.py This is compared with the result from gettxinfo_get_tx_info which i think is b'\r\\x00.

my guess is that there are two issues, the first being some non-determinism in the parsed address, while the other seems to be a string manipulation issue

**Comment by ouziel-slama** [comment]
Already fixed with https://github.com/CounterpartyXCP/counterparty-core/pull/1647
(the problem comes from the fact that for `dispense` transactions, data is injected at the time of analysis.. this should not be the case at the time of composition)
<img width="1033" alt="Capture d’écran 2024-04-14 à 17 29 44" src="https://github.com/CounterpartyXCP/counterparty-core/assets/4574979/c03544f9-8afe-4329-b515-b89db96b16c2">

**Comment by adamkrellenstein** [comment]
okay great! can you test it with free wallet before we close the issue?

**Comment by ouziel-slama** [comment]
> bc1q7ra8ec9nmzfw96rnayss83lqzcz78gd0hsp2j0

just tried but seems I can't compose an arbitrary tx and don't have a wallet with BTC on it (first time I use freewallet)..

**Comment by adamkrellenstein** [comment]
Yeah I mean I can't get Freewallet even to start up properly. 🤷‍♀️
