### ISSUE TITLE
Kill `kickstart`

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#1649]
The regular `start` process is now fast enough to be the only supported method of catching up. This'll be a major simplification and usability win. :)

With https://github.com/CounterpartyXCP/counterparty-core/issues/1957, only about 25% of the time is block fetching (with the final optimization described in https://github.com/CounterpartyXCP/counterparty-core/issues/1960).

**Comment by ouziel-slama** [comment]
done here https://github.com/CounterpartyXCP/counterparty-core/pull/1928/commits/a00be2052e4684e8b3534714c9aa5835b5167914
