### ISSUE TITLE
Don't Report "Behind" Immediately Upon Seeing a New Block

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#1650]
There should be a 20s grace period, or something—if the block is that new, then the node is still reasonably "caught up". That is, if the `blocktime` of the new block is very recent, it's fine.

~Or we could keep it simple and only fail if the node is two blocks behind.~ We already do this?? Then why does this happen so often?

Related to #1327

**Comment by ouziel-slama** [comment]
This is one of the reasons why I think a 503 error is too brutal. There are several use cases where a functional API is interesting but the node is a few blocks behind.
The v2 API systematically returns a result (even with a 503 or 202 error) and it is the responsibility of API clients to systematically check the 3 headers (X-COUNTERPARTY-HEIGHT, X-BACKEND-HEIGHT and X-COUNTERPARTY-READY) and decide what to do depending on the use case.

**Comment by adamkrellenstein** [comment]
ah I don't follow... a result is returned even with a `503`? That's a good idea! But let's be sure to document that very clearly, because we have to make sure the clients know to do that check!

OTOH, IMO a 503 should ~never happen except when initially catching up or after a large reorganization (>=2 blocks). The node should parse each block in a small number of seconds, and it shouldn't report a 503 during that short window.

**Comment by ouziel-slama** [comment]
> ah I don't follow... a result is returned even with a `503`? That's a good idea! But let's be sure to document that very clearly, because we have to make sure the clients know to do that check!

yep! an error code does not mean no content!
of course this will even be in the introduction of the v2 API documentation!

> OTOH, IMO a 503 should ~never happen except when initially catching up or after a large reorganization (>=2 blocks). The node should parse each block in a small number of seconds, and it shouldn't report a 503 during that short window.

sounds good!
let's just return an error code if `X-COUNTERPARTY-HEIGHT >= X-BACKEND-HEIGHT - 1` instead of `X-COUNTERPARTY-HEIGHT >= X-BACKEND-HEIGHT` ?

**Comment by adamkrellenstein** [comment]
@ouziel-slama sorry I was in the middle of editing my comment!

on second thought, I don't think that we should return data if we're going to return a `503`... seems like the data should just be a message saying what the error is.

**Comment by adamkrellenstein** [comment]
> sounds good! let's just return an error code if `X-COUNTERPARTY-HEIGHT < X-BACKEND-HEIGHT - 1` instead of `X-COUNTERPARTY-HEIGHT < X-BACKEND-HEIGHT` ?

Yes! That should be sufficient. But isn't that what's done in the v1 API? https://github.com/CounterpartyXCP/counterparty-core/blob/ae2ba6c8d28e952022529720fcd512d553f72337/counterparty-lib/counterpartylib/lib/api.py#L228

**Comment by ouziel-slama** [comment]
> Maybe it makes sense to split API calls into those that can be returned while the node is behind and those that can't?? For instance, if you want the info on an old block, there's no reason that can't be a `200` even when the node is behind; on the other hand, I think it's not great to return an address's balances when they are out of date (even with an error code—that's a bit risky).

This would actually be ideal but too complex I think! IMHO you really have to leave the responsibility to the API client for this kind of thing. Only the client, when it makes the request, knows whether it is best to have an error code or not if the node is late.
hum.. perhaps the flag `--api-not-ready-http-code` must be in fact an optional header send by the client to indicate what error code he wants ? yeah IMHO that the simpler solution!

**Comment by ouziel-slama** [comment]
> > sounds good! let's just return an error code if `X-COUNTERPARTY-HEIGHT < X-BACKEND-HEIGHT - 1` instead of `X-COUNTERPARTY-HEIGHT < X-BACKEND-HEIGHT` ?
> 
> Yes! That _should_ be sufficient, but isn't that what's done in the v1 API?
> 
> https://github.com/CounterpartyXCP/counterparty-core/blob/ae2ba6c8d28e952022529720fcd512d553f72337/counterparty-lib/counterpartylib/lib/api.py#L228

oh I didn't know! :) I'm going to do the same on v2!

**Comment by adamkrellenstein** [comment]
> oh I didn't know! :) I'm going to do the same on v2!

Yeah I think there's an actual problem that's causing the frequent `503`s, like with mempool parsing, or with it taking ~minutes to parse new blocks sometimes.

I don't love the idea of having a flag for the error code. I mean, if the client knows to set the flag, they can also just modify the client code to handle different HTTP codes differently. 🤷‍♀️

Here's what I'm picturing:
1. We should always use the `503` error code to indicate that the node is behind; and we shouldn't return data, just an error message. (The client should be told to retry.)
2. We should make sure that (1) never happens unless the node is still catching up or there was just a big reorg.
3. We could whitelist *some* routes (e.g. the new version of `/nodeinfo`, `/blocks/<block_hash>`, `/transactions/<tx_hash>`) that will never report a `503` because their data is never out of date, if that's not too complicated.
4. We could have the `--force` flag disable the `503` entirely.

**Comment by ouziel-slama** [comment]
> > oh I didn't know! :) I'm going to do the same on v2!
> 
> Yeah I think there's an actual problem that's causing the frequent `503`s, like with mempool parsing, or with it taking ~minutes to parse new blocks sometimes.
> 
> I don't love the idea of having a flag for the error code... I mean, if the client knows to set the flag, they can also just modify the client code to handle different HTTP codes differently. 🤷‍♀️

yeah exactly! This is why my original idea is to always return a result even with an error code and let the client decide what to do. This is what seems to me to be the simplest and most flexible for the API client.

> 
> Here's what I'm picturing:
> 
> 1. We should always use the `503` error code to indicate that the node is behind; and we shouldn't return data, just an error message. (The client should be told to retry.)
> 2. We should make sure that (1) never happens unless the node is still catching up or there was just a big reorg.
> 3. We could whitelist _some_ routes (e.g. `/nodeinfo`, `/blocks/<block_hash>`, `/transactions/<tx_hash>`) that will never report a `503` because their data is never out of date, if that's not too complicated.
> 4. We could have the `--force` flag disable the `503` entirely.

yep it can work like that! I just wouldn't use `--force` but a specific flag. `--force` seems to me to be used for too many things..

**Comment by ouziel-slama** [comment]
OK so, if the server is not ready the API v2 returns a 503 error except for `/blocks/*`, `/transactions/*`, `/backend/*` and `/`.
Also a server is not ready if `ledger.CURRENT_BLOCK_INDEX >= BACKEND_HEIGHT - 1` 
This means that the server may be a block late (parsing time).. this should be enough as a grace period.. @adamkrellenstein 
if ok for you we can close I think.

**Comment by adamkrellenstein** [comment]
Yep!

**Comment by ouziel-slama** [comment]
Right now, on testnet, there is almost a block by second and the docker compose test fails because `counterparty-server` cannot be "ready".. there is little chance of this happening on `mainnet`.. but if we want to handle this kind of case on `testnet` we probably also need to check the block_time as you suggest! @adamkrellenstein

**Comment by adamkrellenstein** [comment]
Yep, sounds right! We should check both.

**Comment by ouziel-slama** [comment]
Done here https://github.com/CounterpartyXCP/counterparty-core/pull/1754
