### ISSUE TITLE
Issues with block_index

### ISSUE THREAD

**Issue by niftyboss1** [CounterpartyXCP/counterparty-core#1651]
Block_index for some dispensers seems to be incorrect in v10.0 - Or does the API work differently? 
Looking at the same dispenser in v10.0 and v9.61.3:

v10.0:
curl -X POST https://api.counterparty.io:4000/api/ --user rpc:rpc --data-binary "{ \"method\": \"g
et_dispensers\", \"params\": {  \"filters\": [ {\"field\": \"source\", \"op\": \"LIKE\", \"value\": \"1LbqQxREP%\" } , {
\"field\": \"asset\", \"op\": \"=\", \"value\": \"XCP\" } ] ,  \"filterop\": \"And\", \"order_by\": \"satoshirate\",  \"
order_dir\": \"asc\" }, \"jsonrpc\": \"2.0\", \"id\": 0 }"

{"result": [{"tx_index": **2708478**, "tx_hash": "63cfae80d7caf50c37b139c4ee6f076db421e3b0d7bc34616a2318ae0b600e5a", "block_index": **833712**, "source": "1LbqQxREPfeMFNPx9VGpGTiMo4kaiMSpHw", "asset": "XCP", "give_quantity": 100000000, "escrow_quantity": 30000000000, "satoshirate": 23000, "status": 0, "give_remaining": 29900000000, "oracle_address": null, "last_status_tx_hash": null, "origin": "12CeCTTKXNW1D57Pzfc2QheJBEHd37Cnq8", "dispense_count": 1}], "id": 0, "jsonrpc": "2.0"}

v9.61.3:
curl -X POST http://public.coindaddy.io:4000/api/ --user rpc:1234 --data-binary "{ \"method\": \"get_dispensers\", \"params\": {  \"filters\": [ {\"field\": \"source\", \"op\": \"LIKE\", \"value\": \"1LbqQxREP%\" } , {\"field\": \"asset\", \"op\": \"=\", \"value\": \"XCP\" } ] ,  \"filterop\": \"And\", \"order_by\": \"satoshirate\",  \"order_dir\": \"asc\" }, \"jsonrpc\": \"2.0\", \"id\": 0 }"

{"result": [{"tx_index": **2708476**, "tx_hash": "63cfae80d7caf50c37b139c4ee6f076db421e3b0d7bc34616a2318ae0b600e5a", "block_index": **833637**, "source": "1LbqQxREPfeMFNPx9VGpGTiMo4kaiMSpHw", "asset": "XCP", "give_quantity": 100000000, "escrow_quantity": 30000000000, "satoshirate": 23000, "status": 0, "give_remaining": 29900000000, "oracle_address": null, "last_status_tx_hash": null, "origin": "12CeCTTKXNW1D57Pzfc2QheJBEHd37Cnq8"}], "id": 0, "jsonrpc": "2.0"}

**Comment by adamkrellenstein** [comment]
Good catch!

**Comment by ouziel-slama** [comment]
Yes I will check more closely but it's normal. This is not related to the API but to the "No UPDATE" upgrade. Now that we no longer do an UPDATE, the `block_index` which is returned indicates the block of the last modification of this dispenser and no longer that of the creation.

**Comment by niftyboss1** [comment]
Ah, makes sense - many thanks for the clarification.
