### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#1652]
I just found and fixed a few errors, but we should check to make sure there aren't any more, esp. for the `-cli` -> `-wallet` change.

* Include note that the user may have to update their `$PATH` for the commands `counterparty-server` etc. to work.
* Instructions for upgrading, given the change in package names

**Comment by ouziel-slama** [comment]
done here https://github.com/CounterpartyXCP/Documentation/pull/188
