### ISSUE TITLE
Test Non-Idempotent API Endpoints using `regtest`

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#1654]
... to avoid problems like #1119 

* Send
* Issuance
* Dispense
* Etc.

**Comment by ouziel-slama** [comment]
hum.. it's not trivial with regtest.. for the moment we use a mock of bitcoind for all the tests..
the `api.create_*` functions are well tested for now: https://github.com/CounterpartyXCP/counterparty-core/blob/develop/counterparty-lib/counterpartylib/test/fixtures/vectors.py#L8905-L9376

#1119 is a very specific bug which only concerns BTC only transactions with a `dispenser` as recipient.
I also plan to add tests for these functions with API v2, let's integrate this issue into the "API Redesign" PR?

**Comment by adamkrellenstein** [comment]
Yep, that works for me!

**Comment by adamkrellenstein** [comment]
https://github.com/CounterpartyXCP/counterparty-core/issues/2167
