### ISSUE TITLE
Optimize `check.asset_conservation()`

### ISSUE THREAD

**Issue by ouziel-slama** [CounterpartyXCP/counterparty-core#1666]
And re-enable the check after each new block.

**Comment by adamkrellenstein** [comment]
Maybe enable this only for servers that devs run? (Like Sentry)

**Comment by ouziel-slama** [comment]
I put it in an independent Thread, at startup and then each 12 hours: https://github.com/CounterpartyXCP/counterparty-core/pull/2299/commits/32e0300399e5b306487fe3bc326537584e407127
