### ISSUE TITLE
Docker compose installation failing

### ISSUE THREAD

**Issue by jotapea** [CounterpartyXCP/counterparty-core#1690]
**Steps To Reproduce**
Following the instructions from https://docs.counterparty.io/docs/basics/getting-started/.

```bash
git clone https://github.com/CounterpartyXCP/counterparty-core.git
cd counterparty-core
mkdir ~/.local/share/counterparty-docker-data
docker-compose up -d
```

Then in the middle of the process, getting this:

```
57d7718a02a0: Pull complete
Digest: sha256:cbd15da7e8945070fb2fd0b012391139cb869716eb44c2de9238a73d6983db64
Status: Downloaded newer image for counterparty/counterparty:v10.1.0
Creating counterparty-core_bitcoind_1 ... error

ERROR: for counterparty-core_bitcoind_1  Cannot start service bitcoind: error while mounting volume '/var/lib/docker/volumes/counterparty-core_data/_data': failed to mount local volume: mount /root/counterparty-core/${XDG_DATA_HOME:-~/.local/share}/counterparty-docker-data:/var/lib/docker/volumes/counterparty-core_data/_data, flags: 0x1000: no such file or directory

ERROR: for bitcoind  Cannot start service bitcoind: error while mounting volume '/var/lib/docker/volumes/counterparty-core_data/_data': failed to mount local volume: mount /root/counterparty-core/${XDG_DATA_HOME:-~/.local/share}/counterparty-docker-data:/var/lib/docker/volumes/counterparty-core_data/_data, flags: 0x1000: no such file or directory
ERROR: Encountered errors while bringing up the project.
```

**Comment by adamkrellenstein** [comment]
What version did you initially run in Docker? This looks like it was from a pre-release version, when the directories weren't stable.

**Comment by jotapea** [comment]
I'll try a new server... will follow up soon.

**Comment by adamkrellenstein** [comment]
It looks like there was a previous installation of a pre-release version of v10.1.0. Can you remove all of `/var/docker` and try again?

**Comment by jotapea** [comment]
Getting weird errors now:

```
docker-compose up -d

Creating network "counterparty-core_default" with the default driver
ERROR: failed to update bridge store for object type *bridge.networkConfiguration: open /var/lib/docker/network/files/local-kv.db: no such file or directory
```

Got this, then reinstalled docker-compose just in case the deleting of all those files messed it up, but still getting the same error.

**Comment by adamkrellenstein** [comment]
Is this on the fresh server? It looks like there's an issue with your installation of Docker. You should `rm -rf /var/docker` I think.

**Comment by jotapea** [comment]
Same exact error from a fresh server.

**Comment by adamkrellenstein** [comment]
Hm, looks like a potential incompatibility between the OS and the Docker Compose file. What OS are you running and what's the output of `$ mount`?

**Comment by jotapea** [comment]
Ubuntu 22.04.4 LTS (GNU/Linux 6.5.0-1014-aws x86_64)

```
$ mount

/dev/xvda1 on / type ext4 (rw,relatime,discard,errors=remount-ro)
devtmpfs on /dev type devtmpfs (rw,nosuid,noexec,relatime,size=4052604k,nr_inodes=1013151,mode=755,inode64)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev,inode64)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,nodev,size=1624072k,nr_inodes=819200,mode=755,inode64)
tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k,inode64)
cgroup2 on /sys/fs/cgroup type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate,memory_recursiveprot)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
bpf on /sys/fs/bpf type bpf (rw,nosuid,nodev,noexec,relatime,mode=700)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=29,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=15464)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime,pagesize=2M)
mqueue on /dev/mqueue type mqueue (rw,nosuid,nodev,noexec,relatime)
debugfs on /sys/kernel/debug type debugfs (rw,nosuid,nodev,noexec,relatime)
tracefs on /sys/kernel/tracing type tracefs (rw,nosuid,nodev,noexec,relatime)
configfs on /sys/kernel/config type configfs (rw,nosuid,nodev,noexec,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,nosuid,nodev,noexec,relatime)
ramfs on /run/credentials/systemd-sysusers.service type ramfs (ro,nosuid,nodev,noexec,relatime,mode=700)
/var/lib/snapd/snaps/core18_2812.snap on /snap/core18/2812 type squashfs (ro,nodev,relatime,errors=continue,threads=single,x-gdu.hide)
/var/lib/snapd/snaps/core20_2182.snap on /snap/core20/2182 type squashfs (ro,nodev,relatime,errors=continue,threads=single,x-gdu.hide)
/var/lib/snapd/snaps/amazon-ssm-agent_7628.snap on /snap/amazon-ssm-agent/7628 type squashfs (ro,nodev,relatime,errors=continue,threads=single,x-gdu.hide)
/var/lib/snapd/snaps/lxd_27037.snap on /snap/lxd/27037 type squashfs (ro,nodev,relatime,errors=continue,threads=single,x-gdu.hide)
/var/lib/snapd/snaps/snapd_20671.snap on /snap/snapd/20671 type squashfs (ro,nodev,relatime,errors=continue,threads=single,x-gdu.hide)
/dev/xvda15 on /boot/efi type vfat (rw,relatime,fmask=0077,dmask=0077,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,nosuid,nodev,noexec,relatime)
tmpfs on /run/snapd/ns type tmpfs (rw,nosuid,nodev,size=1624072k,nr_inodes=819200,mode=755,inode64)
nsfs on /run/snapd/ns/lxd.mnt type nsfs (rw)
tmpfs on /run/user/1000 type tmpfs (rw,nosuid,nodev,relatime,size=812032k,nr_inodes=203008,mode=700,uid=1000,gid=1000,inode64)
```

**Comment by mattmarcello** [comment]
@jotapea: are you still blocked on this?

**Comment by jotapea** [comment]
I've already tried all of those. I see there is a new v10.1.1 release, anything here that could have fixed the issue?

FYI, my server ran the v10.0 docker-compose installation just fine. Have you been able to run this installation with the most recent versions?

**Comment by adamkrellenstein** [comment]
@jotapea nothing in v10.1.1 would fix it, and I'm pretty sure that v10.1.0 is the same as v10.0.0 vis à vis Docker.

We run everything in Docker Compose as part of our continuous integration to make sure this always works (see https://github.com/CounterpartyXCP/counterparty-core/actions/workflows/test_compose.yml).

It looks to me like there's a problem with some directory not existing in your installs (because of user configuration or something), and Docker is failing to create the necessary mounts because of it.

**Comment by mattmarcello** [comment]
I wanted to make sure that you ran them in that order.  Sounds like you already have.

**Comment by jotapea** [comment]
My v10.0.0-rc1 node is at commit 005dad64, with a docker-compose.yml with the following last line:

```
device: ${COUNTERPARTY_DOCKER_DATA:-~/counterparty-docker-data}/
```

Which is different from the [current](https://github.com/CounterpartyXCP/counterparty-core/blob/5c0f680359294485e7c8367d5565aef95bc2db47/docker-compose.yml#L79). Then, my node also has this `~/counterparty-docker-data` folder.

Replicating these over the current `master` fixes this issue, but now https://github.com/CounterpartyXCP/counterparty-core/issues/1722 happens.

**Comment by mattmarcello** [comment]
@jotapea, going to close this out given that it seems updating the docker compose file to latest solved the volume mount issue for you.  Feel free to re-open if this assumption is incorrect.

**Comment by jotapea** [comment]
The latest docker compose didn't work for me, what worked was reverting it.

**Comment by mattmarcello** [comment]
I just did a clean install on a fresh VM without issues.  

This error message doesn't look right to me: 

` failed to mount local volume: mount /root/counterparty-core/${XDG_DATA_HOME:-~/.local/share}/counterparty-docker-data:/var/lib/docker/volumes/counterparty-core_data/_data, flags: 0x1000: no such file or directory`

I would expect to see the actual path there, rather than the unevaluated expression.  What version of docker are you using?

**Comment by mattmarcello** [comment]
To that end, could you try running `docker compose` instead of `docker-compose`

**Comment by jotapea** [comment]
I was using `sudo apt install docker-compose` as it was documented previously. But let me try it with the following instructions instead https://docs.docker.com/desktop/install/ubuntu/...

**Comment by jotapea** [comment]
Got it working with this Docker installation:

https://docs.docker.com/engine/install/ubuntu/#install-using-the-convenience-script

Thank you @mattmarcello for the follow ups! Closing.

**Comment by mattmarcello** [comment]
Nice.  It's a good catch because I think our docs still reference docker-compose.

**Comment by jotapea** [comment]
Yes they do (at least indirectly).
