### ISSUE TITLE
Lockfile

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#1697]
It's currently possible to run two Counterparty instances with the same DB... that's bad.

Also, I think we should use this to judge when we should run `quick_check`—we should only run it when the node hasn't been shut down cleanly. (Otherwise, one could ask, why should we only run it on startup?) We'll also have to be sure that the DB has the *chance* of being corrupted before we run this—it's too annoying to be aggressive with, unfortunately :/

**Comment by ouziel-slama** [comment]
it's a bit hackish but for the moment I don't see any other solution than to check the presence of a WAL file before connecting:

- if the file does not exist we continue as usual
- if the file exists we check with `lsof` if it is already open
    + if yes, there is already a connection to the database and we exit with an error
    + if not, this means that the server was not properly shut down, so we run a quick check and continue as usual.

**Comment by adamkrellenstein** [comment]
Interesting! Why can't we use a traditional lockfile?

**Comment by ouziel-slama** [comment]
We could! but anyway we need to check the presence of the WALL file (to detected a incorrect shutdown) so no reason to not use it as a lock file..

**Comment by ouziel-slama** [comment]
hum.. it's also more reliable I think.. no need to ensure to delete the lockfile..

**Comment by adamkrellenstein** [comment]
Hm, I don't like the idea of overloading the WAL file like this. I can't find any indication that we can rely on the WAL file either to determine whether (1) only one process is running, or (2) a process shut down incorrectly. Seems like using a separate lockfile is safer.

**Comment by ouziel-slama** [comment]
We are not overloading the WAL file.

1. By definition If the WAL or the DB file are open by a process that's means another process is using it. It's much more reliable than a lock file that can be deleted.
2. By definition if the database is closed correctly then the WAL file is deleted. If a WALL file exist and no one is connected to the database that's means for sure that the DB was not close correctly.

Seems like using the WAL file is safer.

**Comment by adamkrellenstein** [comment]
What you're saying totally makes sense! That's what I'd expect. But I can't find either of these statements supported by the documentation...

> 2. By definition if the database is closed correctly then the WAL file is deleted. If a WALL file exist and no one is connected to the database that's means for sure that the DB was not close correctly.

I don't want to make any bad assumptions, and I also don't see a problem with using a lockfile—it's standard and it's simple.

**Comment by ouziel-slama** [comment]
> I don't want to make any bad assumptions, 

From the SQLITE documentation (https://www.sqlite.org/wal.html):

> 4. The WAL File
> While a [database connection](https://www.sqlite.org/c3ref/sqlite3.html) is open on a WAL-mode database, SQLite maintains an extra journal file called a "Write Ahead Log" or "WAL File". The name of this file on disk is usually the name of the database file with an extra "-wal" suffix, though different naming rules may apply if SQLite is compiled with [SQLITE_ENABLE_8_3_NAMES](https://www.sqlite.org/compile.html#enable_8_3_names).

>The WAL file exists for as long as any [database connection](https://www.sqlite.org/c3ref/sqlite3.html) has the database open. Usually, the WAL file is deleted automatically when the last connection to the database closes. However, if the last process to have the database open exits without cleanly shutting down the database connection, or if the [SQLITE_FCNTL_PERSIST_WAL](https://www.sqlite.org/c3ref/c_fcntl_begin_atomic_write.html#sqlitefcntlpersistwal) [file control](https://www.sqlite.org/c3ref/file_control.html) is used, then the WAL file might be retained on disk after all connections to the database have been closed. The WAL file is part of the persistent state of the database and should be kept with the database if the database is copied or moved. If a database file is separated from its WAL file, then transactions that were previously committed to the database might be lost, or the database file might become corrupted. The only safe way to remove a WAL file is to open the database file using one of the [sqlite3_open()](https://www.sqlite.org/c3ref/open.html) interfaces then immediately close the database using [sqlite3_close()](https://www.sqlite.org/c3ref/close.html).


The documentation is clear on this subject: the WAL file only exists if there is an open connection. Moreover, if a WAL file exists during a connection there is a warning `WALL_RECOVERY_ERROR`.

>  and I also don't see a problem with using a lockfile—it's standard and it's simple.

In this particular case it is much less reliable to check that the database is already used and even less to check if the database has been closed.. if the lock file is still present the only sure and certain information is that we  failed to delete the file.. and I see no problem using the WAL file.

**Comment by adamkrellenstein** [comment]
ah okay gotcha! I'm convinced :)
