### ISSUE TITLE
Test Blockchain Reorganizations

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#1705]

**Comment by warrenpuffett** [comment]
Now that the rust fetcher has been merged into develop it is handling reorgs. All the python process needs to do is determine if the block, received from the `fetcher.get_block` call, has a height less than the highest height it has received. I have test in the rust code that mocks out a reorg but a "real life" test would be better. This is perhaps something that we can test manually. If we keep a counterparty node running, it will hit a reorg as they're not uncommon. When a reorg is hit we can watch how it is handled and then check against a block explorer to make sure that it was dealt with correctly. I think @ouziel-slama is probably already doing that? So I will assign this to him but happy to have a further discussion.

**Comment by adamkrellenstein** [comment]
So the important thing to test here is not so much the block fetching code as everything else, in Python. For that, a mock should be simple.

**Comment by adamkrellenstein** [comment]
https://github.com/CounterpartyXCP/counterparty-core/issues/2167
