### ISSUE TITLE
Healthz Endpoint Response

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#1713]
Response should be in JSON, otherwise it breaks syntax highlighting with standard utils. (Or we should change the content type of the response??)

<img width="523" alt="Screenshot 2024-04-19 at 3 48 29 PM" src="https://github.com/CounterpartyXCP/counterparty-core/assets/6189829/3c809f50-0626-4b13-be0e-1b5c37afc16d">

I think we should also say something like `{'status': 'catching-up'}`, `{'status': 'reorganization'}` etc. when returning a `503`.

Need to de-duplicate this with what we get for `/server/status` and `/`.

**Comment by ouziel-slama** [comment]
Here the current output for the two APIs
<img width="754" alt="Capture d’écran 2024-04-30 à 19 58 41" src="https://github.com/CounterpartyXCP/counterparty-core/assets/4574979/63580ee9-0934-41ca-aa51-73e4e5c8a7ee">

> I think we should also say something like {'status': 'catching-up'}, {'status': 'reorganization'} etc. when returning a 503.

hum.. this could be tricky for now.. let's keep this in mind when refactoring `blocks.follow` and mempool management..
also probably better to put more information in `/ ` and keep the healthz test boolean (we could add other checks transparently and all must pass to have a healthy server) ?

**Comment by adamkrellenstein** [comment]
Yep, sounds good!
