### ISSUE TITLE
ERROR:root:SQLITE_LOG: os_unix.c:44373: (2) open(/data/counterparty/counterparty.db) - No such file or directory (14) SQLITE_CANTOPEN

### ISSUE THREAD

**Issue by blocklack** [CounterpartyXCP/counterparty-core#1722]
I upgraded from version v10 to version v10.11 and got a block indexing error, deleted the database and the counterparty folder, redid docker compose with bootstrap and got this error.

![image](https://github.com/CounterpartyXCP/counterparty-core/assets/115724219/77448967-b501-4b28-9812-654787124ae6)

**Comment by blocklack** [comment]
![image](https://github.com/CounterpartyXCP/counterparty-core/assets/115724219/e7c4a338-c97f-4091-9fae-de76cbd23e01)

I think the bitcoin node when trying to synchronize, addrsindexr is not available and that's why bootstrap or normal startup fails.

**Comment by jotapea** [comment]
Getting the same:

```
counterparty-core_1  | ERROR:root:SQLITE_LOG: os_unix.c:44373: (2) open(/data/counterparty/counterparty.db) - No such file or directory (14) SQLITE_CANTOPEN
counterparty-core_1  | ERROR:root:SQLITE_LOG: cannot open file at line 44373 of [e876e51a0e] (14) SQLITE_CANTOPEN
```

May be related to the bootstrap not being downloaded?

**Comment by mattmarcello** [comment]
@jotapea @blocklack I reproduced this on my end.  Two things:

- despite the alarming logs, the issue resolved for me once bitcoind was done syncing 
- the deluge of `SQLITE_CANTOPEN` errors is actually related to a misconfigured error logger which we will be addressed in the next release

**Comment by mattmarcello** [comment]
As mentioned, this issue is more of a logging UX problem which has been addressed.  Closing for now.
