### ISSUE TITLE
TypeError: DatabaseVersionError-__init__() missing 1 required positional argument: 'from_block_index"

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#1723]
This was with Docker Compose on `master`.

![telegram-cloud-photo-size-4-5850425144772773941-y](https://github.com/CounterpartyXCP/counterparty-core/assets/6189829/89d599a1-ceb1-41ac-8448-d6ddaf6241c9)

**Comment by mattmarcello** [comment]
I think @ouziel-slama fixed this last week. 

https://github.com/CounterpartyXCP/counterparty-core/commit/8c394a0006443a8f402cdda5d9e6bf92e775c3db
