### ISSUE TITLE
Add `verbose` for all routes

### ISSUE THREAD

**Issue by ouziel-slama** [CounterpartyXCP/counterparty-core#1731]
if verbose==True, we carry out post-processing of the results for:
- inject `asset_longname` for all `*asset` fields
- inject `normalized_quantity` for all `*quantity` fields.
- inject `market_pair`, `market_dir` and `market_price` into orders
- inject `sats_per_dispense` and `sats_per_unit` into dispensers

see https://github.com/CounterpartyXCP/Documentation/pull/184#issuecomment-2078621895 and following comment.

**Comment by loon3** [comment]
It would also be helpful if the asset description was included in verbose results.

**Comment by ouziel-slama** [comment]
done here https://github.com/CounterpartyXCP/counterparty-core/pull/1756
Only `sats_per_dispense` and `sats_per_unit` are not calculated but dispensers info is included in dispenses responses.
See example in the PR.
