### ISSUE TITLE
Logging Problem ?

### ISSUE THREAD

**Issue by ouziel-slama** [CounterpartyXCP/counterparty-core#1733]
seen on api3:
<img width="769" alt="Capture d’écran 2024-04-26 à 16 36 15" src="https://github.com/CounterpartyXCP/counterparty-core/assets/4574979/814edacf-95d2-4aa2-9925-eba69b88b429">

- No output (but something in the log file)
- Unhandled exception without backtrace

**Comment by adamkrellenstein** [comment]
I'm seeing this on testnet now too, and a node just went down.

**Comment by adamkrellenstein** [comment]
Seems to me like this is a v high priority issue.

**Comment by ouziel-slama** [comment]
Python logs by default to stderr. Use `pm2 logs -err` to see the output.
