### ISSUE TITLE
Document usage with PM2

### ISSUE THREAD

**Issue by ouziel-slama** [CounterpartyXCP/counterparty-core#1737]
And eventually add a ready to use `ecosystem.config.js` file.

**Comment by adamkrellenstein** [comment]
I actually think we don't need to do this... This is just for our internal infrastructure.

**Comment by adamkrellenstein** [comment]
Like, it's really out of the box: `pm2 start 'counterparty-server start'`. And I don't think PM2 is anywhere near as popular as Docker to justify us having official support for it.

**Comment by ouziel-slama** [comment]
yeah make sense! pm2 is so much more fun to use than docker compose but I hadn't thought about the support lol! let's close!
