### ISSUE TITLE
Sentry Transaction Name

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#1740]
Health checks are not being filtered out by Sentry properly, and this is causing us to blow past our usage quotas.

<img width="1254" alt="Screenshot 2024-04-28 at 9 52 00 AM" src="https://github.com/CounterpartyXCP/counterparty-core/assets/6189829/5ce181ba-7c51-4bee-9a73-abc5d0c7a607">
<img width="761" alt="Screenshot 2024-04-28 at 9 52 24 AM" src="https://github.com/CounterpartyXCP/counterparty-core/assets/6189829/82bd99a4-7c89-4d83-852c-224ee7ecd841">
<img width="339" alt="Screenshot 2024-04-28 at 9 54 40 AM" src="https://github.com/CounterpartyXCP/counterparty-core/assets/6189829/1be35475-0b35-4401-888d-9152f661f1a9">

**Comment by ouziel-slama** [comment]
done here https://github.com/CounterpartyXCP/counterparty-core/pull/1763
