### ISSUE TITLE
counterpartycore.lib.exceptions.ParseTransactionError: ID mismatch in response

### ISSUE THREAD

**Issue by pinnate-modo** [CounterpartyXCP/counterparty-core#1753]
**Steps To Reproduce**
If you think you've found a bug, list the steps to reproduce the unexpected behavior:
1. Using `v10.1.1` run `counterparty-server start`

**Screenshots and Logfiles**
[counterparty_id_mismatch.log](https://github.com/CounterpartyXCP/counterparty-core/files/15165868/counterparty_id_mismatch.log)

**Comment by adamkrellenstein** [comment]
This is a problem with the addrindexrs code, which we're going to delete Soon(TM). Going to close as `wontfix` unless we see it again.
