### ISSUE TITLE
Audit Sentry Integration

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#1758]
* [x] Make sure all there no false positives/negatives
* [x] Make sure issues are filed for everything detected
* [x] Make sure new errors trigger alerts
* [x] Limit volumes to a reasonable quantity (make sure that we're not ingesting more logs that our subscription can handle, in particular with performance units)

* [x] The v2->v1 bridge shouldn't show up itself, I don't think? We should be seeing what the bridge redirects *to*, no?
<img width="695" alt="Screenshot 2024-07-24 at 7 07 38 PM" src="https://github.com/user-attachments/assets/641abdbf-139f-4456-b615-95d69f1b5e6f">

* [x] Missing stuff?
<img width="871" alt="Screenshot 2024-07-24 at 7 06 58 PM" src="https://github.com/user-attachments/assets/23dca112-ba96-49fa-9426-0b1c7dc9a9a8">

**Comment by ouziel-slama** [comment]
All that's missing is this PR: https://github.com/CounterpartyXCP/counterparty-core/pull/2110
