### ISSUE TITLE
Test hashes with other nodes after reparse

### ISSUE THREAD

**Issue by ouziel-slama** [CounterpartyXCP/counterparty-core#1778]

**Comment by ouziel-slama** [comment]
fixed here https://github.com/CounterpartyXCP/counterparty-core/pull/1779

**Comment by ouziel-slama** [comment]
Title updated.

**Comment by warrenpuffett** [comment]
@ouziel-slama What's going on with this issue? 

> fixed here #1779

I'm guessing this was a fix for a bug and now to add an extra layer of security we want to fetch hashes from other nodes to make sure we're in sync? Could you outline an algorithm for this?

**Comment by ouziel-slama** [comment]
> @ouziel-slama What's going on with this issue?
> 
> > fixed here #1779
> 
> I'm guessing this was a fix for a bug and now to add an extra layer of security we want to fetch hashes from other nodes to make sure we're in sync? Could you outline an algorithm for this?

yep! we are already comparing hashes with other servers here: https://github.com/CounterpartyXCP/counterparty-core/blob/master/.github/workflows/test_compose.sh#L103
ideally we should do a reparse of X blocks and then do this test..
the problem is that in this test we use `docker-compose` on this VM.. we have to run a `docker` command I think to start the reparse...

**Comment by ouziel-slama** [comment]
done here https://github.com/CounterpartyXCP/counterparty-core/pull/1836/commits/3aae579aabff1d865fb5db0304db729da5dda5b4
