### ISSUE TITLE
Update Apiary

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#1781]
The host isn't right... it should be on port `4000` and with a `v2` prefix. This may be an issue: https://github.com/CounterpartyXCP/counterparty-core/blob/6378d81dcef9dc3646111e815ed427268b09e9a5/apiary.apib#L2

<img width="1507" alt="image" src="https://github.com/CounterpartyXCP/counterparty-core/assets/6189829/8245420c-dc8e-435d-8c14-1bcbb99f33b7">

There's no `v2` prefix for the new root route... is that intentional?

<img width="628" alt="Screenshot 2024-05-09 at 11 43 52 PM" src="https://github.com/CounterpartyXCP/counterparty-core/assets/6189829/c4480cb8-f307-407f-9b7e-0e24aacdcc99">

**Comment by ouziel-slama** [comment]
Fixed here https://github.com/CounterpartyXCP/counterparty-core/pull/1776/commits/808f29a10999df85735b8875ea7ce5d79853c581
just v2 is not part of the host but of each url.
