### ISSUE TITLE
Invalid APIv2 Route Returns `Unknwon error`

### ISSUE THREAD

**Issue by pinnate-modo** [CounterpartyXCP/counterparty-core#1782]
**Steps To Reproduce**
If you think you've found a bug, list the steps to reproduce the unexpected behavior:

```
$ http localhost:4000/v2/healtz
HTTP/1.1 503 SERVICE UNAVAILABLE
Access-Control-Allow-Origin: *
Connection: close
Content-Length: 26
Content-Type: application/json
Date: Fri, 10 May 2024 01:06:48 GMT
Server: Werkzeug/3.0.1 Python/3.11.0rc1
X-BITCOIN-HEIGHT: 842783
X-COUNTERPARTY-HEIGHT: 842783
X-COUNTERPARTY-READY: True

{
    "error": "Unknwon error"
}
```

**Screenshots and Logfiles**
[api_json_error.txt](https://github.com/CounterpartyXCP/counterparty-core/files/15269209/api_json_error.txt)

**Comment by adamkrellenstein** [comment]
okay so there's a typo in your query and a typo in the response :)

the bad query *should* return a `404`

**Comment by ouziel-slama** [comment]
The problem comes from too generic route.
Fixed here https://github.com/CounterpartyXCP/counterparty-core/pull/1776/commits/e71fd07158aaac75d23f607969853f085d35aa13
