### ISSUE TITLE
Alternative Dispenser Upgrade Path

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#1784]
1. Add a `compose_dispense()` (using OP_RETURN with the `CNTRPRTY` prefix)
2. Have `compose_send('BTC')` (on both API v1 and v2) guess whether the TX should trigger a dispenser—if it does, silently turn it into a `compose_dispense()`.
3. Then we can track to see how much adoption there is of the new method etc. and remove existing, broken method of triggering dispensers later.

**Comment by jdogresorg** [comment]
freewallet-desktop and mobile use `create_send` API CALL to send BTC, so this upgrade path would work... 

1. Freewallet-desktop/mobile would not need to be updated
2. Freewallet-desktop/mobile would make calls to CP API to generate the tranasction
3. CP API can hand back normal BTC send or new DISPENSE command.

My main concerns are :
1. Not having to update freewallet-mobile (App/Play store licensing nonsense)
2. Not having users lose funds when doing a BTC send to a dispenser

This proposed upgrade path resolves the issues on my end... I would need to update my CP API servers (public.coindaddy.io and public.xchain.io) to run the latest version of CP... but as long as it has `get_messages` and this new `create_send` method is transparent... it should work well for my wallets/servers.

**Comment by ouziel-slama** [comment]
1. and 2. done here https://github.com/CounterpartyXCP/counterparty-core/pull/1809

**Comment by adamkrellenstein** [comment]
No reason to do this now, since @jdogresorg changed his mind and said he won't upgrade. We'll still implement (1) and (2) from the OP, however, for backwards-compatibility in the API.

**Comment by jdogresorg** [comment]
> No reason to do this now, since @jdogresorg changed his mind and said he won't upgrade. 

I did not change my mind, I never indicated that I wanted any changes for dispensers in a release, simply that this "alternative" proposal was better than one where you forced other changes on dispensers, breaking mobile wallets🤷‍♂️
