### ISSUE TITLE
Hard-coded transactions

### ISSUE THREAD

**Issue by jotapea** [CounterpartyXCP/counterparty-core#1791]
I am reading there is a plan to hard-code dispense transactions, to [remove dependencies](https://github.com/CounterpartyXCP/counterparty-core/issues/1764) of the software.

We already have a hard-coded list of [burns](https://github.com/CounterpartyXCP/counterparty-core/blob/master/counterparty-core/counterpartycore/mainnet_burns.csv).

My question (issue) is, why is this a goal for the current maintainers of the (reference implementation of the) protocol? I can easily understand that hard-coding data can improve the efficiency of some processes... but shouldn't this software be about reading the data written in Bitcoin?

I've been repeated that this can be verified with old versions of the protocol... but isn't the verification itself the PURPOSE of this software? Asking users to run old versions is literal obfuscation, thus REDUCING the trust of the protocol itself.

Counterparty, as a Bitcoin application, should abide by the same principle of "don't trust, verify".

**Comment by adamkrellenstein** [comment]
Hardcoding historical data that can trivially be verified with old versions of the software is not "literal obfuscation", and the trust model is completely unchanged when one is required to do so.

This GitHub repo is not the place for a remedial class in how blockchains work. If you want to learn, try asking for help on the [official forums](https://github.com/CounterpartyXCP/Forum/discussions).

**Comment by jotapea** [comment]
I want to learn, so made this into a [discussion](https://github.com/CounterpartyXCP/Forum/discussions/137).
