### ISSUE TITLE
setting up multiple dispensers on an address (only 1/8 was successful)

### ISSUE THREAD

**Issue by davestaxcp** [CounterpartyXCP/counterparty-core#1800]
running into something I haven't seen before with setting up dispensers.... 

I am in the process of setting up my new fake rare subassets (11 total) and main asset to dispense all tokens in a single dispenser (at the same price).... I sent through the first 8 txs.... but only the second one (???) I did is showing as valid on xchain and xcp dot dev.... 

Anybody know why this is happening? 

- I used Freewallet v0.9.31 and set up the dispenser using the Source as my main address and the Dispenser address as a new Segwit address (with no btc tx's on it as described in the FW User Manual: https://davestaxcp.gitbook.io/freewallet.io-user-manual/freewallet-functions/setting-up-a-dispenser)

- I was using the counterparty api in my server settings. (would it have been different if I used the xchain API?)

- - I am seeing an "Error 404.....message":"Error: Not Found","data":null}" on xcp dot dev for the unsuccessful tx's (1st tx ex: https://www.xcp.dev/tx/cde966e1da235b06103c44bae868e4b5625c27606edf1b221d62c09504b0b52a) - and shows as "not a counterparty tx" on xchain: https://xchain.io/tx/cde966e1da235b06103c44bae868e4b5625c27606edf1b221d62c09504b0b52a

- all tx's are confirmed and were mined in the same block

1st (unsuccessful): https://mempool.space/tx/cde966e1da235b06103c44bae868e4b5625c27606edf1b221d62c09504b0b52a

2nd (successful) disp tx opening: https://xchain.io/tx/68e7f2e8a91df5d1a7169be65d782c0ce7a20bf6a9463e3617a9c4657c25bb2b

3rd (unsuccessful): https://mempool.space/tx/8e8bd0d2f7b300039c38635a81dccb15e049f2f83abc9fec47958b3f3455d376

4th (unsuccessful): https://mempool.space/tx/d72d6f810118ad8c419060b3c47ba1eb6231fc268c50de9e164e455f2366e895

5th (unsuccessful): https://mempool.space/tx/1306ee0bc5feee90f1df6d46301f5a97cb12df40040bb9870c022824f941939d

6th (unsuccessful): https://mempool.space/tx/4c62cce657df2dd49d2457f6d8e5410100a399af99eaff122f53387afb282aa5

7th (unsuccessful): https://mempool.space/tx/64e87ebc73ca959066516ceadc96141c1d64c08dabe98b475290bbc3abd632da

8th (unsuccessful): https://mempool.space/tx/ae77b9cdb6e522900ac5e472ed0a625e7e42e4a68e3a17d70090880f99c4a0de

now at the moment (think of it from an artists perspective).... I am out $25 ish in BTC as lost funds..... and I will have to go buy more BTC and send it to myself to finish this process (which is a headache to say the least)... and not even sure if it will work after seeing this!

**Comment by davestaxcp** [comment]
upon further inspection looks like this was an issue already posted before: https://github.com/CounterpartyXCP/counterparty-core/issues/1534

**Comment by davestaxcp** [comment]
is it possible that these tx's being automatically converted into CPFP tx's be a base cause of the issue?

![image](https://github.com/CounterpartyXCP/counterparty-core/assets/136373423/e63d40db-3e2f-4d9d-9a55-4804e7b8b934)

**Comment by davestaxcp** [comment]
so I went ahead and tried again using the CP API as well as the xchain API and see this error:

So is it impossible now to set up multiple assets on a single dispenser (at the same price) to dispense multiple assets in a single tx??

Artists have been using this feature and relying on it for some time now... Super frustrating it is now allowed anymore.... was not aware this was the case.

Would this still work if I manually sent the assets to this dispenser address and then set them up from there (so the Source and Dispenser address are the same? which would be addy: bc1qv4mgsvt44ft6nuyyghduvz449mtqj52e6ayumv)

![serversettingsnewnewerror](https://github.com/CounterpartyXCP/counterparty-core/assets/136373423/cb55521f-8000-44ba-8bd9-f7ef237b8bee)

**Comment by davestaxcp** [comment]
Looks like this was just a misunderstanding from my end on how to set up dispensers with the new protocol changes in the past few months....(I am very used to the old way of doing things) Because of this I have updated the FW User Manual for setting up dispensers (to warn users not to make the same mistake I did) and have added this in the troubleshooting section:

https://davestaxcp.gitbook.io/freewallet.io-user-manual/troubleshooting-issues/error-composing-dispenser-tx-balance-history


I went ahead and tried doing the multiple dispenser openings (the old fashioned way) by sending the assets to the new address and opening them there so the Source address and Dispenser address are the same... and worked fine! 

in this example it would be on the btc addy: bc1qv4mgsvt44ft6nuyyghduvz449mtqj52e6ayumv - which now has the multiple dispensers opened like I originally intended

**Comment by adamkrellenstein** [comment]
Yep, this behavior is fixed by https://github.com/CounterpartyXCP/counterparty-core/issues/1670
