### ISSUE TITLE
Block Parsing Performance Optimizations

### ISSUE THREAD

**Issue by warrenpuffett** [CounterpartyXCP/counterparty-core#1805]
As [part](https://github.com/CounterpartyXCP/counterparty-core/blob/master/counterparty-core/counterpartycore/lib/gettxinfo.py#L267) of the kickstart/start process, we compute these properties:

- destinations
- btc_amount
- fee
- data
- potential_dispensers

This is one of the more expensive parsing operations and will run faster in the rust process. We would add this step [here](https://github.com/CounterpartyXCP/counterparty-core/blob/develop/counterparty-rs/src/indexer/bitcoin_client.rs#L72). So when this serialized block is passed to the python process it will have everything it needs.

For additional performance gains, we can move the logic for [get_transaction_sources](https://github.com/CounterpartyXCP/counterparty-core/blob/master/counterparty-core/counterpartycore/lib/gettxinfo.py#L140) into the same place in the rust process. This function can be quite expensive since it may require multiple calls to bitcoin core. The rust process has a pooled bitcoin core client that will perform these calls faster and in parallel when possible.

**Comment by adamkrellenstein** [comment]
would also love to see an updated flame graph for the `start` process and how it compares with `kickstart`.

when you run with the new `start` (I haven't had a chance yet), is the Python the bottleneck? what does the CPU usage look like?

**Comment by warrenpuffett** [comment]
Discussed this more in depth with @ouziel-slama. We have 3 performance optimizations.

1. #1831 which has a PR out #1847. According to perf profiles performed by Ouziel. The python json parsing was taking up ~15% of the total time. So utilizing "native" python (via pyo3) objects should increase performance significantly. This require no integration process other than a bit of manual testing.
2. Parse vouts as part of the block extraction worker in the rust fetcher. This is essentially replacing `parse_transaction_vouts` in the python code.  No integration work is necessary because this function will only be called when the block dict does not have the `parsed_vouts` property. The rust code will not include this property until block 333500 is reached as we rely on a legacy parsing strategy for blocks below that height. Once the optimization is tested and working then this python code can be removed.
3. We can replace `get_transaction_sources` in the python code by fetching transaction info for transaction Vins in the rust code. This is related to dispenser detection. This optimization is a bit tricky. If we don't port the dispenser detection logic to the rust code then we will be relying on a simple heuristic for when we should fetch transaction Vins. This will result in many false positives and could potentially decrease performance. As a result, we will start with 1 and 2, reprofile, and then see if it still makes sense to pursue this optimization.

**Comment by adamkrellenstein** [comment]
> Discussed this more in depth with @ouziel-slama. We have 3 performance optimizations.
> 
> * [x]  1. [Manually deserialize block object to PyDict #1831](https://github.com/CounterpartyXCP/counterparty-core/issues/1831) which has a PR out [Rust fetcher now returns a Dict instead of JSON bytes #1847](https://github.com/CounterpartyXCP/counterparty-core/pull/1847). According to perf profiles performed by Ouziel. The python json parsing was taking up ~15% of the total time. So utilizing "native" python (via pyo3) objects should increase performance significantly. This require no integration process other than a bit of manual testing.
> * [ ]  2. Parse vouts as part of the block extraction worker in the rust fetcher. This is essentially replacing `parse_transaction_vouts` in the python code.  No integration work is necessary because this function will only be called when the block dict does not have the `parsed_vouts` property. The rust code will not include this property until block 333500 is reached as we rely on a legacy parsing strategy for blocks below that height. Once the optimization is tested and working then this python code can be removed.
> * [ ]  3. We can replace `get_transaction_sources` in the python code by fetching transaction info for transaction Vins in the rust code. This is related to dispenser detection. This optimization is a bit tricky. If we don't port the dispenser detection logic to the rust code then we will be relying on a simple heuristic for when we should fetch transaction Vins. This will result in many false positives and could potentially decrease performance. As a result, we will start with 1 and 2, reprofile, and then see if it still makes sense to pursue this optimization.

Let's break these up into separate issues, with (3) moved out of this milestone.

**Comment by adamkrellenstein** [comment]
See https://github.com/CounterpartyXCP/counterparty-core/issues/1960

**Comment by adamkrellenstein** [comment]
With https://github.com/CounterpartyXCP/counterparty-core/issues/1957 (1) and (2) are no longer a major bottleneck.
