### ISSUE TITLE
Refactor Kickstart

### ISSUE THREAD

**Issue by ouziel-slama** [CounterpartyXCP/counterparty-core#1813]
- blk file reader is just a backend..
- ...with the same interface as the Rust fetcher..
- ...and an additional method `get_transaction(tx_hash)`.

**Comment by warrenpuffett** [comment]
With the new rust fetcher, I believe the goal should be to utilize it to unify start & kickstart. @ouziel-slama and I have discussed perf optimization strategies to improve start performance. If that isn't "enough" then we could even host N bitcoin core nodes and, by default, point the fetcher at all of them. Currently the bottleneck is the python process' block parsing anyways. I'll leave this issue open for discussion but I do not think it belongs in this milestone as it is more than a bug fix.

**Comment by adamkrellenstein** [comment]
So we definitely can't be asked to host multiple bitcoin nodes.

And we shouldn't do any optimization here (or anywhere) until we have some benchmarks.

**Comment by adamkrellenstein** [comment]
That said, I agree, we should just kill kickstart asap.

**Comment by warrenpuffett** [comment]
> So we definitely can't be asked to host multiple bitcoin nodes.
> 
> And we shouldn't do any optimization here (or anywhere) until we have some benchmarks.

Makes sense. If we did want to allow people to point at multiple bitcoin nodes (that they host) that's something we could implement/enable in the future.

**Comment by adamkrellenstein** [comment]
Obviated by https://github.com/CounterpartyXCP/counterparty-core/issues/1649
