### ISSUE TITLE
API v1 returning `result` inside of `result`

### ISSUE THREAD

**Issue by DerpHerpenstein** [CounterpartyXCP/counterparty-core#1816]
Occasionally the response from the v1 counterparty API returns the result inside of a result. This seems to be happening across the v10 API in general, I don't recall ever seeing this error in v9.  At this point I've seen it happen on multiple endpoints so it seems to be at a high level in the api response generation.

**Steps To Reproduce**
Use the following v1 api call to get dispensers, and do it 50-100 times.  It doesn't happen every time, were looking at something intermittent that occurs 1%-2% of the time. 

`{"method":"get_dispensers","params":{"offset":-20,"limit":20,"filters":[{"field":"source","op":"==","value":"bc1qy25gwr9vdrvxx0w35wa9vrpc3hc5h6rd0p56f4"},{"field":"origin","op":"==","value":"bc1qy25gwr9vdrvxx0w35wa9vrpc3hc5h6rd0p56f4"},{"field":"asset","op":"==","value":"bc1qy25gwr9vdrvxx0w35wa9vrpc3hc5h6rd0p56f4"}],"filterop":"or","order_by":"tx_index","order_dir":"DESC"},"jsonrpc":"2.0","id":0}`

**Screenshots of anomalous behavior**
![image](https://github.com/CounterpartyXCP/counterparty-core/assets/99779492/02381664-0287-498b-8ffd-592e1dbb32bd)

**Screenshot of expected behavior**
![image](https://github.com/CounterpartyXCP/counterparty-core/assets/99779492/d3b82bdb-2ac3-4b76-8e98-3fdcbf63c2fb)

**Meme**
![image](https://github.com/CounterpartyXCP/counterparty-core/assets/99779492/602b13c0-3769-455f-bfb3-4160c1a7a2af)

**Comment by loon3** [comment]
seeing this sporadically as well with all v1 API calls

**Comment by adamkrellenstein** [comment]
Okay yeah this is a high priority.

**Comment by ouziel-slama** [comment]
@DerpHerpenstein @loon3 do you get this with https://api.counterparty.io:4000/v1/ ?

**Comment by loon3** [comment]
very first get_running_info query returned...

```
{"result": {"result": {"server_ready": true, "db_caught_up": true, "bitcoin_block_count": 845788, "last_block": {"block_index": 845788, "block_hash": "0000000000000000000084f802821b7e9d60478990586c29eb7238fdbbb77faa", "block_time": 1717074351, "previous_block_hash": "00000000000000000002c1e0889bfb79b7142185cc9c147850d180af85d4fecb", "difficulty": 84381461788831.34, "ledger_hash": "59b55b3e562663c0729fdef7d4c7194450a97d133741f5086232a9122c9c9939", "txlist_hash": "e0a13aa3e3a3cf1f7d15442805407c88f3f8899b96efa4a0c6819b7b4cb49757", "messages_hash": "56dbc11de759bf284c6002dbe9b4dd33859fda82f9e29da2b03b8d2d88a66494"}, "indexd_caught_up": true, "indexd_blocks_behind": 0, "last_message_index": 14274292, "api_limit_rows": 1000, "running_testnet": false, "running_regtest": false, "running_testcoin": false, "version_major": 10, "version_minor": 1, "version_revision": 2, "addrindexrs_version_major": 0, "addrindexrs_version_minor": 4, "addrindexrs_version_revision": 6, "uptime": 644183, "dockerized": true, "force_enabled": false}, "id": 0, "jsonrpc": "2.0"}}
```

**Comment by ouziel-slama** [comment]
ok thanks! make sense! if you use `/v1` you will always get the result in the result.. and if you use `/` only sometimes..
The bug is fixed here https://github.com/CounterpartyXCP/counterparty-core/pull/1833
