### ISSUE TITLE
Eliminate Fee on Subasset Registration

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#1840]

**Comment by ffmad** [comment]
Thanks for the post! This was a proposal I made on XCP dinner in Lisbon.

The short idea: fees on subassets makes no sense and limit the use of the protocol.

### Subassets are great, and can be seen as "subdomains" of an asset for many use cases

In 2020 I made a post on CryptoArt explaining how to use Counterparty and how the subassets could be used by artists to name their art with their artist name as the root: https://beta.cent.co/ffmad/+sutrha

The idea is that if your main asset is "FFMAD" you can then create a piece called "FFMAD.My_superb_art_piece".

But it is not limited to just naming piece, you could also **create collections** like this, such as "CRYPTOPUNK.00001" ... "CRYPTOPUNK.10000".

The main point here is that this could help assemble everything under the same roof **without the need of a central indexer**.

#### Creation of "Sub_protocols" ?

We can also think that subprotocol could be created to take advantages of subassets to put more data on chain, like asset properties.

For example "FFMAD.MyArt_#P_#1_Background_Blue_#2_Topic_Pepe" to say that properties of the asset "MyArt" from artist "ffmad" are "Blue" "Background" and "Pepe" "Topic".

Without doubts, I can imagine people imagine a lot of uses cases.

### Subassets like subdomains should be free.

Subassets are like subdomains, you paid for the main domain and you can create how many subdomains you want for free. The **XCP fee of the assets is against name squatting / spam**. There is no name squatting / spam of subdomains as only the owner can create them, thus a XCP fee makes no sense at all.

If the idea of the fee is to give value to the $XCP token, it is like shooting oneself in the foot. **Subassets are currently massively underused**. Why make a subasset when you can make an asset for a little more?

The main problem of pricing here is that XCP asset fee is - on the contrary - really low. Paying just **0.5 XCP for a LIFELONG OWNERSHIP of a domain is nothing**.

### My Conclusion

Subassets are a great tool of the Couterparty metaprotocol, and as "subdomains", should be free of a Counterparty fee _(you already pay a BTC fee)_. This would allow builders to **create more use cases for Counterparty** and artists to manage their collections better. We should do that change soon.

On the other side, we should open a discussion on the asset registration fee of 0.5 $XCP. This is way too low (it should probably be 5 $XCP+ atm). @adamkrellenstein discussed a dynamic fee at that Lisbon dinner, and it could be an interesting thing the explore.

**Comment by reinamora137** [comment]
This pairs well with the subassets for numerics for the same reasons mentioned: https://github.com/CounterpartyXCP/counterparty-core/issues/1842

**Comment by mikeinspace** [comment]
I agree with this given recent clarification that the XCP fee is an "anti-squat" mechanism and not an "anti-spam" mechanism, it does not make sense that it be applied to sub-assets as you can't "squat" yourself.

**Comment by b1u3y** [comment]
IMO, this makes sense for named assets only. There is another discussion about sub-assets for numerics. Would subassets for numerics be an integer or a string?

If no XCP was paid for the main asset, should subassets be free too? This decision will greatly affect usage, and adoption. Free subasset mass adoption could lead to assets being tracked in code & db by main asset, instead of UTXO or address.

**Comment by pinnate-modo** [comment]
IMO subassets for numericals should only be numerical, otherwise it'd be trivial to create metaprotocols that get around the fees for named assets while essentially maintaining all the benefits of the latter.

**Comment by mikeinspace** [comment]
> IMO subassets for numericals should only be numerical, otherwise it'd be trivial to create metaprotocols that get around the fees for named assets while essentially maintaining all the benefits of the latter.

The fee is trivial as it would be paid once on a named asset allowing for an infinite number of free sub-assets anyways. If the concern is that metaprotocols on numerics will "get the benefits" of named assets "for free", then why are we even considering eliminating the fees on subassets at all?

Once again, I return to the concept that xcp fees on asset registrations are an anti-squat mechanism, which makes sense at the global namespace level. On Counterparty, there can only be one TEST. There can only be one RAREPEPE. Therefore, A7337447728884561000.TEST in no way "competes" with TEST. 

I see no reason to constrain subassets on numerics to being numerics *only* when a named subasset in no way competes with a named asset, anyways.
