### ISSUE TITLE
Holdover from Old `mempool` Parsing is 20% of the Run-Time for Early Blocks

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#1858]
https://github.com/CounterpartyXCP/counterparty-core/blob/6378d81dcef9dc3646111e815ed427268b09e9a5/counterparty-core/counterpartycore/lib/blocks.py#L651

**Comment by ouziel-slama** [comment]
with the new mempool system I don't see how this edge case can happen. I removed this check btw here: https://github.com/CounterpartyXCP/counterparty-core/pull/1856/commits/ab446c6e7ca6a2bc146bf77b4eb39757c7864265
