### ISSUE TITLE
Graceful shutdown with `docker compose stop`

### ISSUE THREAD

**Issue by ouziel-slama** [CounterpartyXCP/counterparty-core#1862]
Everything seems normal in the log.. db connections are closed... but WAL file still here..

**Comment by adamkrellenstein** [comment]
unfortunately yeah I don't think that the WAL file's existence is a perfect indicator of a successful shutdown :/

**Comment by ouziel-slama** [comment]
The sqlite documentation says otherwise.

**Comment by adamkrellenstein** [comment]
it's up to you if you want to try to get it working this way! I still think a simple lockfile is the better solution ❤️

**Comment by ouziel-slama** [comment]
fixed here https://github.com/CounterpartyXCP/counterparty-core/pull/1869
