### ISSUE TITLE
`get_tx_info_*` Accounts for Most Parsing Time

### ISSUE THREAD

**Issue by pinnate-modo** [CounterpartyXCP/counterparty-core#1878]
Using `develop` (commit `d3bc818ff056fdb42a9d146c60a14aed2c655852`) I am syncing with `start`. It's much, much faster than `start` with `v10.1.2` but I noticed that `get_tx_info_legacy` (around block 310,000) and `get_tx_info
_new` (around block 346,000) are taking up almost all of the parsing time, where each is used.

GitHub won't let me attach pyspy svgs so below are png flamegraphs.

![start-blk-310000](https://github.com/CounterpartyXCP/counterparty-core/assets/159686725/a23e5078-e13a-446b-92be-bc6028466c62)
![start-blk-346000](https://github.com/CounterpartyXCP/counterparty-core/assets/159686725/7170d3e8-3d42-4006-9ba6-9042fec849df)

**Comment by adamkrellenstein** [comment]
This should be dealt with by #2 here https://github.com/CounterpartyXCP/counterparty-core/issues/1805#issuecomment-2143267139
