### ISSUE TITLE
More Detailed `InsufficientBTC` Error

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#1895]
Improve the insufficient btc error so that it clearly states how many btc are needed *including* the fee, and how many btc are available

**Comment by pinnate-modo** [comment]
It should also say that the fee is needed to get the tx included in the _next_ block, and that the user may either pass `confirmatiom_target` to get a fee estimation for a specific number of blocks out or pass `fee` to manually set the fee .
