### ISSUE TITLE
API Result Sorting and Filtering

### ISSUE THREAD

**Issue by loon3** [CounterpartyXCP/counterparty-core#1917]
I'm finding that anything with a limit parameter also needs a sort parameter (or at the very least to be automatically sorted by tx_index).

For example, this call (https://api.counterparty.io:4000/v2/orders/PEPECASH/XCP?status=filled) obviously has a ton of results as its been an active pair over the years, but the results appear to be sorted alphanumerically by tx_hash.   Using a limit parameter here doesn't return useful results because it effectively just returns random txs from the list.

Also, having the ability to return order matches by asset or asset pair is helpful for showing order histories as using orders only doesn't give the full picture (indicating the two order txs that actually matched to result in the fill).  Currently v2 only offers the ability to return order matches by tx hash.

**Comment by droplister** [comment]
After working with the API a few days, the main sorts I would use:
- Asset Holder Balances (Hi > Lo)
- Address Balances (Alphabetical)
- - Ideally subassets are sorted by their longname.

**Comment by ouziel-slama** [comment]
see https://github.com/CounterpartyXCP/counterparty-core/pull/2070
