### ISSUE TITLE
Add endpoint to get BTC balances

### ISSUE THREAD

**Issue by dime-squanderer** [CounterpartyXCP/counterparty-core#1922]
Rather than relying on another public bitcoin node, I would be able to get btc balances from counterparty api

**Comment by ouziel-slama** [comment]
Bitcoin Core does not offer a command to obtain the balance of an arbitrary address.
You can use `/v2/bitcoin/addresses/<address>/utxos` and add up the unspent amounts (it's an `addrindexrs` command despite the url).

**Comment by adamkrellenstein** [comment]
Yeahhhh this is a wontfix because of https://github.com/CounterpartyXCP/counterparty-core/issues/1764
