### ISSUE TITLE
Inconsistent Mempool

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#1925]
<img width="718" alt="Screenshot 2024-06-13 at 8 59 04 AM" src="https://github.com/CounterpartyXCP/counterparty-core/assets/6189829/24561a33-4ba6-4e0a-8cae-8f02bcdab9ff">

[mempool.json](https://github.com/user-attachments/files/15815137/mempool.json)

**Comment by ouziel-slama** [comment]
what version of `counterparty-server` ?  before v10.2.0 it's "normal".

**Comment by adamkrellenstein** [comment]
```
6:04.631772000+00:00 - [    INFO] - Shutting down logging...
2024-06-26T10:16:04.633022000+00:00 - [    INFO] - Stopping fetcher...
2024-06-26T10:16:04.633863000+00:00 - [    INFO] - Shutdown complete.
```

**Comment by adamkrellenstein** [comment]
Unable to reproduce.
