### ISSUE TITLE
mismatch in order state across /transactions/<order_hash> and /orders/<order_hash>

### ISSUE THREAD

**Issue by mattmarcello** [CounterpartyXCP/counterparty-core#1940]
See https://github.com/UnspendableLabs/Horizon-Explorer/issues/62

**Comment by ouziel-slama** [comment]
this is normal.. `/transactions/<order_hash>` returns the data embedded in the transaction used to open the order.. `/orders/<order_hash>` returns the current status of the order.

**Comment by mattmarcello** [comment]
hmm.  if it's always returning the data embedded in the transaction used to open the order, will the status always be "open"?
