### ISSUE TITLE
Dispenser discrepancy

### ISSUE THREAD

**Issue by niftyboss1** [CounterpartyXCP/counterparty-core#1969]
Just noticed something weird with this dispenser:

316b9b9b503487cb1f214b39e6ba9f1821d11eddcbe045e253ea72ea53fb5b8b

When accessing it directly, I can find its details. Status is 10 (closed) as expected.   
   https://api.counterparty.io:4000/v2/dispensers/316b9b9b503487cb1f214b39e6ba9f1821d11eddcbe045e253ea72ea53fb5b8b

However, I'm unable to find it when querying for all PEPECASH dispensers with status 10:
  https://api.counterparty.io:4000/v2/assets/PEPECASH/dispensers?status=10&limit=5000

Please let me know if more details are needed.  
Thanks!

**Comment by ouziel-slama** [comment]
The problem comes from this group by: https://github.com/CounterpartyXCP/counterparty-core/blob/master/counterparty-core/counterpartycore/lib/api/queries.py#L1322
fixed with the new API database.
