### ISSUE TITLE
Dev Testnet Failing to Keep Up

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#1979]
If this is a ZeroMQ issue, then we need to switch to using the Rust process at least until we can make the ZeroMQ fully robust.

<img width="1458" alt="Screenshot 2024-06-28 at 11 51 34 AM" src="https://github.com/CounterpartyXCP/counterparty-core/assets/6189829/31616b3a-3832-4dbf-aa45-b93ed8126e6a">
https://console.cloud.google.com/logs/query;query=%22503%22%0Aresource.labels.instance_id%3D%226188892154008299866%22;cursorTimestamp=2024-06-28T09:50:56.668339720Z;duration=P7D?project=noted-extension-407918

**Comment by droplister** [comment]
I think I'm encountering something like this on mainnet with 10.2. Once my nodes are caught up and switch to zmq blockchain watcher, new bitcoin blocks are found but counterparty-core does not progress. Fixed by putting the docker profile down/up.

Possibly relevant information from the ZMQ docs: https://github.com/bitcoin/bitcoin/blob/master/doc/zmq.md

> Note that for *block topics, when the block chain tip changes, a reorganisation may occur and just the tip will be notified. It is up to the subscriber to retrieve the chain from the last known block to the new tip. Also note that no notification will occur if the tip was in the active chain--as would be the case after calling invalidateblock RPC. In contrast, the sequence topic publishes all block connections and disconnections.
>
> There are several possibilities that ZMQ notification can get lost during transmission depending on the communication type you are using. Bitcoind appends an up-counting sequence number to each notification which allows listeners to detect lost notifications.
>
>The sequence topic refers specifically to the mempool sequence number, which is also published along with all mempool events. This is a different sequence value than in ZMQ itself in order to allow a total ordering of mempool events to be constructed.

**Comment by adamkrellenstein** [comment]
@droplister the above issue was addressed by changing the poll interval for testnet. @droplister it sounds like you have a ZeroMQ configuration problem. (See https://docs.counterparty.io/docs/basics/manual-installation/) If you have the correct Bitcoin Core config, please file a new issue and upload the complete log files for both Bitcoin Core and Counterparty Core.
