### ISSUE TITLE
Quick Check on Startup that Bitcoin Core is Accessible

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#1983]

**Comment by warrenpuffett** [comment]
@Ouziel The idea here is we want counterparty-core to exit with a "good" message to the user about BitcoinCore not being up. Any thoughts on where in the code this could live? Ideally before we startup the rust fetcher I think.

**Comment by warrenpuffett** [comment]
Ok I've confirmed that this logic already exists! https://github.com/CounterpartyXCP/counterparty-core/blob/5e0cf15772a2788703bb69ebdce769e47bdee44b/counterparty-core/counterpartycore/lib/backend/bitcoind.py#L60

All we need to do is changing this from `debug` to `warning` so the user can see this message. Thoughts @Ouziel @adamkrellenstein ?

**Comment by adamkrellenstein** [comment]
makes sense to me!

**Comment by ouziel-slama** [comment]
yeah!
