### ISSUE TITLE
GetBalancesByAddresses

### ISSUE THREAD

**Issue by mattmarcello** [CounterpartyXCP/counterparty-core#1985]
We need a way to get balances across a set of accounts in a single request.  

One possible API but open to all of your suggestions here :)

```{ result: balances: [ {  asset: "XCP", total: 10, { [address_1]: 5, [address_2]: 4 } }]```

I'm not sure if we need pagination here, practically.  Although technically, it's probably the right thing to do.

**Comment by ouziel-slama** [comment]
done here https://github.com/CounterpartyXCP/counterparty-core/pull/2041
