### ISSUE TITLE
`404` Errors Under Load

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#1986]
@mattmarcello to fill in details

**Comment by mattmarcello** [comment]
reproducible with this command:

```autocannon  https://api.counterparty.io:14000/v2/addresses/tb1q6c4r68274alzkjchfd3yx4e0ff0e08ktyps/balances```

https://www.npmjs.com/package/autocannon

**Comment by adamkrellenstein** [comment]
Not reproducible locally? LB issue?

**Comment by adamkrellenstein** [comment]
Not a node issue. See https://github.com/UnspendableLabs/infrastructure/issues/41
