### ISSUE TITLE
utxos V2 upstream request timeout

### ISSUE THREAD

**Issue by loon3** [CounterpartyXCP/counterparty-core#1990]
The utxos call takes a very long time (10 seconds+) or results in timeout for addresses with a large tx history.

Ex.  https://api.counterparty.io:4000/v2/bitcoin/addresses/1AtcSh7uxenQ6AR5xqr6agAegWRUF5N4uh/utxos?unconfirmed=true

**Comment by adamkrellenstein** [comment]
yeah, this is being addressed in this PR: https://github.com/CounterpartyXCP/counterparty-core/pull/1928
