### ISSUE TITLE
XCP and BTC Asset Info

### ISSUE THREAD

**Issue by droplister** [CounterpartyXCP/counterparty-core#2034]
I think it could make sense to leave asset_longname and descriptions on these assets blank. Ran into it while working on my explorer.

https://github.com/CounterpartyXCP/counterparty-core/blob/5e0cf15772a2788703bb69ebdce769e47bdee44b/counterparty-core/counterpartycore/lib/ledger.py#L795-L810

"Counterparty" and "Bitcoin" are accurate display names, but not the names you'd use in a send or order, for example.

It's pretty minor and I've just had to make a small change to my asset name formatter to handle, but asset_longname is an artifact of the subasset name implementation and with this update XCP and BTC are using asset_longname in a different/unexpected way.

Also I would consider making BTC locked = true.

**"The Impact" in my application....**

Name formatting function before:
```
export const formatAssetName = (assetName, assetInfo) => {
  return assetInfo?.asset_longname ?? assetName;
};
```

Name formatting function after:
```
export const formatAssetName = (assetName, assetInfo) => {
  if (assetName === 'XCP') return 'XCP'
  if (assetName === 'BTC') return 'BTC'
  return assetInfo?.asset_longname ?? assetName;
};
```

**Comment by ouziel-slama** [comment]
done here https://github.com/CounterpartyXCP/counterparty-core/pull/2059
