### ISSUE TITLE
Do Not Return Asset Description when Not Verbose

### ISSUE THREAD

**Issue by droplister** [CounterpartyXCP/counterparty-core#2036]
Working with the API and the verbose settings are very handy indeed. I think description is one field that could be removed from the asset info. Especially with stamps, asset descriptions can be rather large. Asset descriptions don't tend to be something needed in a list of assets or balances or events and can be fetched on a individually if someone wants to drill down into a specific asset.

**Comment by adamkrellenstein** [comment]
So you're saying cut the description when `verbose=false`?

**Comment by ouziel-slama** [comment]
hum.. perhaps we should support `verbose=<interger>`: `verbose=1` => exclude description and `verbose=2` => include description..

**Comment by adamkrellenstein** [comment]
I'd rather have a "description" flag.

**Comment by droplister** [comment]
I find that, in general, I only want the asset description If I'm indexing all assets in a table or if I'm looking at one single asset.

When I am displaying balances of an address, I don't need the descriptions. And I think that's probably the case with a lot of lists in an explorer or wallet use case.

**Comment by adamkrellenstein** [comment]
Yeah, I'd rather not assume that. In general, iff you're passing `verbose=true`, then you should expect a lot of data. Going to change this issue accordingly.

**Comment by droplister** [comment]
Alright, that's not my issue, so I'll close this.
