### ISSUE TITLE
Get Transactions By Addresses / Get Mempool by Addresses

### ISSUE THREAD

**Issue by mattmarcello** [CounterpartyXCP/counterparty-core#2042]
In order to have first class support for "Accounts" ( i.e. a composition of N addresses ) in the wallet, we need a way to get all transactions by a set of addresses and all mempool events by a set of addresses. 

For context, this will power an account level transactions feed.

**Comment by ouziel-slama** [comment]
done here https://github.com/CounterpartyXCP/counterparty-core/pull/2059
