### ISSUE TITLE
Testnet TX List Hash Break

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2044]
<img width="1060" alt="image" src="https://github.com/CounterpartyXCP/counterparty-core/assets/6189829/5fa5adb5-6662-4f2a-ab12-405df07f4c71">

**Comment by droplister** [comment]
Try deleting: `/.local/share/counterparty` and try again. It worked for me here: https://github.com/CounterpartyXCP/counterparty-core/issues/2024

**Comment by adamkrellenstein** [comment]
If there's a consensus hash because of a db migration, that's an actual bug and needs to be investigated.

**Comment by ouziel-slama** [comment]
fixed here https://github.com/CounterpartyXCP/counterparty-core/pull/2057
