### ISSUE TITLE
inconsistent api behavior when querying asset resourses by `asset.asset` vs `asset.asset_longname`

### ISSUE THREAD

**Issue by mattmarcello** [CounterpartyXCP/counterparty-core#2048]
❯ curl https://dev.counterparty.io:4000/v2/assets/barf.pepe | jq .
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   374  100   374    0     0   5513      0 --:--:-- --:--:-- --:--:--  5500
{
  "result": {
    "asset": "A3423842286956990730",
    "asset_id": "3423842286956990730",
    "asset_longname": "BARF.PEPE",
    "issuer": "14VhF5JGExMn4qkN2RiMqNvCwpqmFvbQaz",
    "owner": "14VhF5JGExMn4qkN2RiMqNvCwpqmFvbQaz",
    "divisible": false,
    "locked": false,
    "supply": 0,
    "description": "ruderelics.io/sBnkB.json",
    "first_issuance_block_index": 851282,
    "last_issuance_block_index": 851282
  }
}

horizon-explorer on  main [$!] via  v20.11.0 on ☁️  matt.marcello@gmail.com
❯ curl https://dev.counterparty.io:4000/v2/assets/barf.pepe/issuances  | jq .
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    54  100    54    0     0    803      0 --:--:-- --:--:-- --:--:--   805
{
  "result": [],
  "next_cursor": null,
  "result_count": 0
}

horizon-explorer on  main [$!] via  v20.11.0 on ☁️  matt.marcello@gmail.com
❯ curl https://dev.counterparty.io:4000/v2/assets/A3423842286956990730/issuances  | jq .
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   576  100   576    0     0   7931      0 --:--:-- --:--:-- --:--:--  8000
{
  "result": [
    {
      "tx_index": 2739615,
      "tx_hash": "300fc59272c54dd04e3524c1c9d0f461085d72da827976ecb429ceb2ea2079a5",
      "msg_index": 0,
      "block_index": 851282,
      "asset": "A3423842286956990730",
      "quantity": 0,
      "divisible": false,
      "source": "1RUDEjgtMCY8kSJUUvTv4KHMGFgg9LrgF",
      "issuer": "14VhF5JGExMn4qkN2RiMqNvCwpqmFvbQaz",
      "transfer": true,
      "callable": false,
      "call_date": 0,
      "call_price": 0,
      "description": "ruderelics.io/sBnkB.json",
      "fee_paid": 25000000,
      "locked": false,
      "status": "valid",
      "asset_longname": "BARF.PEPE",
      "reset": false
    }
  ],
  "next_cursor": null,
  "result_count": 1
}

**Comment by ouziel-slama** [comment]
fixed here https://github.com/CounterpartyXCP/counterparty-core/pull/2041/commits/f83430c89fa7dbac0aafb1b0d214cc752513a681
