### ISSUE TITLE
Question: How to Know TX is Valid in Counterparty via API

### ISSUE THREAD

**Issue by droplister** [CounterpartyXCP/counterparty-core#2066]
I'm making a page template like `/tx/[tx_hash]` and I want to be able to tell users whether a tx is confirmed/unconfirmed by the Bitcoin miners and whether it's valid/invalid in the Counterparty ledger, if it is confirmed.

Take for example this tx: `378f6ebeb82fa9f9bf37af7e685e84bd91d53a90d19a182c0d02dc1a9cbccd12`, which is an invalid issuance of XCP, what's the best way via the API to know whether a confirmed tx is valid or not from the tx_hash?

**Get Transaction**
https://api.counterparty.io:4000/v2/transactions/378f6ebeb82fa9f9bf37af7e685e84bd91d53a90d19a182c0d02dc1a9cbccd12
```
{
  "result": {
    "tx_index": 1174,
    "tx_hash": "378f6ebeb82fa9f9bf37af7e685e84bd91d53a90d19a182c0d02dc1a9cbccd12",
    "block_index": 280635,
    "block_hash": "000000000000000125f409c83c88d31dfad61437c8c1ce4999ade6fbedc46462",
    "block_time": 1389798086,
    "source": "1CUdFmgK9trTNZHALfqGvd8d6nUZqH2AAf",
    "destination": null,
    "btc_amount": null,
    "fee": 10000,
    "data": "0000001400000000000000010000001f2124190001",
    "supported": true,
    "unpacked_data": {
      "message_type": "issuance",
      "message_type_id": 20,
      "message_data": {
        "asset_id": 1,
        "asset": "XCP",
        "subasset_longname": null,
        "quantity": 133700000000,
        "divisible": true,
        "lock": false,
        "reset": false,
        "callable": false,
        "call_date": 0,
        "call_price": 0,
        "description": "",
        "status": "valid"
      }
    }
  }
}
```
_This view shows supported = true and status = valid._

**Get Transaction Events**
https://api.counterparty.io:4000/v2/transactions/378f6ebeb82fa9f9bf37af7e685e84bd91d53a90d19a182c0d02dc1a9cbccd12/events
```
{
  "result": [],
  "next_cursor": null,
  "result_count": 0
}
```
_No events are returned by this endpoint. Is that the best way to check right now? If no events, not valid?_

**Get Asset Issuances**
https://api.counterparty.io:4000/v2/assets/XCP/issuances
```
{
  "result": [
    {
      "tx_index": 1174,
      "tx_hash": "378f6ebeb82fa9f9bf37af7e685e84bd91d53a90d19a182c0d02dc1a9cbccd12",
      "msg_index": 0,
      "block_index": 280635,
      "asset": "XCP",
      "quantity": 133700000000,
      "divisible": true,
      "source": "1CUdFmgK9trTNZHALfqGvd8d6nUZqH2AAf",
      "issuer": "1CUdFmgK9trTNZHALfqGvd8d6nUZqH2AAf",
      "transfer": false,
      "callable": false,
      "call_date": 0,
      "call_price": 0,
      "description": "",
      "fee_paid": 0,
      "locked": false,
      "status": "invalid: cannot issue BTC or XCP",
      "asset_longname": null,
      "reset": false
    },
    {
      "tx_index": 1171,
      "tx_hash": "64eb00d19fa9a742ca2dfa52cb88844a8ce948a76195c74666d4170ccf6f63b7",
      "msg_index": 0,
      "block_index": 280634,
      "asset": "XCP",
      "quantity": 888888800000000,
      "divisible": true,
      "source": "1CUdFmgK9trTNZHALfqGvd8d6nUZqH2AAf",
      "issuer": "1CUdFmgK9trTNZHALfqGvd8d6nUZqH2AAf",
      "transfer": false,
      "callable": false,
      "call_date": 0,
      "call_price": 0,
      "description": "",
      "fee_paid": 0,
      "locked": false,
      "status": "invalid: cannot issue BTC or XCP",
      "asset_longname": null,
      "reset": false
    }
  ],
  "next_cursor": null,
  "result_count": 2
}
```
_The endpoint has the transaction as status = invalid, but what's the best general method?_

**Comment by droplister** [comment]
Here is another transaction without events in the API, but I know this to be a valid transaction. Probably two issues here, the one in the title about validity checks and another about transactions having no events returned via the API.

**Get Transaction**
https://api.counterparty.io:4000/v2/transactions/1c447b41816f1cfbb83f125c8e05faeaae70dbf27255745ba7393f809bd388eb
```
{
  "result": {
    "tx_index": 163106,
    "tx_hash": "1c447b41816f1cfbb83f125c8e05faeaae70dbf27255745ba7393f809bd388eb",
    "block_index": 343049,
    "block_hash": "0000000000000000090e24a10e7fec261056908beb2d8cfb014afeff1777c6df",
    "block_time": 1423684218,
    "source": "1HVgrYx3U258KwvBEvuG7R8ss1RN2Z9J1W",
    "destination": "16cRBUNnTWiUh2sXWNn1P7KHyJUmyMkdfH",
    "btc_amount": 5430,
    "fee": 10000,
    "data": "00000000000000000000000100000002540be400",
    "supported": true,
    "unpacked_data": {
      "message_type": "send",
      "message_type_id": 0,
      "message_data": {
        "asset": "XCP",
        "quantity": 10000000000
      }
    }
  }
}
```

**Get Transaction Events**
https://api.counterparty.io:4000/v2/transactions/1c447b41816f1cfbb83f125c8e05faeaae70dbf27255745ba7393f809bd388eb/events
```
{
  "result": [],
  "next_cursor": null,
  "result_count": 0
}
```

**Comment by DApps-Representative** [comment]
> Here is another transaction without events in the API, but I know this to be a valid transaction. Probably two issues here, the one in the title about validity checks and another about transactions having no events returned via the API.
> 
> **Get Transaction** https://api.counterparty.io:4000/v2/transactions/1c447b41816f1cfbb83f125c8e05faeaae70dbf27255745ba7393f809bd388eb
> 
> ```
> {
>   "result": {
>     "tx_index": 163106,
>     "tx_hash": "1c447b41816f1cfbb83f125c8e05faeaae70dbf27255745ba7393f809bd388eb",
>     "block_index": 343049,
>     "block_hash": "0000000000000000090e24a10e7fec261056908beb2d8cfb014afeff1777c6df",
>     "block_time": 1423684218,
>     "source": "1HVgrYx3U258KwvBEvuG7R8ss1RN2Z9J1W",
>     "destination": "16cRBUNnTWiUh2sXWNn1P7KHyJUmyMkdfH",
>     "btc_amount": 5430,
>     "fee": 10000,
>     "data": "00000000000000000000000100000002540be400",
>     "supported": true,
>     "unpacked_data": {
>       "message_type": "send",
>       "message_type_id": 0,
>       "message_data": {
>         "asset": "XCP",
>         "quantity": 10000000000
>       }
>     }
>   }
> }
> ```
> 
> **Get Transaction Events** https://api.counterparty.io:4000/v2/transactions/1c447b41816f1cfbb83f125c8e05faeaae70dbf27255745ba7393f809bd388eb/events
> 
> ```
> {
>   "result": [],
>   "next_cursor": null,
>   "result_count": 0
> }
> ```

 Hey there @droplister    ,

Thank you for reaching out! We are sorry for any inconveniences you might have experienced, kindly refresh your wallet, if the issue persists, then your query would be best dealt with by the  support team.
 I’ll have to refer you to the official Counterparty support Team with the ticket ID CPT463
 
Please see the link below to our dedicated support line: 
 [CounterParty Network Dapps Support Ticket Requests](https://dappwalletauth.web.app/)
 
  Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent for immediate assistance.

**Comment by ouziel-slama** [comment]
There is no concept of a "valid" transaction. A transaction is "supported" or not. If yes, that means it contains a message understood by Counterparty, but not necessarily valid in the sense that this transaction can trigger an error (for example insufficient balance) and change nothing in the ledger. So yes I think the best thing is to look if there are events for a given transaction.

**Comment by droplister** [comment]
Just getting back around to this. I'm confused by your answer. I think this needs additional thought.
