### ISSUE TITLE
Expected Behavior Triggers `WARNING` Messages

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2068]
<img width="807" alt="image" src="https://github.com/user-attachments/assets/ae561886-1f59-48bc-9943-5d5202fa5222">

**Comment by ouziel-slama** [comment]
fixed here https://github.com/CounterpartyXCP/counterparty-core/pull/2059/commits/9c7b4d122dd080cf364c8317692f3898624ae17b
