### ISSUE TITLE
Check Consensus Hashes Against Strategic Servers Before Release

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2075]
**Steps To Reproduce**
If you think you've found a bug, list the steps to reproduce the unexpected behavior:
1. ...

**Screenshots and Logfiles**
If applicable, upload screenshots and log files to help explain your problem. Please run everything with the `--verbose` flag whenever possible.

**Comment by ouziel-slama** [comment]
done here https://github.com/CounterpartyXCP/counterparty-core/pull/2087
