### ISSUE TITLE
RSFetcher freeze

### ISSUE THREAD

**Issue by ouziel-slama** [CounterpartyXCP/counterparty-core#2089]
rsfetcher cannot connect to bitcoind but the main problem is that it freezes my computer completely.. it seems to be the CPU and RAM which are overloaded.. I can only physically restart the computer.

<img width="1088" alt="Capture d’écran 2024-07-24 à 12 14 35" src="https://github.com/user-attachments/assets/dfdf7dd1-f443-4d88-9ede-67bb26ca00fb">

**Comment by adamkrellenstein** [comment]
I don't want to block the release on this, but it's definitely an important issue.

**Comment by pinnate-modo** [comment]
Anecdotally I am seeing this more often.

**Comment by warrenpuffett** [comment]
@ouziel-slama and I have confirmed this is not an issue with the rust fetcher.
