### ISSUE TITLE
Peg Python Version

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2097]
to 3.10 or whatever

**Comment by ouziel-slama** [comment]
3.10 and 3.11 are both well tested on github workflow. I  excluded 3.12 meantime there is a demand for it.
https://github.com/CounterpartyXCP/counterparty-core/pull/2244/commits/32d495016ef6a2a6db3b0914bc9f4a34f95ad8a9
