### ISSUE TITLE
Counterparty Node UUID Location

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2103]
It should be stored in `$XDG_CACHE_HOME`, not at `~/.counterparty_node_uuid`.

(Actually it should be in `$XDG_STATE_HOME`: see https://github.com/CounterpartyXCP/counterparty-core/issues/2102

And it's not on our GCP servers?

```
ouziel@dev-xcp-main-develop-v1-1-2hql ~ $ cat ~/.counterparty-node-uuid
cat: /home/ouziel/.counterparty-node-uuid: No such file or directory
ouziel@dev-xcp-main-develop-v1-1-2hql ~ $ cat /root/.counterparty-node-uuid
cat: /root/.counterparty-node-uuid: Permission denied
ouziel@dev-xcp-main-develop-v1-1-2hql ~ $ sudo cat /root/.counterparty-node-uuid
cat: /root/.counterparty-node-uuid: No such file or directory
```

**Comment by ouziel-slama** [comment]
fixed here https://github.com/CounterpartyXCP/counterparty-core/pull/2150/commits/c68ad453c791868e33808741e743196da7f7ef1c
