### ISSUE TITLE
SQLITE_LOG: recovered 514 frames from WAL file

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2113]
https://counterparty.sentry.io/issues/5657009533/?alert_rule_id=15343752&alert_type=issue&notification_uuid=8908b504-63a3-4d5d-83c9-c5d85206b052&project=4507062633365504&referrer=slack

**Comment by ouziel-slama** [comment]
fixed here https://github.com/CounterpartyXCP/counterparty-core/pull/2150

**Comment by adamkrellenstein** [comment]
fixed again here https://github.com/CounterpartyXCP/counterparty-core/pull/2521/commits/eb5727f3facfc447bb9ab14bcba81e33473db77d
