### ISSUE TITLE
No Traceback for Routine Errors

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2137]
<img width="1241" alt="image" src="https://github.com/user-attachments/assets/8fc58220-a0e2-4426-82d9-70289105455c">

**Comment by ouziel-slama** [comment]
done here https://github.com/CounterpartyXCP/counterparty-core/pull/2150/commits/1c3b27f55c7c82c04375dbef8788cb6a682d7b81
