### ISSUE TITLE
Tweak Block Logging in JSON Mode

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2138]
We should put the block height in a dedicated field.

<img width="1240" alt="Screenshot 2024-08-08 at 9 45 46 AM" src="https://github.com/user-attachments/assets/4c6ac71f-6733-4693-814d-a777173c0777">

**Comment by ouziel-slama** [comment]
done here https://github.com/CounterpartyXCP/counterparty-core/pull/2150/commits/a0d55c9d8615ec2d87d46aeb33d8133bf74849ba
