### ISSUE TITLE
Events API Super Slow

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2144]
<img width="746" alt="Screenshot 2024-08-08 at 10 41 57 PM" src="https://github.com/user-attachments/assets/40d571b9-40eb-4aa6-a5e2-2faf79536826">
<img width="554" alt="Screenshot 2024-08-08 at 10 42 05 PM" src="https://github.com/user-attachments/assets/c8e518d8-d31f-4b2e-a583-9893949a3228">

This is a regression from v10.3.0, and it reproducible locally.

**Comment by ouziel-slama** [comment]
fixed here https://github.com/CounterpartyXCP/counterparty-core/pull/2147
