### ISSUE TITLE
DB Recovery Should be `WARN`

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2145]
Right now we're reporting these messages as `ERROR`—they should be `WARN`:

`Database WAL file detected. To ensure no data corruption has occurred...`
`SQLITE_LOG: recovered 395 frames from WAL file /data/counterparty/counterparty.db-wal (283)`

**Comment by ouziel-slama** [comment]
done here https://github.com/CounterpartyXCP/counterparty-core/pull/2150
