### ISSUE TITLE
`DivisionByZero`

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2166]
[**Steps To Reproduce**
If you think you've found a bug, list the steps to reproduce the unexpected behavior:
1. ...

**Screenshots and Logfiles**
If applicable, upload screenshots and log files to help explain your problem. Please run everything with the `--verbose` flag whenever possible.
](https://counterparty.sentry.io/issues/5701164613/?notification_uuid=9a470ad5-b65f-4ee8-afb7-c4857a079208&project=4507062633365504&referrer=regression_activity-email)

**Comment by ouziel-slama** [comment]
fixed here https://github.com/CounterpartyXCP/counterparty-core/pull/2244/commits/3f77d315ec39112964bc14ff35cb3d5c2c149952
