### ISSUE TITLE
Incorrect dispenser price?

### ISSUE THREAD

**Issue by crypt0biwan** [CounterpartyXCP/counterparty-core#2172]
If you look at the dispensers here https://api.counterparty.io:4000/v2/assets/JEWELDRAGONS/dispensers
you'll notice the top one has `"satoshirate": 49900`

```json
{
      "tx_index": 2704914,
      "tx_hash": "78e698c36f7fe8dfbc91332b601e6612c96206ccfee059cec5a8146528edb089",
      "block_index": 832731,
      "source": "133UZ4ubcqb3x1u7rWWRUsaJbSfejt4wJN",
      "asset": "JEWELDRAGONS",
      "give_quantity": 1,
      "escrow_quantity": 1,
      "satoshirate": 49900,
      "status": 0,
      "give_remaining": 1,
      "oracle_address": "1BTCUSDupRmeaNferCFoxmF6bYV5cAR2X2",
      "last_status_tx_hash": null,
      "origin": "133UZ4ubcqb3x1u7rWWRUsaJbSfejt4wJN",
      "dispense_count": 0,
      "last_status_tx_source": null,
      "close_block_index": null,
      "confirmed": true
 }
```

However, when looking in Freewallet (and in xchain/tokenscan API) the dispenser price is different https://tokenscan.io/api/dispensers/JEWELDRAGONS

```json
{
      "asset": "JEWELDRAGONS",
      "asset_longname": "",
      "block_index": 832731,
      "escrow_quantity": "1",
      "fiat_price": "499.00",
      "fiat_unit": "USD",
      "give_quantity": "1",
      "give_remaining": "1",
      "oracle_address": "1BTCUSDupRmeaNferCFoxmF6bYV5cAR2X2",
      "oracle_price": "69128.00",
      "oracle_price_block_time": "1712709129",
      "oracle_price_last_updated": "838527",
      "satoshi_price": "0.00721850",
      "satoshirate": "0.00049900",
      "source": "133UZ4ubcqb3x1u7rWWRUsaJbSfejt4wJN",
      "status": "0",
      "timestamp": 1709320488,
      "tx_hash": "78e698c36f7fe8dfbc91332b601e6612c96206ccfee059cec5a8146528edb089",
      "tx_index": "2704914"
 }
```

It looks like freewallet / xchain/tokenscan uses the "satoshi_price" field, but no clue what that is compared to the satoshirate field :-)
is it a bug? is info missing? not sure how to classify this, but thought I'd create an issue for it :-)

**Comment by droplister** [comment]
This is an "oracle" dispenser. I also have trouble working with these. Append ?verbose=true to the query to get the oracle price.
https://api.counterparty.io:4000/v2/assets/JEWELDRAGONS/dispensers?verbose=true

They are targeting a fiat price and an oracle is broadcasting BTCUSD exchange rates so the price in sats fluctuates.

**Comment by crypt0biwan** [comment]
Thanks for elaborating @droplister 
I was able to get the correct price by adding "verbose"!
Feel free to close this issue @adamkrellenstein when it should be working like this! :-)
