### ISSUE TITLE
Add `quantity_by_price` in Fairminter

### ISSUE THREAD

**Issue by ouziel-slama** [CounterpartyXCP/counterparty-core#2178]

**Comment by adamkrellenstein** [comment]
This is a protocol change?

**Comment by adamkrellenstein** [comment]
*bump*

**Comment by ouziel-slama** [comment]
This is to fix the new protocol. Without this parameter the minimum price of a non-divisible asset is 1 XCP.

**Comment by ouziel-slama** [comment]
done here https://github.com/CounterpartyXCP/counterparty-core/pull/2203
