### ISSUE TITLE
API Watcher - Migration lock timeout. Breaking lock and retrying...

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2183]
https://counterparty.sentry.io/issues/5753336383/?project=4507062633365504&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=7d&stream_index=0

**Comment by ouziel-slama** [comment]
fixed here https://github.com/CounterpartyXCP/counterparty-core/pull/2244/commits/ce72f2b8cb42b772c7515f817c5f35b28b6fc07c
