### ISSUE TITLE
Uncaught `ValueError` in API

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2192]
https://counterparty.sentry.io/issues/5792159959/?alert_rule_id=15343752&alert_type=issue&notification_uuid=844d1a69-f3d9-4627-86a4-1d910e2c9840&project=4507062633365504&referrer=slack

**Comment by ouziel-slama** [comment]
fixed here https://github.com/CounterpartyXCP/counterparty-core/pull/2700/commits/4cfa2b29677192376d02cd3e947761214f8c08db
