### ISSUE TITLE
API Endpoint for Info on Unconfirmed TX

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2204]

**Comment by pinnate-modo** [comment]
Might be better suited to the marketplace.

**Comment by ouziel-slama** [comment]
Added a route `/v2/transactions/<tx_hash>/info` here https://github.com/CounterpartyXCP/counterparty-core/pull/2244
This route works if the tx is in the mempool of the queried node.
