### ISSUE TITLE
Refactor Transaction Composition

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2245]
* [x] Don't rely on AddrIndexRs
* [x] Allow user to pass in all necessary data via API.
* [x] Try Bitcoin Core if params are not included, assuming `source` is in wallet
* [x] Fall back to `electrs`

-------

* [x] Allow only returning data output(s).

**Comment by ouziel-slama** [comment]
done here https://github.com/CounterpartyXCP/counterparty-core/pull/2873
