### ISSUE TITLE
Unconfirmed Events

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2254]

**Comment by mattmarcello** [comment]
It is very common across most crypto API providers for endpoints that return objects that are confirmed and in the mempool in a single call, by passing a parameter.  While it may be difficult to achieve, I think it makes sense to expose this capability in the `/events` api.  Perhaps it shouldn't be done in core... but it's definitely the sort of capability we'd want from an "api as product" standpoint.

**Comment by adamkrellenstein** [comment]
We have this!
