### ISSUE TITLE
Non-JSON Werkzeug Logs

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2256]
https://console.cloud.google.com/logs/query;cursorTimestamp=2024-09-24T19:15:43.483424549Z;duration=PT5M;query=resource.type%3D%22gce_instance%22%0Aresource.labels.instance_id%3D%221107237035789212286%22%0Atimestamp%3D%222024-09-24T19:15:37.279113148Z%22%0AinsertId%3D%222jloseen1ijz%22?project=noted-extension-407918

**Comment by ouziel-slama** [comment]
hum.. weird, I can't reproduce locally..

**Comment by adamkrellenstein** [comment]
Maybe it doesn't matter? Were about to switch to a production web server... that'll replace werkzeug, no?

**Comment by ouziel-slama** [comment]
I don't know :) need to make some search about this!

**Comment by ouziel-slama** [comment]
yep I confirm, problem solved with Gunicorn: https://github.com/CounterpartyXCP/counterparty-core/blob/develop/counterparty-core/counterpartycore/lib/api/wsgi.py#L125
