### ISSUE TITLE
Unhandled Error: Object of type `bytes` is not JSON serializable

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2263]
https://counterparty.sentry.io/issues/5903366249/?alert_rule_id=15343752&alert_type=issue&notification_uuid=5415fc79-ae94-46a1-890e-1332d6f24512&project=4507062633365504&referrer=slack
<img width="1024" alt="image" src="https://github.com/user-attachments/assets/0a3e3573-e2fa-42fa-a51d-8f039ff580da">

**Comment by ouziel-slama** [comment]
fixed here https://github.com/CounterpartyXCP/counterparty-core/pull/2264/commits/759e8157b47274b64b15d3678be2d34e0aee5a8c
