### ISSUE TITLE
Update BTC Fee Calculation

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2268]
<img width="694" alt="Screenshot 2024-09-25 at 11 45 02 AM" src="https://github.com/user-attachments/assets/2732cf5d-8711-4cb3-81e9-bc561219d3c0">

**Comment by JavierCervilla** [comment]
Adding more info to this Issue, looks like when you are requesting for a tx that is using multisig encoding is not taking account the sigops penalization for multisig tx so for example i sent this tx with a fee_per_kb of 4500 and resulting efective fee (1.62 resulting) is lower than the expected (4.33 was expected) 

https://mempool.space/es/tx/ff2742ffeb5fa5abccb1b78537ed2ec0a5d8341d7c59f7d145cf5205477f8a7e

![image](https://github.com/user-attachments/assets/f29b7310-d976-4b38-81ef-19d06891887b)

**Comment by ouziel-slama** [comment]
done here https://github.com/CounterpartyXCP/counterparty-core/pull/2873
