### ISSUE TITLE
MPMA Issues: First TX Succeeds Second TX Fails

### ISSUE THREAD

**Issue by pinnate-modo** [CounterpartyXCP/counterparty-core#2270]
Getting reports that there is a regression in Core > v9.61.3:

![image](https://github.com/user-attachments/assets/08021f14-1be7-4917-984c-26e2e4dbeaec)
![image](https://github.com/user-attachments/assets/1faff782-4a5f-4212-ae98-c8630718eb9d)

**Comment by ouziel-slama** [comment]
https://www.blockchain.com/explorer/transactions/btc/3f9ebd03e4a39e78d4e85fa9c45d6641e617fd973aabc183341c39284cf50ced
blockchain.comblockchain.com
[Transaction: 3f9ebd03e4a39e78d4e85fa9c45d6641e617fd973aabc183341c39284cf50ced | Blockchain.com](https://www.blockchain.com/explorer/transactions/btc/3f9ebd03e4a39e78d4e85fa9c45d6641e617fd973aabc183341c39284cf50ced)
The easiest and most trusted transaction search engine and block explorer.
[21 h 16](https://unspendablelabs.slack.com/archives/C07839GN4UV/p1727378219705059?thread_ts=1727360555.299129&cid=C07839GN4UV)
and here's the address https://www.blockchain.com/explorer/addresses/btc/35YFG178PnpTGS8Hd7fzg8iwKRcFqWM9mS
blockchain.comblockchain.com
[Address: 35YFG178PnpTGS8Hd7fzg8iwKRcFqWM9mS](https://www.blockchain.com/explorer/addresses/btc/35YFG178PnpTGS8Hd7fzg8iwKRcFqWM9mS)
The most popular and trusted block explorer and crypto transaction search engine.

**Comment by adamkrellenstein** [comment]
@ouziel-slama I'm not sure I understand. The transactions go through without a problem?

**Comment by ouziel-slama** [comment]
yes I don't understand either! the description of the bug is not coherent:
1. There is a screenshot that indicates that the second transaction is invalid
2. the second transaction is supposed to cause loss of funds
How can an invalid transaction cause loss of funds? I'm not sure I understand but it seems to me to be a bug in the wallet that displays an error message and broadcasts the transaction anyway (?).

**Comment by ouziel-slama** [comment]
ah ok I just understood that it is a p2sh transaction!

**Comment by adamkrellenstein** [comment]
see https://github.com/CounterpartyXCP/counterparty-core/issues/2277
