### ISSUE TITLE
ThreadingViolation Error

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2273]
<img width="1010" alt="image" src="https://github.com/user-attachments/assets/45b531a3-8bcf-49e3-b882-29d220e2cb25">

https://counterparty.sentry.io/issues/5918295738/?alert_rule_id=15343752&alert_type=issue&notification_uuid=5e6b80d9-a78f-4029-b779-76d25fcb7bb1&project=4507062633365504&referrer=slack

Possibly related to #1976

**Comment by ouziel-slama** [comment]
I can neither explain nor reproduce. I have set up a workaround here: https://github.com/CounterpartyXCP/counterparty-core/pull/2299/commits/0894f6160364a3a023b31736ed9eda6b58621057
