### ISSUE TITLE
Disable P2SH

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2277]
~Right now v1 forces P2SH encoding, at least for MPMA transactions. Both v1 and v2 should default to multi-sig, since~ P2SH is unreliable (https://github.com/CounterpartyXCP/counterparty-core/issues/2270 https://github.com/CounterpartyXCP/counterparty-core/issues/1383). (It's also probably more expensive in many cases, because it uses multiple transactions.) All of this is a stopgap, given we're gonna be doing all encoding using witness data in the near future (cf. https://github.com/CounterpartyXCP/counterparty-core/issues/1375).

**Comment by adamkrellenstein** [comment]
apparently this actually has something to do with `memo`, `memo_in_hex`, and the version of bitcoin core / python-bitcoinlib being used...

**Comment by adamkrellenstein** [comment]
So it turns out that P2SH no longer works with recent versions of Bitcoin Core.

In addition, there were two other bugs in the P2SH implementation:

1. https://github.com/CounterpartyXCP/counterparty-core/issues/2287
2. https://github.com/CounterpartyXCP/counterparty-core/issues/2288

Plus we also ran into: https://github.com/CounterpartyXCP/counterparty-core/issues/2286

**Comment by ouziel-slama** [comment]
done here https://github.com/CounterpartyXCP/counterparty-core/pull/2290
