### ISSUE TITLE
Missing `Type` Field in Issuance Events

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2278]
<img width="1122" alt="Screenshot 2024-09-30 at 12 34 57 PM" src="https://github.com/user-attachments/assets/31e613e5-2898-4a51-98dd-74fa3418c3c7">

**Comment by ouziel-slama** [comment]
fixed here https://github.com/CounterpartyXCP/counterparty-core/pull/2292/commits/b4c4060b6752f0da696c190a3e8854729824289b
