### ISSUE TITLE
`FileNotFoundError`

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2296]
<img width="996" alt="image" src="https://github.com/user-attachments/assets/5b2e51ff-0764-4ca6-bb7b-ca251007af16">

https://counterparty.sentry.io/issues/5941816292/?alert_rule_id=15343752&alert_type=issue&notification_uuid=ea5d3101-da1c-4c6e-8a49-cae6f84d9e28&project=4507062633365504&referrer=slack

**Comment by ouziel-slama** [comment]
it's because the file is not included in the package.
Fixed here https://github.com/CounterpartyXCP/counterparty-core/pull/2292/commits/bb133b266735d3898bd85c75d6772491f325ce46
