### ISSUE TITLE
`BadRequest` Error

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2302]
<img width="1018" alt="image" src="https://github.com/user-attachments/assets/780824ba-9366-44a1-b9df-5828d6df35ff">

**Comment by ouziel-slama** [comment]
fixed here https://github.com/CounterpartyXCP/counterparty-core/pull/2299/commits/7c351c940b50b6d6d1b9d90f97cb79bbb2b5cca7
