### ISSUE TITLE
`AttributeError` on `get_transactions`

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2304]
![telegram-cloud-photo-size-4-5768181649245320595-y](https://github.com/user-attachments/assets/ea56911a-fe8f-4c33-8b24-e34f607ee615)
![telegram-cloud-photo-size-4-5765857431988057752-y](https://github.com/user-attachments/assets/536fb654-a78a-4a5e-b14b-4db4faa88758)

**Comment by adamkrellenstein** [comment]
Also, this isn't showing up on Sentry... I guess because it's being caught? But it still should.

**Comment by ouziel-slama** [comment]
fixed here https://github.com/CounterpartyXCP/counterparty-core/pull/2299/commits/fc7701b36099483ae45c4b6473a5c69efcb580ca

> Also, this isn't showing up on Sentry... I guess because it's being caught? But it still should.

everythins is handled by `jsonrpc.JSONRPCResponseManager.handle`
