### ISSUE TITLE
`last_block` *sometimes* returning `null`

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2312]
![telegram-cloud-photo-size-4-5770740990192235744-y](https://github.com/user-attachments/assets/f80513f4-5056-4e44-8eea-7c40a4a37e82)

**Comment by adamkrellenstein** [comment]
<img width="698" alt="Screenshot 2024-10-05 at 3 19 06 PM" src="https://github.com/user-attachments/assets/d03e98f3-1d12-47ef-8eb6-5f3060ca7521">

**Comment by adamkrellenstein** [comment]
<img width="717" alt="image" src="https://github.com/user-attachments/assets/118db899-7f4b-4154-904b-64b5c7e3697b">

**Comment by ouziel-slama** [comment]
fixed here https://github.com/CounterpartyXCP/counterparty-core/pull/2318/commits/35228157715bda6679f5de22cb2e970876069d85
