### ISSUE TITLE
Skip Cache Flag for API (?)

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2314]

**Comment by ouziel-slama** [comment]
It sounds a little weird to me :-) Generally, it's the responsibility of the server to decide when to use the cache (for DDoS attacks, for example). Also, if the cache is well-implemented on the server side, you should never see a difference as a client !

**Comment by adamkrellenstein** [comment]
Yeah this is just for debugging purposes... Not sure what the best soln is though.

**Comment by adamkrellenstein** [comment]
The cache is global, so it's weird for one user to be able to bypass it. (Would the cache be updated in that case?)

**Comment by adamkrellenstein** [comment]
See https://github.com/CounterpartyXCP/counterparty-core/issues/2783
