### ISSUE TITLE
Testnet Crashed due to Invalid Script

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2316]
![telegram-cloud-photo-size-4-5775233440084506206-y](https://github.com/user-attachments/assets/486b8d1d-818d-4b99-8f92-7807bb5dc9ac)

**Comment by adamkrellenstein** [comment]
Partially addressed by https://github.com/CounterpartyXCP/counterparty-core/pull/2315/files

**Comment by ouziel-slama** [comment]
completed here https://github.com/CounterpartyXCP/counterparty-core/pull/2318/commits/3810112e81782002300f83022631e19c9c5905ab
