### ISSUE TITLE
`AttributeError`

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2329]
https://counterparty.sentry.io/issues/5980265368/?alert_rule_id=15343752&alert_type=issue&notification_uuid=74ef5c45-5063-4e72-8623-ca6b552e97b3&project=4507062633365504&referrer=slack
<img width="1022" alt="image" src="https://github.com/user-attachments/assets/2b0a5597-1861-41ed-8e05-1b18f8bb9a8f">

**Comment by ouziel-slama** [comment]
fixed here https://github.com/CounterpartyXCP/counterparty-core/pull/2328/commits/136fde216294b4aa6595b8ad77f7997e046226eb
