### ISSUE TITLE
Invalid Address Error

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2331]
<img width="1008" alt="image" src="https://github.com/user-attachments/assets/d16bf6db-43c2-437f-90f8-53177d6766cf">

https://counterparty.sentry.io/issues/5982027796/?alert_rule_id=15343752&alert_type=issue&notification_uuid=19de92d2-d37a-45ef-a9e0-8530cae89cb9&project=4507062633365504&referrer=slack

**Comment by ouziel-slama** [comment]
fixed here https://github.com/CounterpartyXCP/counterparty-core/pull/2328/commits/1f7a38b084be883aa1b11983cc82d56bfe7f77cd
