### ISSUE TITLE
Address Credits/Debits Showing Unconfirmed Without Passing show_unconfirmed

### ISSUE THREAD

**Issue by droplister** [CounterpartyXCP/counterparty-core#2332]
I'm finding that I'm getting unconfirmed credits and debits from the API despite not passing show_unconfirmed.

**Comment by adamkrellenstein** [comment]
@droplister would you mind providing an example API call + response?

**Comment by ouziel-slama** [comment]
fixed here https://github.com/CounterpartyXCP/counterparty-core/pull/2336
