### ISSUE TITLE
Testnet Down (Again)

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2335]
![image](https://github.com/user-attachments/assets/cd698c89-9bd2-4f8b-8a18-2ce82d66041d)
![image](https://github.com/user-attachments/assets/62f89d72-d19d-4b53-a667-c01ebe97ebb1)

**Comment by ouziel-slama** [comment]
This should be fixed with https://github.com/CounterpartyXCP/counterparty-core/pull/2337 but let's monitor testnet 24/48h on the dev server before closing.

**Comment by ouziel-slama** [comment]
all good!

**Comment by adamkrellenstein** [comment]
Ah nope, it's down again!

**Comment by adamkrellenstein** [comment]
Fixed: https://github.com/CounterpartyXCP/counterparty-core/pull/2349
