### ISSUE TITLE
getMempoolEventsByAddresses inconsistencies 

### ISSUE THREAD

**Issue by mattmarcello** [CounterpartyXCP/counterparty-core#2370]
the responses to `/addresses/mempool?verbose=true` and likely `/addresses/mempool` are inconsistent. 

observed behavior:

| Request       | Query                            | Response                                    |
|---------------|----------------------------------|---------------------------------------------|
| Request 1     | Query `mempoolEventsByAddresses` | `[mempoolEventA, mempoolEventB, mempoolEventC]` |
| Request 2     | Query `mempoolEventsByAddresses` | `[]`                                        |
| Request 3     | Query `mempoolEventsByAddresses` | `[mempoolEventA, mempoolEventB, mempoolEventC]` |

**Comment by ouziel-slama** [comment]
should by fixed by LB setting. @mattmarcello please re-open if happen again.
