### ISSUE TITLE
By Default, Don't Spend UTXOs with Assets Attached to Them

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2375]
Since nodes are using Counterparty Core to do UTXO selection for composing new transactions, we should do what we can to avoid accidentally spending UTXOs with assets attached to them. We can require a flag in the API to bypass this check.

Also we should create an endpoint which lists all UTXOs of an address that have assets attached to them.

**Comment by DerpHerpenstein** [comment]
would seem like this should be on milestone https://github.com/CounterpartyXCP/counterparty-core/milestone/41 , perhaps with #2610

By default, cp nodes creating txs that accidentally send assets should be considered a bug?

**Comment by tepixelabs** [comment]
It would be great if you could fix what derp mentioned! I wouldn't want to send my stamps inside other stamps! thhks team!

**Comment by jdogresorg** [comment]
Glad to see you implemented yet another one of my suggestions to protect users from accidentally spending UTXOs with assets attached to them :P 

![image](https://github.com/user-attachments/assets/cefb42b4-7b94-4507-9fc7-1d6fa49cb3f7)
