### ISSUE TITLE
Telemetry Oneshot Timeout

### ISSUE THREAD

**Issue by droplister** [CounterpartyXCP/counterparty-core#2377]
Getting this with 10.4.5. Seeing an increase in 504s, but not a complete halt/crash.
```
Error in telemetry one shot: (<urllib3.connection.HTTPConnection object at 0x72cedaaf83d0>, 'Connection to telemetry.counterparty.io timed out. (connect timeout=10.0)')
```

**Comment by jdogresorg** [comment]
Would like to request the flag to disable telemetry as discussed in this issue:

https://github.com/CounterpartyXCP/counterparty-core/issues/1522

`Obviously all of this data is 100% anonymous and there'll be a flag to disable it entirely.`

**Comment by adamkrellenstein** [comment]
The flag is this one:

```
> counterparty-server --help | grep telemetry
                           [--no-mempool] [--no-telemetry]
  --no-telemetry        Do not send anonymous node telemetry data to telemetry
> 
```

**Comment by adamkrellenstein** [comment]
This is probably a problem with the telemetry server primarily, but we should make sure that the timeouts are reasonable, and that there's retry logic, etc.

**Comment by adamkrellenstein** [comment]
okay issue was that when we switched telemetry to be behind a load balancer we didn't open 8086
