### ISSUE TITLE
`NoneType` object is not subscriptable

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2393]
https://counterparty.sentry.io/issues/5999196200/?referrer=slack&notification_uuid=27235448-3db6-4a0a-96cf-b2ff302f83a9&alert_rule_id=15343752&alert_type=issue
<img width="1066" alt="image" src="https://github.com/user-attachments/assets/43b6d0bd-5d9b-44a1-9538-da12139fcc3c">

**Comment by droplister** [comment]
This took down my nodes.

**Comment by droplister** [comment]
```
{
"result": {
"server_ready": false,
"network": "mainnet",
"version": "10.4.6",
"backend_height": 866084,
"counterparty_height": 866077,
"documentation": "https://counterpartycore.docs.apiary.io/",
"routes": "http://api.counterparty.info/v2/routes",
"blueprint": "https://raw.githubusercontent.com/CounterpartyXCP/counterparty-core/refs/heads/master/apiary.apib"
}
}
```

**Comment by ouziel-slama** [comment]
fixed here https://github.com/CounterpartyXCP/counterparty-core/pull/2401
