### ISSUE TITLE
API Rate Limit

### ISSUE THREAD

**Issue by droplister** [CounterpartyXCP/counterparty-core#2394]
Is there an implicit rate limit or a setting I can manage explicitly?

I do a lot of API calls for indexing and that usually looks like a loop paginating with offset/limit through all orders, for example.

It's common that what will happen is everything is good and working and then I'll get 403 errors for a while and then back to good, so it looks like rate limiting to me but I was wondering if there's a header or a setting that I can handle those rates or not?

**Comment by droplister** [comment]
I also get "stream timeout" very often after these updates.

**Comment by adamkrellenstein** [comment]
@droplister can you be more specific? what's the issue you're having? What is reporting a rate limit?

**Comment by droplister** [comment]
Nothing is reporting a rate limit, I often get 403 errors on the API endpoints, not one specific endpoint which makes me think there could be a rate limit that I'm not aware of.

**Comment by adamkrellenstein** [comment]
yeah no it's not a rate limit. if you could upload some logs + screenshots, that'd be helpful so we can see what's causing the errors.

**Comment by droplister** [comment]
You know what, it's probably with my cloud setup. I have two nodes load balanced in google cloud and I think they are applying a default policy. Nevermind!
