### ISSUE TITLE
Fairmints Event Status on Rollbacks

### ISSUE THREAD

**Issue by droplister** [CounterpartyXCP/counterparty-core#2399]
I rolled back to 865,690 (which I saw mentioned in the release docs) to see if it would help me and I noticed this error while it was parsing. Blocks continued to be parsed after this. 

![{481D4242-E0E3-4F50-90E2-035533494FDF}](https://github.com/user-attachments/assets/dacde4d1-bef5-461f-9652-373e8bed886a)

https://github.com/CounterpartyXCP/counterparty-core/blob/8890f8a0250b229c8c09729509972817ac9c4e32/counterparty-core/counterpartycore/lib/api/api_watcher.py#L630-L644

I think you could do something like...
  
 ```
        if event.get("event") != "NEW_FAIRMINT":
        return
    if event.get("status") != "valid":
        return
 ```

**Comment by ouziel-slama** [comment]
fixed here https://github.com/CounterpartyXCP/counterparty-core/pull/2401
