### ISSUE TITLE
Counterparty Behind Bitcoin

### ISSUE THREAD

**Issue by droplister** [CounterpartyXCP/counterparty-core#2412]
What's the recommended strategy for something like this, I encountered in 10.4.5 and it persisted in 10.4.8, should I rollback and see if it resolves? I've run into this a few times this year and I'm never really sure what to do about it.

The API shows:
```
{
"result": {
"server_ready": false,
"network": "mainnet",
"version": "10.4.8",
"backend_height": 866102,
"counterparty_height": 866077,
}
}
```

Command line:
```
[INFO] - Catch up complete.
```

**Comment by droplister** [comment]
Interestingly the counterparty_height is going down when I refresh this api endpoint...
```
{
"result": {
"server_ready": false,
"network": "mainnet",
"version": "10.4.8",
"backend_height": 866102,
"counterparty_height": 866074,
}
}
```

Maybe there's some processing happened that's not reflected to me in the journalctl which looks just like it's watching the mempool all caught up.

**Comment by droplister** [comment]
Two nodes that I've upgraded are like this, their height it going down slowly one block at a time and the logs on the command line just look normal. Now it's down to 866,070.

![{DD172B9B-D4A8-4669-B970-DAA5FD11134A}](https://github.com/user-attachments/assets/4d562fba-d3e1-4fef-baa0-5e49747b6b6e)

**Comment by droplister** [comment]
Nothing in the logs, just seeing the height slowly roll back now at 866,064.. 866,604. 

![{48866CB8-2352-4D7E-BD32-86F89A62A5CD}](https://github.com/user-attachments/assets/daac6724-89a3-456e-b9b8-d6fce7985021)

I had rolled back to 865690 prior to updating, maybe it's a weird interaction of the two.

**Comment by adamkrellenstein** [comment]
yeah this is weird. will investigate

**Comment by droplister** [comment]
It seems to have stopped at 866,050, but I can't be sure until more time passes.

**Comment by droplister** [comment]
Rolled backed, it caught back up, at least in my command line logs, but still showing 866,050. Could be some sort of caching or the ledger_hash isnt being populated on blocks so the query isnt selecting the latest or i dont know what. I may fully reparse.

**Comment by droplister** [comment]
I'm thinking it's to do with this relatively new change that adds a ledger_hash condition to the selection query:
https://github.com/CounterpartyXCP/counterparty-core/blob/34d4436c67e360fb73cf7479bc80b0e6d4b09692/counterparty-core/counterpartycore/lib/ledger.py#L1133-L1144

**Comment by droplister** [comment]
So bizarre, I went to dinner and it was resolved.
