### ISSUE TITLE
New CORS Settings

### ISSUE THREAD

**Issue by droplister** [CounterpartyXCP/counterparty-core#2419]
Is there info on how the new release changes things with cors. I'm wondering if I need to change my settings.

I'm making a low-rent mint tool here: https://www.xcp.io/mint

And I'm trying to have the client call /compose and getting...
```
Access to XMLHttpRequest at 'https://api.counterparty.info/v2/addresses/19QWXpMXeLkoEKEJv2xo9rn8wkPCyxACSX/compose/fairmint' from origin 'https://www.xcp.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

**Comment by droplister** [comment]
Stupid - I was doing a post instead of a get. ugh!

**Comment by droplister** [comment]
Nope that wasnt it.

**Comment by JavierCervilla** [comment]
im geting cors error on some routes like v2

**Comment by adamkrellenstein** [comment]
@JavierCervilla we need more information to debug this. What exact requests? Can you replicate it with cURL / HTTPie? As far as we know, all of the headers are being sent.

**Comment by adamkrellenstein** [comment]
Okay when I made an `OPTIONS `request I didn't get the headers:


```
adam@Adams-MacBook-Pro ~ > http OPTIONS https://api.counterparty.io:4000/v2
HTTP/1.1 200 OK
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Content-Length: 0
content-type: text/html; charset=utf-8
date: Wed, 30 Oct 2024 20:23:38 GMT
server: gunicorn
via: 1.1 google
```

and I'm now manually injecting them at the LB-level:


```
http OPTIONS https://api.counterparty.io:4000/v2
HTTP/1.1 200 OK
Alt-Svc: clear
Content-Length: 0
access-control-allow-headers: *
access-control-allow-methods: *
access-control-allow-origin: *
content-type: text/html; charset=utf-8
date: Wed, 30 Oct 2024 20:34:14 GMT
server: gunicorn
via: 1.1 google
```

**Comment by adamkrellenstein** [comment]
I see this behavior is tested here! so something is wonky.

https://github.com/CounterpartyXCP/counterparty-core/commit/9cbfd69832c0ac5093a1e6ff87ba4dfa311a7c1d

**Comment by adamkrellenstein** [comment]
verified the headers are missing on localhost too, so they're not getting stripped
