### ISSUE TITLE
API Reliability Issues

### ISSUE THREAD

**Issue by droplister** [CounterpartyXCP/counterparty-core#2420]
I am running two cloud hosted nodes behind a load balancer with Google Cloud which I think the team is doing as well based on the errors I get on api.counterparty.io. I took this video quickly to show what I'm encountering a lot.

The nodes will hang on even basic pages, like the /v2 homepage. And eventually it will load, stays cached for a short amount of time and then it goes back into this long-load state. And it happens often enough and consistent enough that there are timeouts or the health checks fail and are not re-tried for a minute so it's not stable enough to run the explorer frontend I'm using it on.

Let me know if you have any ideas or figure it out because I see the counterparty.io exhibiting similar behavior.

**Comment by droplister** [comment]
https://www.awesomescreenshot.com/video/32677414?key=1313cac3b0691a880314d3812480dbb5

**Comment by adamkrellenstein** [comment]
Yes, this is a known problem. We're having node stability issues. See https://github.com/CounterpartyXCP/counterparty-core/issues/2415

**Comment by droplister** [comment]
I'd be surprised if 2415 was the source of the API issues. Seems like some sort of middleware issue or maybe these new WSGI's that have been swapped in recently.

**Comment by adamkrellenstein** [comment]
Yeah it's a bunch of factors. See #2429 and just AddrIndexRs being overloaded.
