### ISSUE TITLE
Non-hexadecimal digit found

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2435]
https://counterparty.sentry.io/issues/6001894376/?alert_rule_id=15343752&alert_type=issue&notification_uuid=032a3f98-259d-4ab2-ac88-d113ce80f0f0&project=4507062633365504&referrer=slack
<img width="1056" alt="image" src="https://github.com/user-attachments/assets/43bb9c8b-59a7-4621-9a3e-33f86cbe7731">

**Comment by ouziel-slama** [comment]
fixed here https://github.com/CounterpartyXCP/counterparty-core/pull/2558/commits/ee6e25072293dfa49c22fb6540e21f27f0d5e403
