### ISSUE TITLE
XCP dispense through FreeWallet.io partially done : BTC spent but not received my XCP

### ISSUE THREAD

**Issue by japrog** [CounterpartyXCP/counterparty-core#2451]
**Steps To Reproduce**
If you think you've found a bug, list the steps to reproduce the unexpected behavior:
1. Dispense XCP from dispenser through FreeWallet.io desktop during very high traffic

**Screenshots and Logfiles**
Please find details of which would be the transaction links below explaining it is showing up on xcp dot dev but not tokenscan or horizon explorer:
- Tx is showing up from 2 links below :
https://www.xcp.dev/tx/f27f7cd4b7fa5637cd59059a99bd5fa1bef7da277df6437374983b5035221905
https://blockstream.info/tx/f27f7cd4b7fa5637cd59059a99bd5fa1bef7da277df6437374983b5035221905
- Tx is NOT showing up from the 2 links below :
https://tokenscan.io/tx/f27f7cd4b7fa5637cd59059a99bd5fa1bef7da277df6437374983b5035221905
https://explorer.unspendablelabs.com/tx/f27f7cd4b7fa5637cd59059a99bd5fa1bef7da277df6437374983b5035221905

To conclude :
- my BTC has been spent but i might not receive XCP along FreeWallet.io desktop neither on https://tokenscan.io/ (i don't see my bought XCP)
- but on https://www.xcp.dev/, all seems to be fine (i see my bought XCP)

Thanks for your help.

**Comment by adamkrellenstein** [comment]
Thanks for reporting the issue, but the network is experiencing an unusually high load right now. This is very likely due to that. (But it's a matter for Tokenscan.io, in any case.)
