### ISSUE TITLE
Missing Data from Blocks API

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2452]
<img width="668" alt="Screenshot 2024-10-18 at 4 25 27 PM" src="https://github.com/user-attachments/assets/742cf61a-5a01-488b-950a-09664baf9ef0">

**Comment by ouziel-slama** [comment]
fixed here https://github.com/CounterpartyXCP/counterparty-core/pull/2450/commits/9ac0eb8c462740e9e731a79a0c28f7fc2fcf4f0e
