### ISSUE TITLE
Custom Log Levels

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2455]
* [Ledger] Blocks
* [Ledger] Transactions
* [Ledger] Events
* [Ledger] Mempool
* [API] Requests
* [API] Responses
* [API] Events
* [API] Mempool

**Comment by ouziel-slama** [comment]
there is already a `--quiet` flag. It set log level to ERROR.

**Comment by adamkrellenstein** [comment]
Custom levels for Transactions and API stuff

**Comment by adamkrellenstein** [comment]
Be able to hide mempool transaction parsing too

**Comment by adamkrellenstein** [comment]
Merged with https://github.com/CounterpartyXCP/counterparty-core/issues/2509
