### ISSUE TITLE
Server Stopped Keeping Up

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2478]
I haven't had a chance to look into this yet.

https://storage.cloud.google.com/counterparty-debug/163-logs.tar.gz

**Comment by ouziel-slama** [comment]
```
{"filename": "log.py", "funcName": "trace", "levelname": "TRACE", "lineno": 32, "module": "log", "name": "counterparty", "pathname": "/home/adam_krellenstein/venv/lib/python3.11/site-packages/counterpartycore/lib/log.py", "process": 92108, "processName": "Process-1", "stack_info": null, "thread": 140313047738048, "threadName": "Thread-2", "block_index": null, "message": "Parent process is dead. Exiting...", "time": "2024-10-19T14:25:09.277891+00:00"}
```

**Comment by ouziel-slama** [comment]
probably fixed with https://github.com/CounterpartyXCP/counterparty-core/issues/2478

**Comment by adamkrellenstein** [comment]
lol that's a link to this issue

**Comment by adamkrellenstein** [comment]
it just happened here fwiw: https://storage.cloud.google.com/counterparty-debug/stopping-api-watcher.tar.gz

**Comment by ouziel-slama** [comment]
oops sorry I meant here https://github.com/CounterpartyXCP/counterparty-core/commit/e59dfce4b79ce14027bf35076c63e3d8658aac89
but I reverted this commit because it was causing really bizarre bugs.

**Comment by adamkrellenstein** [comment]
@ouziel-slama can we re-enable it when gunicorn is not being used? then we can limit the process stuff to gunicorn :)
