### ISSUE TITLE
Bitcoin Core ZMQ issue with default config using docker compose

### ISSUE THREAD

**Issue by JavierCervilla** [CounterpartyXCP/counterparty-core#2486]
```
counterparty-core-1  | 2024-10-19T21:26:41.357+00:00 - [   ERROR] - Bitcoin Core ZeroMQ notifications are incorrectly configured. The following notification must be enabled: ['pubrawtx', 'pubhashtx', 'pubsequence', 'pubrawblock']
```

**Comment by JavierCervilla** [comment]
i think i solved, is not exposing the 8333 port by default in the docker compose

**Comment by adamkrellenstein** [comment]
@JavierCervilla have you tried spinning up an entirely separate docker compose instance?

**Comment by JavierCervilla** [comment]
yes sir i spin another one and same issue

**Comment by adamkrellenstein** [comment]
which exact instructions are you following? can you share your config files? logs?

**Comment by JavierCervilla** [comment]
will get all that info and share it here when fully sync in this rc.1 version and check if tthe problem is still there, tank you :)
