### ISSUE TITLE
Initializing Asset Cache Multiple Times?

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2490]
...all within a very short period
<img width="757" alt="Screenshot 2024-10-19 at 11 13 51 PM" src="https://github.com/user-attachments/assets/319d74b8-e25e-4aff-ab58-5991ade1270e">
<img width="706" alt="Screenshot 2024-10-19 at 11 14 06 PM" src="https://github.com/user-attachments/assets/2de22f5e-2bfc-45ec-b524-c5ece62f8c1b">
<img width="636" alt="Screenshot 2024-10-19 at 11 14 02 PM" src="https://github.com/user-attachments/assets/d785c0c6-15f5-472e-a22a-915c47749960">

**Comment by ouziel-slama** [comment]
@adamkrellenstein it's with Gunicorn right ? if yes this cache is also used by the API, one by process.
