### ISSUE TITLE
endpoint estimatexcpfee missing

### ISSUE THREAD

**Issue by JavierCervilla** [CounterpartyXCP/counterparty-core#2508]
Looks like the endpoint `/v2/addresses/<address>/send/compose/estimatexcpfees` is missing in the api and apiary
showed here: https://gist.github.com/adamkrellenstein/7c7cab257cee162233fc2ba6682eb8da

**Comment by ouziel-slama** [comment]
fixed here https://github.com/CounterpartyXCP/counterparty-core/pull/2558/commits/05cb8ad253760090de7eb0614d1a4dd353853d31
