### ISSUE TITLE
Prefix Every Log Message with Process + Thread Indicator

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2509]
Custom log levels for different processes / threads. Be able to pick and choose exactly what you do / don't want to see on the CLI.

(We need to include the Rust prefetcher logs in `STDERR`.}

* [Ledger] Blocks
* [Ledger] Transactions
* [Ledger] Events
* [Ledger] Mempool
* [API] Requests
* [API] Responses
* [API] Events
* [API] Mempool
* [Prefetcher] Prefetcher

**Comment by ouziel-slama** [comment]
done here https://github.com/CounterpartyXCP/counterparty-core/pull/2799/files
