### ISSUE TITLE
API DB -> StateDB

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2517]
Right now the "API DB" is a effectively a record of the current *state* of the Counterparty network that complements the log-structured "LedgerDB". This is particularly useful for serving API requests which might, e.g., query the extant quantity of an asset—for that query, we don't want to have to sum all of the old `issuances`, but rather simply look up the latest value (which is not stored in the LedgerDB). However, we also need the ability to roll the "API DB" back.

Right now the "API DB" is *also* log-structured for rollbacks, but this is unnecessary because we have all of that information in the Ledger DB. When we roll back, we delete all of the recent rows in the extant log-structured tables (that include only `INSERT`s) and we undo each `UPDATE` in stateful tables. Instead, we could simply build any arbitrary historical state of this datastore by making some (slow) queries of the LedgerDB, and then rolling forward the normal way when following the blockchain. This would allow the StateDB not to have to store any information that is not up to date. It would also dramatically increase the speed at which rollbacks occur because we'd be making a few heavy queries rather than a bajillion sequential `UPDATES`.

The API Server process would read from the StateDB more or less the same way that it reads from the current "API DB", but the StateDB would be much smaller and lighter.

Note: if the slow queries of the LedgerDB don't work for some reason, e.g. they're too slow, we may have to instead store historical snapshots of the StateDB from which we roll forward.)

**Comment by ouziel-slama** [comment]
> Rename API DB -> StateDB (that it's used for the API is incidental).

API DB was designed specifically for the API and is certainly not incidental.
IMO statedb is a synonym for ledgerdb and API db is the good name for this database.

**Comment by adamkrellenstein** [comment]
So an example of something which is more "API-like" than "State"-like would be storing prices as floats so we could serve them to the API (instead of just `give_quantity` and `get_quantity`).

**Comment by adamkrellenstein** [comment]
https://github.com/CounterpartyXCP/counterparty-core/pull/2714/files
