### ISSUE TITLE
Add a new API call to get non-fairmint issuance

### ISSUE THREAD

**Issue by ffmad** [CounterpartyXCP/counterparty-core#2520]
I encountered the problem yesterday, but when trying to get the issuance of a tokens with fairmint, I'm overloaded with fairmints, while I just want to get the original issuance calls.

Can we add this?

**Comment by ouziel-slama** [comment]
done here https://github.com/CounterpartyXCP/counterparty-core/pull/2558/commits/339bfb4844c7da358fdd2945213c366028fc4712
in the next version you could use `asset_events=creation,reissuance` for example.
