### ISSUE TITLE
Data Dir

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2524]
Right now we're just naming the API DB based on `--database-file=<foo.db>` => `foo.api.db`. Fetcherdb doesn't change. This is inconsistent.

We should replace `--database-file` with `--data-dir` and namespace all data in directories. (and always call the db files the same thing)

**Comment by ouziel-slama** [comment]
done here https://github.com/CounterpartyXCP/counterparty-core/pull/2525/commits/0663dea371d142a26810c25217931f91ec2545d1
