### ISSUE TITLE
API Route for (address and balance) and (balance) does not shows correct data when there is utxo attached in tha address

### ISSUE THREAD

**Issue by JavierCervilla** [CounterpartyXCP/counterparty-core#2538]
this address holds 295 units of the asset from that 295 units there is one attached to utxo, api call just shows that unit attached to utxo:

https://api.counterparty.io:4000/v2/addresses/bc1qwfmtwelj00pghxhg0nsu0jqx0f76d5nm0axxvt/balances/A6524912715479370914
```
{
  "result": {
    "address": null,
    "asset": "A6524912715479370914",
    "quantity": 1,
    "utxo": "197badd60e340b0b270a89be6f18fa7a4fa3b855485d8206e91873470cf3fbf3:0",
    "utxo_address": "bc1qwfmtwelj00pghxhg0nsu0jqx0f76d5nm0axxvt"
  }
}
```

https://api.counterparty.io:4000/v2/addresses/bc1qwfmtwelj00pghxhg0nsu0jqx0f76d5nm0axxvt/balances

**Comment by ouziel-slama** [comment]
fixed here https://github.com/CounterpartyXCP/counterparty-core/pull/2542
