### ISSUE TITLE
Transaction chained with XCP dispense and utxo attach is just performing the dispense

### ISSUE THREAD

**Issue by JavierCervilla** [CounterpartyXCP/counterparty-core#2539]
Im creating a tx to reduce friction for users when xcp fee is active (as i know that now is 0) that has 2 msgs:
- dispense for XCP encoded in multisig
- utxo attaching encoded in OP_RETURN

its weird bc api route gives utxo_info for this tx so maybe is related with my previous issue #2538  and is an api thing:

https://api.counterparty.io:4000/v2/transactions/17233d0afde53291ebe593d196e4ea59b9298813b813d4b04a4fd132300d79ab

```
{
  "result": {
    "tx_index": 2950761,
    "tx_hash": "17233d0afde53291ebe593d196e4ea59b9298813b813d4b04a4fd132300d79ab",
    "block_index": 866799,
    "block_hash": "000000000000000000018785de91a879d134ad6c78989fa3ba057be2d11a3583",
    "block_time": 1729570666,
    "source": "bc1qwfmtwelj00pghxhg0nsu0jqx0f76d5nm0axxvt",
    "destination": "bc1qm0gx0mwlj2rdfuuy83htptdsadyl0fyk6lhg0s",
    "btc_amount": 634,
    "fee": 0,
    "data": "0d00",
    "supported": true,
    "utxos_info": "17233d0afde53291ebe593d196e4ea59b9298813b813d4b04a4fd132300d79ab:0",
    "confirmed": true
  }
}
```
the stored data also looks a bit weird for me:     `"data": "0d00"`

edited: looks like all the dispenses tx shows data in `utxos_info` when calling `/v2/transactions/` endpoint
 - eg: https://api.counterparty.io:4000/v2/transactions/dd9f09e6e7b4a34b039ce560ea4e946ae154ecaeb7bc69659e4f7857c5ac976f

edited2: looks like it has neither dispense the XCP

**Comment by JavierCervilla** [comment]
Good thing is that despite having 2 messages counterparty has not broke :D

**Comment by ouziel-slama** [comment]
this is not supported by the protocol :) 
it is normal that only the first valid `data` encountered is taken into account.

**Comment by JavierCervilla** [comment]
When we were talking about the gas fee system the conclussion was that this will be possible to do, to avoid the problem for dont have a good way to buy XCP for newcomers. Was supposed also to be this the place to discuss this kind of things so i dont understand why do you closed the issue. Okey now is not supported for the protocol, i have already see it, thats why i openned the issue to be if will be possible to add it on the future as that was what we agree on telegram dev group with Adam and Evan.

**Comment by JavierCervilla** [comment]
at least would be possible for a future update to pay the xcp from another address? including a signed utxo input from the wallet that holds the xCP?

**Comment by reinamora137** [comment]
looks like this one: https://github.com/CounterpartyXCP/counterparty-core/issues/2197

**Comment by reinamora137** [comment]
as part of this milestone release for future reference: https://github.com/CounterpartyXCP/counterparty-core/milestone/30

**Comment by ouziel-slama** [comment]
@JavierCervilla sorry there was no bad intention! I thought you were reporting a bug not that you wanted to open a discussion!
Yes this is planned as mentioned by @reinamora137

**Comment by adamkrellenstein** [comment]
yeah let's centralize discussion of this matter in this issue: https://github.com/CounterpartyXCP/counterparty-core/milestone/30
