### ISSUE TITLE
Getting 'insufficient balance' error when doing MPMA send 

### ISSUE THREAD

**Issue by jdogresorg** [CounterpartyXCP/counterparty-core#2541]
When doing an MPMA send using both /v1/ and /v2/ endpoints I am getting an error message from counterparty-core that I have 'insufficient funds" when in fact, there are plenty of funds to complete the MPMA send

![image](https://github.com/user-attachments/assets/296fa597-bd35-4f85-b0f8-01c34ef25f67)

Can very clearly see that I have 77 BACKINBLOOD tokens in my address `1JDogZS6tQcSxwfxhv6XKKjcyicYA4Feev/1JDogZS6tQcSxwfxhv6XKKjcyicYA4Feev`, and am trying to send 2, but am getting an error message about having "insufficient funds"

**Comment by ouziel-slama** [comment]
could you please provide the exact query you are trying ?
