### ISSUE TITLE
546 Sats

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2543]
<img width="642" alt="image" src="https://github.com/user-attachments/assets/8a359b44-7e3a-4efa-ba48-df19f7a2679c">

**Comment by ouziel-slama** [comment]
we are already using 546 as default value: https://github.com/CounterpartyXCP/counterparty-core/blob/master/counterparty-core/counterpartycore/lib/config.py#L128
