### ISSUE TITLE
Filter out `Open_fairminters` from the the /issuances apis

### ISSUE THREAD

**Issue by luchenkob** [CounterpartyXCP/counterparty-core#2544]
maybe have a filter query param to filter issuances responding endpoints with `asset_events`

**Comment by ouziel-slama** [comment]
done here https://github.com/CounterpartyXCP/counterparty-core/pull/2558/commits/339bfb4844c7da358fdd2945213c366028fc4712
in the next version you could use `asset_events=creation,reissuance` for example.
