### ISSUE TITLE
show_unconfirmed not working in v2 balances endpoint

### ISSUE THREAD

**Issue by loon3** [CounterpartyXCP/counterparty-core#2546]
```https://api.counterparty.io:4000/v2/addresses/bc1qxlupt9rg4vxvtyqgjq70x293uffx9j6qehsrcv/balances?verbose=true&show_unconfirmed=true```

not showing unconfirmed tx, specifically a utxo attach, here's mempool for that tx...

```
{"tx_hash": "b74ee2320a820615d5f70ea455262a7e6a6d0ab3e705be601fff6a8658ba6ac5", "command": "insert", "category": "debits", "bindings": "{\"action\":\"attach to utxo\",\"address\":\"bc1qxlupt9rg4vxvtyqgjq70x293uffx9j6qehsrcv\",\"asset\":\"GORF\",\"block_index\":866847,\"event\":\"b74ee2320a820615d5f70ea455262a7e6a6d0ab3e705be601fff6a8658ba6ac5\",\"quantity\":1,\"tx_index\":2950878,\"utxo\":null,\"utxo_address\":null}", "timestamp": 1729604726.8350766, "event": "DEBIT", "addresses": "bc1qxlupt9rg4vxvtyqgjq70x293uffx9j6qehsrcv"}
```

this is especially important for utxo attach so this utxo doesnt accidentally get spent in another tx

**Comment by ouziel-slama** [comment]
too complicate to add unconfirmed balances in `balances` table and there is a lot of way to get the same thing. See for example: https://github.com/CounterpartyXCP/counterparty-core/blob/master/counterparty-core/counterpartycore/test/regtest/scenarios/scenario_last_mempool.py#L51
or https://github.com/CounterpartyXCP/counterparty-core/blob/master/counterparty-core/counterpartycore/test/regtest/scenarios/scenario_last_mempool.py#L13
closing.
