### ISSUE TITLE
API /balances result when querying for a specific asset on an address only returns those attached to UTXO's

### ISSUE THREAD

**Issue by reinamora137** [CounterpartyXCP/counterparty-core#2551]
**Steps To Reproduce**

Call to: `/v2/addresses/1MZUaVy6y7vmwh2MqMKTFy2JiqXteyevpN/balances`

returns 2 results for MINTS token. one portion of the assets tied to a UTXO and another result with the remainder still on the account.

```
    {
      "address": null,
      "asset": "MINTS",
      "quantity": 6000,
      "utxo": "71342e070ab70f4b41ca7e4740e6bc7a7f3852410f78870949d38022cf421248:0",
      "utxo_address": "1MZUaVy6y7vmwh2MqMKTFy2JiqXteyevpN"
    },
    {
      "address": "1MZUaVy6y7vmwh2MqMKTFy2JiqXteyevpN",
      "asset": "MINTS",
      "quantity": 699999994000,
      "utxo": null,
      "utxo_address": null
    },
```

Call to `/v2/addresses/1MZUaVy6y7vmwh2MqMKTFy2JiqXteyevpN/balances/MINTS`

returns only 1 result

```
{
  "result": {
    "address": null,
    "asset": "MINTS",
    "quantity": 6000,
    "utxo": "71342e070ab70f4b41ca7e4740e6bc7a7f3852410f78870949d38022cf421248:0",
    "utxo_address": "1MZUaVy6y7vmwh2MqMKTFy2JiqXteyevpN"
  }
}
```

**Comment by reinamora137** [comment]
almost seems like this future optional param is enable, discussed on this issue: https://github.com/CounterpartyXCP/counterparty-core/issues/2550

**Comment by ouziel-slama** [comment]
fixed here https://github.com/CounterpartyXCP/counterparty-core/pull/2542
