### ISSUE TITLE
Clean Up and Refactor DB Connection Pooling and Management

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2554]
Make sure everything is 100% thread-safe.

Track all connections opened/closed for both connection pools, and on process shutdown, verify that no opened connections are left (and that the WAL and SHM files are not there).

We should distinguish very carefully the `main` process and the `api` process; we should have one DB connection pool for each and each should be initialized / cleaned up from `server.py`. We should have all of the `db.close()` statements in the `finally:` clause *inside* all running threads (rather than in the `stop()` methods). Etc. etc.

**Comment by ouziel-slama** [comment]
done here https://github.com/CounterpartyXCP/counterparty-core/pull/2786
