### ISSUE TITLE
`get_running_info` reporting incorrect block after 10.5 upgrade

### ISSUE THREAD

**Issue by jdogresorg** [CounterpartyXCP/counterparty-core#2559]
After updating to 10.5.0 last night, now my node is stuck reporting the last block incorrectly. The block displayed for `block_index` in last block is the last block that was parsed with 10.5.0-rc1 before updating.

`counterparty-core` continues to parse blocks, but the `last_block->block_index` is not updated as expected.

Stopping and starting the fednode has no effect.

![image](https://github.com/user-attachments/assets/9457f7ec-1dbb-4a9f-824b-218fea71668e)

Also `get_mempool` now reports no transactions.

![image](https://github.com/user-attachments/assets/61c72400-b1e4-4859-869b-361d1754fd9e)

**Comment by adamkrellenstein** [comment]
Yes, it's surprising. See: <img width="390" alt="Screenshot 2024-10-23 at 8 46 14 AM" src="https://github.com/user-attachments/assets/db9a4a6d-23d4-4bbf-b659-09c2e52e374b">

**Comment by jdogresorg** [comment]
Adding `--catchup=bootstrap-always` temporarily seems to have fixed the initial issue with `block_index` being wrong in `get_running_info`... However, getting some pretty long parse times for blocks.

![image](https://github.com/user-attachments/assets/ba2ab461-fbe7-4926-a218-a3a82795049a)

Can you think of any reason that parsing a block with just 1 tx should take 82+ seconds? There is nothing else running on this machine other than bitcoind/addrindexs/counterparty-core

**Comment by jdogresorg** [comment]
restarted `counterparty-core` to see if that sped up block parsing. Seems some blocks take way longer than one would expect (866855 took 577 seconds), and others parse quickly.

![image](https://github.com/user-attachments/assets/d067a376-e0b9-4e16-9173-6ecf7a105b21)

Any insight would be appreciated.

**Comment by jdogresorg** [comment]
Parsing has finally caught up, and last_block->block_index is being reported correctly.
