### ISSUE TITLE
If `hard_cap` is Set, Ensure `max_mint_per_tx`Divides Evenly into it if `price == 0`

### ISSUE THREAD

**Issue by pinnate-modo** [CounterpartyXCP/counterparty-core#2561]

**Comment by adamkrellenstein** [comment]
<img width="661" alt="image" src="https://github.com/user-attachments/assets/247c788a-3fbf-4d9a-9d83-418646d8665c">

**Comment by adamkrellenstein** [comment]
We just need to make sure that however much can be minted divides evenly into max_mint_per_tx if price == 0. E.g. if there have been issuances beforehand or if theres been a premint

**Comment by ouziel-slama** [comment]
fixed with partial mint here: https://github.com/CounterpartyXCP/counterparty-core/pull/2647
