### ISSUE TITLE
MPMA Send unable to send multiple memos

### ISSUE THREAD

**Issue by jdogresorg** [CounterpartyXCP/counterparty-core#2568]
Traditionally, MPMA Sends have allowed for a optional per-line memo, which can be either hex or not on a per-send basis.

According to the new /v2/ API docs, and the response from the `/address/<address>/compose/mpma` response, both `memo` and `memo_is_hex` fields are now only a SINGLE value rather than an array of values, as it has always been, and has been in the /v1/ API.

This forces the entire MPMA send to send one memo type, when an MPMA send can contain many memos, both hex and non-hex memos.

### Necessary Updates :
I feel the following needs to be updated to be "backwards-compatible":
1. API should be updated to allow specifying a comma separated list of text `memos`
2. API should be udpated to allow specifying a comma separated list of boolean values for `memo_is_hex`
3. API Documentation should be updated to indicate `memos` and `memo_is_hex` are comma separated values.

### Usage Example: 
User wants to distribute an MPMA send, and send a per-line memo, or a hexidecimal reference to the send
- Like when an exchange wants to batch their withdraws into a MPMA request, and reference a withdraw ID# for each Send.

### Example API Request: 
https://api.counterparty.io:4000/v2/addresses/1JDogZS6tQcSxwfxhv6XKKjcyicYA4Feev/compose/mpma?address=1JDogZS6tQcSxwfxhv6XKKjcyicYA4Feev&destinations=1Lfm6jXgCQi8LvjpgFHa2F4hdr1uJVa5t4%2Cbc1q50kxp76j9l0k9jgwasvcz4mcz0v03fv2y5pdxx&assets=BACKINBLOOD%2CBACKINBLOOD&quantities=1%2C1&memo=Test%20Memo%201%2C1JDogZS6tQcSxwfxhv6XKKjcyicYA4Feev&memo_is_hex=false%2Ctrue&exact_fee=4096&allow_unconfirmed_inputs=true

![image](https://github.com/user-attachments/assets/1437827e-15b5-408e-9da3-f0b3b2906930)

![image](https://github.com/user-attachments/assets/d682b0a2-6843-4538-a4a7-813300a61f0c)

![image](https://github.com/user-attachments/assets/41ac58ce-dd1f-471b-8e01-ca065e95a6c6)

**Comment by adamkrellenstein** [comment]
First of all, v2 is not supposed to be backwards-compatible with v1. Second of all, the v1 API is still live. Third of all, MPMA is a terribly designed feature that will be completely obviated in the following upcoming protocol change which introduces an actually sane way to pack multiple sends into a single BTC transaction: https://github.com/CounterpartyXCP/counterparty-core/issues/2197

**Comment by jdogresorg** [comment]
WOW!!.. SO one day you say that the V1 API is depreciated and no one should use it, and the next day you say that the V1 API is still available for use and it should be used for MPMA sends.

So, let me get this clear, your solution is to only have ONE memo for all the sends in a MPMA send rather than continuing to support multiple memos? And your official answer is your not going to fix this issue because your working on an implementation that you feel is more appropriate and "sane"?

**Comment by ouziel-slama** [comment]
@jdogresorg https://github.com/CounterpartyXCP/counterparty-core/blob/v9.61.3/counterpartylib/lib/messages/versions/mpma.py#L92
it was a bug in the API. mpma never supported a list for memo and memo_is_hex (see v9.61.3 in the link above). We didn't touch this function.

**Comment by jdogresorg** [comment]
You are wrong sir, MPMAs DID support multiple memos.  I know because I tested this feature before putting out releases.

### Example of a send which has multiple memos

Here you can see a MPMA send which has 67 different memos displayed in your own UL explorer.

https://explorer.unspendablelabs.com/tx/2123040

![image](https://github.com/user-attachments/assets/a8b2c3bb-0fd3-490e-b61d-3938a4cc7562)

### Quick dump of 25 MPMA sends which have multiple memos.

```
mysql> select count(distinct(memo)) as cnt, tx_index from sends group by tx_index order by cnt desc limit 25;
+-----+----------+
| cnt | tx_index |
+-----+----------+
|  67 |  2123040 |
|  18 |  1813503 |
|  12 |  2072205 |
|  11 |  2664322 |
|  10 |  2154600 |
|  10 |  2402935 |
|   8 |  2043312 |
|   8 |  2043311 |
|   8 |  2043313 |
|   8 |  1979337 |
|   7 |  2527118 |
|   7 |  1974262 |
|   6 |  2019503 |
|   6 |  1942688 |
|   5 |  1741107 |
|   5 |  1954696 |
|   5 |  2503113 |
|   5 |  1849337 |
|   5 |  2526535 |
|   5 |  1954375 |
|   5 |  1968918 |
|   5 |  1783305 |
|   4 |  2250660 |
|   4 |  1970155 |
|   4 |  2132118 |
+-----+----------+
25 rows in set (2.07 sec)
```

So clearly you are mistaken, counterparty DID support multiple memos, it was not a "BUG" in the API, and this functionality no longer works in `counterparty-core` 10.5

**Comment by adamkrellenstein** [comment]
Yes, you should have pointed this out six months ago. API v1 is now EOL.

**Comment by jdogresorg** [comment]
Got ya, Adam…. It’s my job to find bugs in your code months ago before I was forced to use a new API.Thanks for making it very clear. Your gaslighting is at epic levels. 🤷🏻‍♂️I find it interesting that yesterday you were saying to use the V1 API to continue generating MPMA sends  and today all of a sudden it’s EOL and you gaslight and try to blame me for finding issues that you should’ve found months ago.You may not like me pointing out problems in your code that you didn’t find for many many months, but you can’t deny the fact that counterparty has lost functionality, and rather than fixing the issue you blame other developers in a feeble attempt to scapegoat your lack of testing.And one wonders why we’ve had six hot fix releases in the past two weeks. lol🤷🏻‍♂️Sent fromw my iPhoneOn Oct 24, 2024, at 5:53 AM, Adam Krellenstein ***@***.***> wrote:﻿
Yes, you should have pointed this out six months ago. API v1 is now EOL.

**Comment by jdogresorg** [comment]
Marking my comment as abuse? For simply pointing out that your blaming me for not finding regressions in your code?

**Comment by adamkrellenstein** [comment]
Re-opened issue at https://github.com/CounterpartyXCP/counterparty-core/issues/2600
