### ISSUE TITLE
`'NoneType' object has no attribute 'cursor'`

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2569]
<img width="1057" alt="image" src="https://github.com/user-attachments/assets/87662e35-0543-4b26-9c1f-0dff779abddc">

**Comment by ouziel-slama** [comment]
it's from the APIStatusPoller here https://github.com/CounterpartyXCP/counterparty-core/blob/master/counterparty-core/counterpartycore/lib/api/api_v1.py#L483
Can't reproduce. Fixed with https://github.com/CounterpartyXCP/counterparty-core/pull/2521 ?
