### ISSUE TITLE
Compose Attach not adding dust

### ISSUE THREAD

**Issue by DerpHerpenstein** [CounterpartyXCP/counterparty-core#2570]
Compose attach is not creating a dust utxo to attach the asset to.  Perhaps i dont understand 

https://api.counterparty.io:4000/v2/addresses/bc1q20d2cdvy2x83h3ssrz5lgryy4c9wqxsgc749ej/compose/attach?asset=A241301191507000031&allow_unconfirmed_inputs=true&exact_fee=10000&quantity=1

`{"result": {"params": {"source": "bc1q20d2cdvy2x83h3ssrz5lgryy4c9wqxsgc749ej", "destination": null, "asset": "A241301191507000031", "quantity": 1}, "name": "utxo", "data": "434e545250525459646263317132306432636476793278383368337373727a356c67727979346339777178736763373439656a7c7c413234313330313139313530373030303033317c31", "btc_in": 15955, "btc_out": 0, "btc_change": 5955, "btc_fee": 10000, "rawtransaction": "02000000000101934ceddd2632bfc21cf5daf91a5560a729853102115ff9c15455de20993134af0300000016001453daac3584518f1bc61018a9f40c84ae0ae01a08ffffffff0200000000000000004c6a4a0505fa09d3b2c111f65f307a53482b6e29ec783bf55ec457d797af51335b4924c5d2a051d1b1618aa2b1fce7c2ad0187e79f8297d0e1272436849b910e31cb7bb8da6aeb960a82c87f76431700000000000016001453daac3584518f1bc61018a9f40c84ae0ae01a0802000000000000"}}`

![image](https://github.com/user-attachments/assets/bce9f62b-1132-445f-a2b7-7500117f52b3)

Am i missing something or should output 0 be a utxo of regular_dust_size?

**Comment by reinamora137** [comment]
i don't see anything in `compose` or `compose_attach` about creating a new utxo. Perhaps a new arg like `create_new_utxo=True` to trigger a new utxo be created would be ideal.

**Comment by ouziel-slama** [comment]
yeah! here the asset will be attached to the change output and is not a good idea (see https://github.com/CounterpartyXCP/counterparty-core/blob/master/counterparty-core/counterpartycore/lib/messages/utxo.py#L155). Will update the compose function to add a dust output before the change.

**Comment by reinamora137** [comment]
Great news thanks! This one helps a lot

**Comment by ouziel-slama** [comment]
fixed here https://github.com/CounterpartyXCP/counterparty-core/pull/2611
