### ISSUE TITLE
Dispense Fails with a Closed Dispenser on Same Address

### ISSUE THREAD

**Issue by jdogresorg** [CounterpartyXCP/counterparty-core#2571]
Since dispensers have been changed to require a `dispense` message to trigger a dispense instead of a normal BTC send, the feature of automatically detecting a BTC send to an address with an open dispenser and then auto-converting the request from a `send` to a `dispense` message is not consistently working.

To work around this issue, I have been working to update FreeWallet to handle generating the `dispense` transaction directly, but am getting nonsense errors.

## Issue 1 : Auto-conversions to `dispense` not working.

Auto-converting BTC `send` to `dispense` when `destination` has an open dispenser is not working consistently. 

Sometimes the auto-conversion works, sometimes it does not, and user are losing funds as a result. I have heard of users having issues with this feature both in FreeWallet and Horizon.

## Issue 2 : Invalid error message returned to valid dispense request

When trying to generate a `dispense` transaction on an address with an open dispenser, invalid error messages are returned

```
Source Address        : 1JDogZS6tQcSxwfxhv6XKKjcyicYA4Feev
Dispenser Address     : 1LJCLfaKU6aNUn5w96cge7woiBE4Hn22x8
Dispenser Transaction : 00a65b06e696a3d44fc14fbf6fbf4da15284d1e441a6ea3e49d136153b3f20b6
```

You can view open dispenser at :
https://tokenscan.io/tx/00a65b06e696a3d44fc14fbf6fbf4da15284d1e441a6ea3e49d136153b3f20b6

### Example API request
https://api.counterparty.io:4000/v2/addresses/1JDogZS6tQcSxwfxhv6XKKjcyicYA4Feev/compose/dispense?dispenser=1LJCLfaKU6aNUn5w96cge7woiBE4Hn22x8&quantity=1000000&exact_fee=1280&allow_unconfirmed_inputs=true

### Example API Response
"error": "['dispenser is not open', 'dispenser is empty', 'dispenser is not open', 'dispenser is empty']"

### Example response in FreeWallet showing errors from API
![image](https://github.com/user-attachments/assets/9624505f-5145-463e-b110-357145b8e8e4)

### Example response in POSTMAN showing errors from API
![image](https://github.com/user-attachments/assets/6dae0d12-ffd3-4c7b-8755-2563ffcc09c9)

I hope you take this matter seriously, as it is losing users funds by doing normal BTC sends when they should be `dispenses` and preventing people from actually using your new `dispense` transaction (your new/preferred method to trigger a dispense)

**Comment by ouziel-slama** [comment]
There is 3 dispensers at the address `1LJCLfaKU6aNUn5w96cge7woiBE4Hn22x8`: https://dev.counterparty.io:4000/v2/addresses/1LJCLfaKU6aNUn5w96cge7woiBE4Hn22x8/dispensers
Two of them are closed. Seems normal to me to prevent a transaction to this address but we could not raise an error if at least one dispenser is open.

**Comment by ouziel-slama** [comment]
we could add a argument `no_dispensers_check` when composing a dispense.

**Comment by jdogresorg** [comment]
it would seem to make the most sense to only raise the error if there is no dispenser open.

If a dispenser is open and a person is trying to create a dispense to that dispenser, I don’t know why you would wanna throw an error and prevent that dispense simply because the address had some dispensers open on it in the past…. Especially if you’re expecting users to reuse addresses for dispensers, rather than create new addresses for dispensers.

I think checking if a dispenser is open is a good thing, as it could prevent creating transactions to send to a dispenser that is not open… I also think a flag to bypass all checks makes less sense than just checking for a single open dispenser and returning a single error message only if there is no dispenser open.

Thank you for your attention to this matter 👍🏻

**Comment by pompotetonpote** [comment]
Hello, to add some info about a case, I tried to dispense XCP but it wasn't triggered.

The dispenser:
https://explorer.unspendablelabs.com/tx/f5726faee825674551719fc53c75a5e7c3908834ff89c8b7373477fa1a19d217

My send tx:
https://www.blockchain.com/explorer/transactions/btc/2be739d34c7805d726f3113c93379ee03a9614745fc8abc06358bd1d0b9ed1fb

I was using FreeWallet to do it, hope it can help to solve the issues.

Have a nice day

**Comment by diulef** [comment]
I'm also creating dispensers for used addresses. This worked fine in the past, and when you think about it, it shouldn’t really be an issue. The same applies to having multiple open dispensers on one address, allowing the dispensing of multiple assets at once.

**Comment by adamkrellenstein** [comment]
Yeah this looks like an unintentional change in behavior. Will look into making a protocol change to fix it.

Note: using the `create_send()` call to trigger dispensers is *not* advised. That's for backwards compatibility only. Ofc. everyone should switch to `create_dispense()` asap.

**Comment by adamkrellenstein** [comment]
See https://github.com/CounterpartyXCP/counterparty-core/pull/2575#pullrequestreview-2392420461
