### ISSUE TITLE
Fair Minting Test Cases

### ISSUE THREAD

**Issue by warrenpuffett** [CounterpartyXCP/counterparty-core#2602]
As part of updating the fair minting docs I came up with some test cases. The ones that are checked off have definitely been covered. The unchecked ones I'm not sure.

- [x]  T1: Create a valid fairminter
    
    Ensure a fairminter with valid parameters is successfully created.
    
- [x]  T2: Reuse an asset with an open fairminter
    
    Attempt to create a fairminter using an asset with an existing open fairminter (should fail).

https://github.com/CounterpartyXCP/counterparty-core/blob/develop/counterparty-core/counterpartycore/test/regtest/scenarios/scenario_20_fairminter.py#L282-L290
    
- [x]  T3: Asset creation with parent asset
    
    Ensure a fairminter can create a new asset with a parent asset that exists.

https://github.com/CounterpartyXCP/counterparty-core/blob/develop/counterparty-core/counterpartycore/test/regtest/scenarios/scenario_20_fairminter.py#L204-L281
    
- [x]  T4: Fee deduction for named asset creation
    
    Validate that 0.5 XCP is deducted when creating a named asset.

https://github.com/CounterpartyXCP/counterparty-core/blob/develop/counterparty-core/counterpartycore/test/regtest/scenarios/scenario_1_fairminter.py#L68-L82
    
- [x]  T5: Premint quantity exceeds hard cap
    
    Attempt to create a fairminter with `premint_quantity >= hard_cap` (should fail).

https://github.com/CounterpartyXCP/counterparty-core/blob/develop/counterparty-core/counterpartycore/test/fixtures/contract_vectors/fairminter.py#L117

- [x]  T6: Description locked check
    
    Create a fairminter with a locked asset description and ensure it fails if the provided description does not match.

https://github.com/CounterpartyXCP/counterparty-core/blob/42502984b9abff70264af9461962d3e72716c50c/counterparty-core/counterpartycore/test/regtest/scenarios/scenario_21_fairminter.py
    
- [x]  T7: Invalid start and end blocks
    
    Ensure fairminter creation fails if `start_block > end_block`.
    
- [x]  T8: Valid and invalid soft cap deadlines
    
    Ensure fairminter creation fails if `soft_cap_deadline_block <= start_block` or `>= end_block`.

https://github.com/CounterpartyXCP/counterparty-core/blob/79cde59cc639c814ddbb1f14089e4bb2128920cd/counterparty-core/counterpartycore/test/regtest/scenarios/scenario_21_fairminter.py
    
- [x]  T9: Successful mint with valid quantity
    
    Mint an asset under a valid open fairminter with sufficient balance.
    
- [x]  T10: Mint beyond max_mint_per_tx
    
    Attempt to mint more than `max_mint_per_tx` (should fail).
    
- [x]  T11: Insufficient XCP balance for minting
    
    Attempt to mint with insufficient XCP balance (should fail).

https://github.com/CounterpartyXCP/counterparty-core/blob/42502984b9abff70264af9461962d3e72716c50c/counterparty-core/counterpartycore/test/regtest/scenarios/scenario_21_fairminter.py
    
- [x]  T12: Mint exceeding hard cap
    
    Attempt to mint such that the total supply exceeds `hard_cap` (should fail).
    
- [x]  T13: Free mint with incorrect quantity
    
    Attempt a mint with `quantity != 0` for a free asset (should fail).
    
- [x]  T14: Hard cap reached during mint
    
    Mint the last available units to hit the hard cap and ensure the fairminter closes correctly.

https://github.com/CounterpartyXCP/counterparty-core/blob/develop/counterparty-core/counterpartycore/test/regtest/scenarios/scenario_16_fairminter.py#L181
    
- [x]  T15: Commission calculation validation
    
    Mint and ensure the commission awarded to the issuer is calculated correctly.

https://github.com/CounterpartyXCP/counterparty-core/blob/42502984b9abff70264af9461962d3e72716c50c/counterparty-core/counterpartycore/test/regtest/scenarios/scenario_21_fairminter.py
    
- [x]  T16: Soft cap not reached refund
    
    Mint under a soft-capped fairminter, fail to reach the soft cap by the deadline, and ensure payments are refunded.

https://github.com/CounterpartyXCP/counterparty-core/blob/develop/counterparty-core/counterpartycore/test/regtest/scenarios/scenario_2_fairminter.py#L417
    
- [x]  T17: Escrowed minting behavior
    
    Ensure mints under a soft-capped fairminter before the cap is hit are escrowed.

https://github.com/CounterpartyXCP/counterparty-core/blob/develop/counterparty-core/counterpartycore/test/regtest/scenarios/scenario_2_fairminter.py#L303
    
- [x]  T18: Burn payment validation
    
    Mint under a fairminter with `burn_payment=True` and ensure the XCP is burned.

https://github.com/CounterpartyXCP/counterparty-core/blob/42502984b9abff70264af9461962d3e72716c50c/counterparty-core/counterpartycore/test/regtest/scenarios/scenario_21_fairminter.py
    
- [x]  T19: Fairminter opening hook
    
    Simulate a block where the `start_block` equals the current block and ensure the fairminter opens.

https://github.com/CounterpartyXCP/counterparty-core/blob/79cde59cc639c814ddbb1f14089e4bb2128920cd/counterparty-core/counterpartycore/test/regtest/scenarios/scenario_21_fairminter.py
    
- [x]  T20: Premint quantity release
    
    Ensure the preminted quantity is credited to the issuer if no soft cap is set.

https://github.com/CounterpartyXCP/counterparty-core/blob/42502984b9abff70264af9461962d3e72716c50c/counterparty-core/counterpartycore/test/regtest/scenarios/scenario_21_fairminter.py
    
- [x]  T21: Soft cap hit before deadline
    
    Ensure hitting the soft cap credits escrowed payments and assets correctly.

https://github.com/CounterpartyXCP/counterparty-core/blob/develop/counterparty-core/counterpartycore/test/regtest/scenarios/scenario_1_fairminter.py#L329
    
- [x]  T22: Fairminter closure on end block
    
    Ensure fairminter status changes to closed when `end_block` is reached.

https://github.com/CounterpartyXCP/counterparty-core/blob/42502984b9abff70264af9461962d3e72716c50c/counterparty-core/counterpartycore/test/regtest/scenarios/scenario_21_fairminter.py
    
- [x]  T23: Description lock at hard cap
    
    Ensure the asset description is locked if configured when the hard cap is reached.

https://github.com/CounterpartyXCP/counterparty-core/blob/42502984b9abff70264af9461962d3e72716c50c/counterparty-core/counterpartycore/test/regtest/scenarios/scenario_21_fairminter.py
    
- [x]  T24: Max mint per tx division check
    
   Ensure the last mint receives what is left to reach the hard cap

https://github.com/CounterpartyXCP/counterparty-core/blob/42502984b9abff70264af9461962d3e72716c50c/counterparty-core/counterpartycore/test/regtest/scenarios/scenario_16_fairminter.py

**Comment by ouziel-slama** [comment]
thank you @warrenpuffett !! done here https://github.com/CounterpartyXCP/counterparty-core/pull/2676
