### ISSUE TITLE
`Health check failed: construct() got an unexpected keyword argument 'fee'`

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2605]
https://counterparty.sentry.io/issues/6023435212/?alert_rule_id=15343752&alert_type=issue&notification_uuid=03374b54-29f2-4d8a-bb74-3a874218f3c3&project=4507062633365504&referrer=slack
<img width="1067" alt="Screenshot 2024-10-27 at 1 53 41 PM" src="https://github.com/user-attachments/assets/adbff226-2d8a-4202-9973-9eeb6b879346">

**Comment by ouziel-slama** [comment]
fixed here https://github.com/CounterpartyXCP/counterparty-core/pull/2606
