### ISSUE TITLE
Potential issues with current UTXO mechanism

### ISSUE THREAD

**Issue by btcopenstamp** [CounterpartyXCP/counterparty-core#2623]
For FairMinters, we ([https://openstamp.io/](https://openstamp.io/)) have launched account model-based trading and are currently exploring Counterparty's UTXO design to support Atomic Swap trading in the UTXO model. However, we have found that the current UTXO design may have certain inconsistencies with its intended purpose:

**Currently, Counterparty allows assets to be attached to already spent UTXOs**  
   
   One of the main reasons Counterparty introduced the UTXO model was to allow Counterparty assets to be compliant with the Ordinals trading transactional structure, facilitating seamless integration of Counterparty assets into the Ordinals ecosystem for major Ordinals players.  
   
   However, allowing assets to be attached to already spent UTXOs prevents achieving a consistent trading model with Ordinals, as Atomic Swap transactions need to reference UTXOs to which assets are attached.

Therefore, our recommendations are as follows for a reference:

Assets should not be specifically attached to a particular UTXO but rather to the outputs of the current transaction by default, with attachment to the first non-OP_RETURN output.

**Comment by adamkrellenstein** [comment]
> Assets should not be specifically attached to a particular UTXO but rather to the outputs of the current transaction by default, with attachment to the first non-OP_RETURN output.

This is already possible. You simply don't specify the `destination` when attaching.

**Comment by ouziel-slama** [comment]
@btcopenstamp thank you very much for this report and all these great suggestions!!
Please see https://github.com/CounterpartyXCP/counterparty-core/pull/2626
