### ISSUE TITLE
Discrepancy in Number of Broadcasts

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2625]
API v2:      87,123     v10.6

HORIZON:     87,123     v10.6
XCP.IO:     107,040     v10.6
TOKENSCAN:  107,018     v10.6

**Comment by adamkrellenstein** [comment]
not reproducible

**Comment by jdogresorg** [comment]
FYI the difference between 107,040 and 87,123 is simply that API v2 onlys shows 'valid' broadcasts and not ALL broadcasts.

> not reproducible

Seems pretty "reproducible" to me... API v2 only shows when status=`valid` 🤷‍♂️

![telegram-cloud-photo-size-1-4976603714710253655-x](https://github.com/user-attachments/assets/a260c9b0-e8e1-4f8e-a25d-17fe7c7f1aac)

![image](https://github.com/user-attachments/assets/403f7e8e-b515-414a-982c-59f4a2a05131)
