### ISSUE TITLE
Asset Longname: "" vs null

### ISSUE THREAD

**Issue by droplister** [CounterpartyXCP/counterparty-core#2629]
On a balance endpoint, I noticed that MINTS has `asset_longname: ""` instead of `asset_longname: null`. It's preferable that it's null consistently, imo. It's coming from this line of code. I don't have the bandwidth to do so, but I think the fairminter.py could use a refactor to implement things more similarly/consistently with issuance.py, using the existing util functions, etc. 

https://github.com/CounterpartyXCP/counterparty-core/blob/3096f79cc136b2df184477a69312d38a555a3915/counterparty-core/counterpartycore/lib/messages/fairminter.py#L413-L416

```
{
"address": "19QWXpMXeLkoEKEJv2xo9rn8wkPCyxACSX",
"asset": "BALLOTBURN",
"quantity": 1,
"utxo": null,
"utxo_address": null,
"asset_info": {
"asset_longname": null,
"description": "https://easyasset.art/j/pbrxav/BALLO.json",
"issuer": "1JJP986hdU9Qy9b49rafM9FoXdbz1Mgbjo",
"divisible": false,
"locked": false
},
"quantity_normalized": "1"
},
{
"address": "19QWXpMXeLkoEKEJv2xo9rn8wkPCyxACSX",
"asset": "MINTS",
"quantity": 3900000000000,
"utxo": null,
"utxo_address": null,
"asset_info": {
"asset_longname": "",
"description": "FAIRMINT",
"issuer": "1FairPYzS6MJJq5fPQqf3M58ZxJEpkiGfX",
"divisible": true,
"locked": false
},
"quantity_normalized": "39000.00000000"
},
```

**Comment by ouziel-slama** [comment]
fixed here https://github.com/CounterpartyXCP/counterparty-core/pull/2700/commits/d7c6d6dd9d4cab818ba62b00c7a8aa7ca5f681a3
