### ISSUE TITLE
`AttributeError` on `decoded_block.get("height")`

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2630]
<img width="1060" alt="image" src="https://github.com/user-attachments/assets/b8d86186-58b2-4c23-bf6c-b0a166a8f3f1">

**Comment by ouziel-slama** [comment]
fixed here https://github.com/CounterpartyXCP/counterparty-core/pull/2700/commits/e1f4b71a8d6c30c9e8399e1be943ff2fbf1d91b6
