### ISSUE TITLE
Update UTXO Support Docs

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2634]
in particular we should describe:

1. Attach
- [x] The attach operation does not allow specifying a specific UTXO for binding.
- [x] Use the destination field to specify the vout of the outputs, indicating the output index in the attach transaction to which the asset will be bound.
- [x] If the destination vout points to an OP_RETURN, the transaction should be invalid.
- [x] If destination is not specified, default to binding to the first non-OP_RETURN output; if no non-OP_RETURN output exists, the transaction is invalid.
- [x] Don't specify the source address in the data, as assets can be directly deducted from the transaction's source by default. This presents no security risk and reduces data size.
- [x] The attach data can now be encoded directly into OP_RETURN without requiring Multi-Sig, which will significantly reduce attach transaction fees.
2. Detach
- [x] Don't specify the specific source UTXO; the source can refer to the UTXO to detach by positioning it within the detach transaction's vins. This ensures that the UTXO to be detached is included as an input in the transaction.
- [x] The detach data can now be encoded directly into OP_RETURN without requiring Multi-Sig, greatly reducing detach transaction fees.

We should include in the release notes a link to the updated docs.

**Comment by ouziel-slama** [comment]
done here https://github.com/CounterpartyXCP/Documentation/pull/220
