### ISSUE TITLE
Show Dispenser Price per Unit and Allow Sorting on that Field

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2638]

**Comment by droplister** [comment]
Having done a lot of price related indexing, one weird edge case with price per unit are divisible assets with less than 1.00000000 supply. For example, 0.000015000. Calculating a price per 1.00000000 usually gives you a really high price for an amount of the asset that's not possible to buy anyways. I think people understand it and "get it", but you get a more realistic price, in these instances, calculating the price per 0.00000001. It would be very reasonable to not create special logic for these cases just putting it out there.

**Comment by ouziel-slama** [comment]
done here https://github.com/CounterpartyXCP/counterparty-core/pull/2657
