### ISSUE TITLE
BUG with detach detected as utxo move and moving assets to first multisig output instead detaching when including the utxo to detach as input

### ISSUE THREAD

**Issue by JavierCervilla** [CounterpartyXCP/counterparty-core#2639]
Example transaction, assets sent to first multisig outpup instead of detaching.
`33956989b8f51f3225ff6d931dac6d8c040e5756c797ece1dc50b752c1366d4d`
here you can see that the tokens are holded in the first msig output
https://api.counterparty.io:4000/v2/utxos/33956989b8f51f3225ff6d931dac6d8c040e5756c797ece1dc50b752c1366d4d:0/balances

**Comment by adamkrellenstein** [comment]
@ouziel-slama this was just fixed, right?

**Comment by ouziel-slama** [comment]
@adamkrellenstein right! fixed in https://github.com/CounterpartyXCP/counterparty-core/pull/2626
