### ISSUE TITLE
High-Level Property Testing Suite

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2641]

**Comment by ouziel-slama** [comment]
see https://github.com/CounterpartyXCP/counterparty-core/blob/develop/counterparty-core/counterpartycore/test/regtest/properytestnode.py
and https://github.com/CounterpartyXCP/counterparty-core/blob/develop/counterparty-core/counterpartycore/test/regtest/utxosupport_propertytest.py
