### ISSUE TITLE
Allow All Responses to be Sorted by `block_time`

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2642]

**Comment by ouziel-slama** [comment]
hum.. it's really not trivial because the `block_time` field is present only in the table `blocks`.. however `sort=block_index` is already available for most of the tables and returns exactly the same order.. what advantage of having `block_time` too?

**Comment by adamkrellenstein** [comment]
Oh this was just a feature requested by a user. If it's redundant we can close!

**Comment by pinnate-modo** [comment]
@adamkrellenstein given that the Core issue is [not planned](https://github.com/CounterpartyXCP/counterparty-core/issues/2642#issuecomment-2470754836) what do we do here?
