### ISSUE TITLE
balances V2 verbose showing incorrect asset info

### ISSUE THREAD

**Issue by loon3** [CounterpartyXCP/counterparty-core#2644]
https://api.counterparty.io:4000/v2/addresses/1AmCna74MNY4YxDWQWc1tL9bhiogeRzqSj/balances/PEPENATION?verbose=true
results show `locked: false` the incorrect state for this asset

https://api.counterparty.io:4000/v2/assets/PEPENATION
results show `locked: true` the correct state for this asset

**Comment by ouziel-slama** [comment]
fixed here https://github.com/CounterpartyXCP/counterparty-core/pull/2657/commits/90ae78138c3e672d924f264ee5fa8cefaa14a4b2
