### ISSUE TITLE
Gunicorn WORKER TIMEOUT (pid:67)

### ISSUE THREAD

**Issue by ouziel-slama** [CounterpartyXCP/counterparty-core#2645]
https://counterparty.sentry.io/issues/6041592970?alert_rule_id=15343752&alert_type=issue&groupId=6041592970&notification_uuid=adc3227d-c68a-46b8-8917-2a76418b37c9&pageEnd=2024-11-04T21%3A11%3A38.112&pageStart=2024-11-03T21%3A11%3A38.112&project=4507062633365504&referrer=slack&source=issue_details

<img width="873" alt="Capture d’écran 2024-11-04 à 10 15 22" src="https://github.com/user-attachments/assets/9ebed269-157e-4b6e-b4d9-131f717bad91">

**Comment by adamkrellenstein** [comment]
Merged with https://github.com/CounterpartyXCP/counterparty-core/issues/2621
