### ISSUE TITLE
API to get a subasset info eg `/assets/A17191730846371319683.FROG`

### ISSUE THREAD

**Issue by luchenkob** [CounterpartyXCP/counterparty-core#2660]
we don't have api to get sub-asset details ie
`/assets/A17191730846371319683.FROG` doesn't work

**Comment by ouziel-slama** [comment]
in fact that works, for example https://api.counterparty.io:4000/v2/assets/BTCSTAMPART.NINE
there is a bug with `A17191730846371319683.FROG`
see https://github.com/CounterpartyXCP/counterparty-core/issues/2661
