### ISSUE TITLE
--catch-up=bootstrap not bootstrapping on testnet

### ISSUE THREAD

**Issue by dime-squanderer** [CounterpartyXCP/counterparty-core#2668]
(venv)  ~/Library/Application Support/counterparty/ /Users/dime/counterparty/counterparty-core/venv/bin/python /opt/homebrew/bin/counterparty-server --testnet start --indexd-port 28432 --catch-up=bootstrap

Counterparty Core v10.6.1
Verbosity: 0
Quiet: False
Network: testnet
Configuration File: /Users/dime/Library/Application Support/counterparty/server.conf
Counterparty Database: /Users/dime/Library/Application Support/counterparty/counterparty.testnet.db
Counterparty API Database: /Users/dime/Library/Application Support/counterparty/counterparty.testnet.api.db
Rust Fetcher Database: /Users/dime/Library/Caches/counterparty/fetcherdb.testnet
Server Log: /Users/dime/Library/Logs/counterparty/server.testnet.log
API Access Log: /Users/dime/Library/Logs/counterparty/server.testnet.access.log

------------------------------ START ------------------------------

2024-11-06T18:07:47.281-05:00 - [    INFO] - Connecting to database... (SQLite 3.45.1.0)
2024-11-06T18:07:47.283-05:00 - [    INFO] - Initializing database...
2024-11-06T18:07:47.288-05:00 - [    INFO] - Database version number updated.
2024-11-06T18:07:47.288-05:00 - [    INFO] - Running PRAGMA optimize...
^C2024-11-06T18:07:59.367-05:00 - [ WAR

**Comment by ouziel-slama** [comment]
```
$ counterparty-server start --testnet --catch-up=bootstrap

Counterparty Core v10.7.0
Verbosity: 0
Quiet: False
Network: testnet
Configuration File: /home/ouziel/.config/counterparty/server.conf
Counterparty Database: /home/ouziel/.local/share/counterparty/counterparty.testnet.db
Counterparty API Database: /home/ouziel/.local/share/counterparty/counterparty.testnet.api.db
Rust Fetcher Database: /home/ouziel/.cache/counterparty/fetcherdb.testnet
Server Log: /home/ouziel/.cache/counterparty/log/server.testnet.log
API Access Log: /home/ouziel/.cache/counterparty/log/server.testnet.access.log

------------------------------ START ------------------------------

WARNING: `counterparty-server bootstrap` downloads a recent snapshot of a Counterparty database
from a centralized server maintained by the Counterparty Core development team.
Because this method does not involve verifying the history of Counterparty transactions yourself,
the `bootstrap` command should not be used for mission-critical, commercial or public-facing nodes.
        
2024-11-13T09:44:26.133+00:00 - [    INFO] - Downloading database from https://bootstrap.counterparty.io/counterparty-testnet.latest.tar.gz...
````

seems to works well. @dime-squanderer did you make sure to clear the database before running this command? with `--catch-up=bootstrap` the server bootstraps if, and only if, the file does not exist. If you want to overwrite existing files you have to use `--catch-up=bootstrap-always`.
