### ISSUE TITLE
On testnet, re-orgs take down the node

### ISSUE THREAD

**Issue by DerpHerpenstein** [CounterpartyXCP/counterparty-core#2670]
Per @jdogresorg on telegram...

<img width="375" alt="image" src="https://github.com/user-attachments/assets/4feca914-f6a3-4865-b7ca-d14ebc3ea999">
<img width="375" alt="image" src="https://github.com/user-attachments/assets/0137e507-8480-444f-a89d-42024447629b">
<img width="750" alt="image" src="https://github.com/user-attachments/assets/b890f832-3ceb-40fb-8f29-ffa10c7a5cbb">
<img width="750" alt="image" src="https://github.com/user-attachments/assets/4e601b59-017c-454c-adf6-718a60e917d6">
<img width="750" alt="image" src="https://github.com/user-attachments/assets/76464657-16dc-4ee4-bb3d-bb5b9c171f29">

**Comment by adamkrellenstein** [comment]
Thanks for reporting this. Someone else already did and it was fixed here: https://github.com/CounterpartyXCP/counterparty-core/pull/2663/commits/4317603edfa279a7d02563d5c8027aa3e39cf08a
