### ISSUE TITLE
Has -> Have

### ISSUE THREAD

**Issue by droplister** [CounterpartyXCP/counterparty-core#2684]
nit on grammar
https://github.com/CounterpartyXCP/counterparty-core/blob/3096f79cc136b2df184477a69312d38a555a3915/counterparty-core/counterpartycore/lib/messages/dispenser.py#L231-L236

**Comment by ouziel-slama** [comment]
fixed here https://github.com/CounterpartyXCP/counterparty-core/pull/2700/commits/42f5b7771a9bded00ac4b646111c4b27ae1c7c1f
