### ISSUE TITLE
Add Asset Longname to Select for Sort

### ISSUE THREAD

**Issue by droplister** [CounterpartyXCP/counterparty-core#2699]
In 10.7.0

Looks like this one is probably on me:
/v2/addresses/19QWXpMXeLkoEKEJv2xo9rn8wkPCyxACSX/balances?verbose=true&sort=asset

```
[ERROR] - Error in API: SQLError: no such column: asset_longname
```

Something like this is needed:
```
if sort_name == "asset":
    # Ensure asset_longname is included in the SELECT clause
    if "asset_longname" not in select:
        select += ", asset_longname"
    order_by.append(f"COALESCE(asset_longname, asset) {sort_order.upper()}")
```

**Comment by ouziel-slama** [comment]
hum.. the problem is that we don't have the `asset_longname` field in the `balances` table and I don't really want to use a join. `verbose=true` enriches the results after the SQL query and we can't sort with the fields that contain.

**Comment by ouziel-slama** [comment]
yeah not trivial and don't think worth the effort. let's reopen if there is strong user demand in the future.
