### ISSUE TITLE
API Endpoint for checking existing of attached assets

### ISSUE THREAD

**Issue by warrenpuffett** [CounterpartyXCP/counterparty-core#2706]
@ouziel-slama It may be useful to know the inverse of what is described in #2705. Wallets will need to be able to avoid paying with UTXOs that have assets attached. An endpoint that just checks whether or not a list of UTXOs have attached assets would make this convenient to figure out.

Something like `GET /utxos/asset-status?utxos=x,y,z` or `GET /assets/attached-status?utxos=x,y,z`

**Comment by droplister** [comment]
I'm working on a wallet and am thinking this can be outsourced to these checks:
https://github.com/CounterpartyXCP/counterparty-core/blob/6c47c005c31fda70fe5284e43a1752bd4f8f2842/counterparty-core/counterpartycore/lib/transaction_helper/transaction_inputs.py#L305-L317

And these API settings introduced in 10.6.1?
- Add `use_utxos_with_balances` and `exclude_utxos_with_balances` parameters to the compose API

It's more the unconfirmed utxos that concern me and accidentally spending an attached utxo while chaining txs.

**Comment by adamkrellenstein** [comment]
As @droplister said, we already have a param for removing UTXOs with attached assets from the composition API; but wallets really shouldn't be using that API in the long run... they should be picking their own UTXOs for use as inputs. In that case, it'll be nice to be able to see which UTXOs have attached assets.

Can we just use this as a heuristic? https://github.com/CounterpartyXCP/counterparty-core/issues/2543

**Comment by ouziel-slama** [comment]
Also even if it is the wallet's responsibility to select the utxos, the API can still return an error when one of the utxos has assets attached. This is the case today: if `inputs_set` contains utxos with balances an error is returned.
There is two flag to bypass the default behavior:

```
    "use_utxos_with_balances": (
        bool,
        False,
        "Use UTXO with balances",
    ),
    "exclude_utxos_with_balances": (
        bool,
        False,
        "Exclude silently UTXO with balances instead of raising an exception",
    ),
```

**Comment by ouziel-slama** [comment]
done here https://github.com/CounterpartyXCP/counterparty-core/pull/2721
