### ISSUE TITLE
Add description_locked to API

### ISSUE THREAD

**Issue by droplister** [CounterpartyXCP/counterparty-core#2724]
It would be nice if this was available on the /assets/ASSET endpoint. It's only surfaced on the issuances endpoint which isn't a reliable way to determine if an asset is locked or description_locked because of how fairmints can result in a lot of issuance messages and the last issuance message can be locked = false, description_locked = false even if the asset itself is locked or description_locked because of how they're not reflective of state so much as the upsert you're intereted in making with the issuance.

**Comment by ouziel-slama** [comment]
done
