### ISSUE TITLE
BUG with detach detected as utxo move and moving assets to first multisig output instead detaching when including the utxo to detach as input

### ISSUE THREAD

**Issue by zswdgithub** [CounterpartyXCP/counterparty-core#2727]
Example transaction, assets sent to first multisig outpup instead of detaching.
33956989b8f51f3225ff6d931dac6d8c040e5756c797ece1dc50b752c1366d4d
here you can see that the tokens are holded in the first msig output
https://api.counterparty.io:4000/v2/utxos/33956989b8f51f3225ff6d931dac6d8c040e5756c797ece1dc50b752c1366d4d:0/balances

I need to bounce output to multi-signature assets

**Comment by adamkrellenstein** [comment]
This was fixed in this release, for which the protocol change has not yet activated: https://github.com/CounterpartyXCP/counterparty-core/releases/tag/v10.7.0

**Comment by adamkrellenstein** [comment]
@ouziel-slama this was fixed in https://github.com/CounterpartyXCP/counterparty-core/releases/tag/v10.7.0 correct?

**Comment by ouziel-slama** [comment]
yes I confirm.
