### ISSUE TITLE
`AttributeError` Error 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2729]
https://counterparty.sentry.io/issues/6037375322/?project=4507062633365504&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&statsPeriod=7d&stream_index=0

<img width="1063" alt="Screenshot 2024-11-18 at 8 06 25 AM" src="https://github.com/user-attachments/assets/4464f321-7391-4e77-baba-368402531955">

**Comment by ouziel-slama** [comment]
already fixed here https://github.com/CounterpartyXCP/counterparty-core/commit/e1f4b71a8d6c30c9e8399e1be943ff2fbf1d91b6
