### ISSUE TITLE
`movetoutxo` is a confusing name

### ISSUE THREAD

**Issue by pinnate-modo** [CounterpartyXCP/counterparty-core#2763]
In fact, you're moving _from_ a UTXO and, per the docs, to an address.
![image](https://github.com/user-attachments/assets/f00728fd-6bb5-48a4-8edc-a910126c0e4d)

**Comment by adamkrellenstein** [comment]
We could just rename this to `move`. The most important thing is to update the docs though.

**Comment by adamkrellenstein** [comment]
Can we also include the line, "`movetoutxo` is like `send` but for moving from one UTXO to another, with the `destination` is specified as an address."?
