### ISSUE TITLE
Property Test Transaction Construction

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2780]
To catch problems like https://github.com/CounterpartyXCP/counterparty-core/pull/2777/files and https://github.com/CounterpartyXCP/counterparty-core/pull/2735/files

**Comment by ouziel-slama** [comment]
done here https://github.com/CounterpartyXCP/counterparty-core/pull/2795/commits/26d7bbe27fdd289897319df540f62a7e91fb54d3
