### ISSUE TITLE
UTXO Outputs Should Be 10,000 Sats

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2782]
When composing an attach / move, we should use `10,000` sats for the value, rather than `546`, which is the dust size. Then there's enough BTC for people to actually use that output. This is sort of a standard in the Ordinals space.

**Comment by ImagiNFT** [comment]
IMO is a bit dangerous doing it as default for 10k sats, as there is more risk to acidentally spend that utxo

**Comment by adamkrellenstein** [comment]
The Counterparty node API prevents the accidental spend of UTXOs with assets attached.

Also it's the standard for Ordinals, per https://github.com/me-foundation/msigner and:
![IMG_9127](https://github.com/user-attachments/assets/2bd83f3c-2bc8-4091-8d09-dfacaf3b3f2f)

**Comment by ouziel-slama** [comment]
done here https://github.com/CounterpartyXCP/counterparty-core/pull/2786/commits/61f4aa21ff59c0026b89f1885726132b751e8dd3
