### ISSUE TITLE
The holders endpoint does not return the same response when querying a subasset using its asset_longname versus its asset field

### ISSUE THREAD

**Issue by ImagiNFT** [CounterpartyXCP/counterparty-core#2784]
The holders endpoint does not return the same response when querying a subasset using its asset_longname versus its asset field

https://api.counterparty.io:4000/v2/assets/TOPINI.LONGONE/balances
![image](https://github.com/user-attachments/assets/e2fcbd7f-f400-4499-aac7-4f0658e90d72)

https://api.counterparty.io:4000/v2/assets/A95428957753448833/balances
![image](https://github.com/user-attachments/assets/7780f8ab-4d92-48bc-98a7-71088f17de89)

**Comment by ouziel-slama** [comment]
done here https://github.com/CounterpartyXCP/counterparty-core/pull/2786
