### ISSUE TITLE
bypass transaction building on compose when return_only_data is true

### ISSUE THREAD

**Issue by loon3** [CounterpartyXCP/counterparty-core#2787]
[This large mpma compose](https://api.counterparty.io:4000/v2/addresses/bc1qxlupt9rg4vxvtyqgjq70x293uffx9j6qehsrcv/compose/mpma?assets=PINATAPEPE,PINATAPEPE,PINATAPEPE,PINATAPEPE,PINATAPEPE,PINATAPEPE,PINATAPEPE,PINATAPEPE,PINATAPEPE,PINATAPEPE,PINATAPEPE,PINATAPEPE,PINATAPEPE,PINATAPEPE,PINATAPEPE,PINATAPEPE,PINATAPEPE,PINATAPEPE,PINATAPEPE,PINATAPEPE,PINATAPEPE,PINATAPEPE,PINATAPEPE,PINATAPEPE,PINATAPEPE,PINATAPEPE,PINATAPEPE,PINATAPEPE,PINATAPEPE,PINATAPEPE,PINATAPEPE,PINATAPEPE,PINATAPEPE,PINATAPEPE,PINATAPEPE,PINATAPEPE,PINATAPEPE,PINATAPEPE,PINATAPEPE,PINATAPEPE,PINATAPEPE,PINATAPEPE,PINATAPEPE,PINATAPEPE,PINATAPEPE,PINATAPEPE,PINATAPEPE,PINATAPEPE,PINATAPEPE,PINATAPEPE&quantities=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1&destinations=1CsMPn3FDBu1tz9yRCLNw2DoPRQSrXMsGd,12WVHuvG8SK7oZ1zjNWyWdMgufnkKLJKiF,1BKkSJyYUo8tmVcbRaTp7MCQ3Ux6taeRn5,17qWTPNjzGtdz1EHaHuh61mpyh1bzEqy2k,1LVpzJcMks2NrCQRsdwUUH6SWyQarJVLWB,13qyjmpVrq5juKNBjJKU5aMT5Vszf6RrEB,1CFws1FX6iCxJhBts3qPWbogqjx2DP5MnP,15e3oG2XiVDxdveTA46FSUfpmfhD8CcKm1,14wcJqbpxuoQjg87KypWFBjTbm8r9g3UtP,1GND5xY5ymSjQVfbjEuW83Dac7PmEXfgLA,18RriBjgVbNwpYazQT7gcjYyPvumRKnHcr,1EfS5zj8b6azLifij6DwEpzyeDWtHim9yi,1MMj7jrxfWyKuK7Y9EbH2kabwjx8md6Yaq,1Jwybhr54tgfZab6VBUGg23d4vVUWMxEGZ,1L58GEPokLkjjZKai2QHjEsuruaNYjj58w,12jkSi8kthNoRchQZhNwWVh5tX5MunUQ8y,14kgyX9axTr7yQvtp47VDCrzdX8pmnMaC8,177yTqyXjrtutPr1NmY6ya9SdcFmisNF1D,19j5B1ysjiUYtRdrtNGSCtLNQpKYsX3ZpK,1M21nTgSmWM9xAJ1qnjVKpTFeJ8hRyRD42,1GYW5h6Y8aCqA8DhbNyHEjUSJozbyEhmtV,1Fm6K2JjWPef3CkiCD1NxLqCa6UyPxuEqb,1Gx6SJw9aAvqBu5ERLv1Pwwi48AhDL4FyJ,1DBfdt9rQByvR6VkZA5LvrwA9PShityXu8,14GTvbSWRMMeoosVV3yjjRErFdKirJpiNd,1GLkPutCZxvk3ncCWn89nowm8pmhkWfkB3,1MCuJAtLPKVzhMjUwicQYgBJ3FzgotSdaX,1P22SuDCwp4Hv16xVxJxW4ePSaLdfet7LG,1L3SgBEq74UYBarMsaz91sdcByfJThCSoy,19vXdUEiefnvx6csZJne8HMCstStADVcRJ,13MfmFCev2gsuk2mBfKhxtvuXMtZYEENKS,1KnvQ77DUCNXprwZWw41eb5KbdQmY1L6T3,14pAnNwpvErNXooMec1hNEwYuvvLGciUVc,1Dcz5uWrG9r9X3dUTqv2HwVUbSGxCYhCh9,153jjEKKjAxPoycg2LPhgaqkgLQvj4aUWo,1CqjUUBTD2PVG1qmEdUxf8PASXYFvmTb1g,19tehY8cDocXXHq4fKsbwcMAm6CPH6YqSy,1Hp24BL2B2ZNDz3GAm8PNT7kVMfWFtF85H,17bmbMrgDw1pniztieCwFsiXPsnc4iQqPj,154rPsYNjaV4abLGLim1DDotenXVj6Rkjz,18WCwfNQ9XVMufeh3HivSV9xrwQweqgXFZ,16UUMfKRPcr8LyHSBTh7cXrNrW3KoQpp3T,1Q7wmUKWmSB3ZnpwRfWUPsyfsdYeC9RrnT,168W8T5d6hBHEh5dbwdphYDoyBcrQ11mVD,18zDR8enAtto4TX5B6uFTjexEjzNURefBj,18QtHKkdEDmSana8wZr55wW87GagDn6dhf,1ET4cRx5KxC9XavHWvz3BqwkxuYqcogK6B,1Ero4nCaHc63jbHFhijJa2MhvqD2CyfNFb,18fY34i1bp6hcpfrCY9PHRaAxrGRoeZe8i,13rp36TfQdNgh22q8r7ooZzWsRVHhLTX5g&return_only_data=true) is currently failing to create due to insufficient BTC balance.  Since I'm only asking for message data, this shouldn't cause it to fail because I don't need the transaction data.

**Comment by ouziel-slama** [comment]
@loon3 you could use now the parameter "&validate=false" to skip validations.
