### ISSUE TITLE
No Such Table `config`

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2797]
https://counterparty.sentry.io/issues/6109130302/?alert_rule_id=15343752&alert_type=issue&notification_uuid=c1455af7-a2be-45cf-9f3d-f5772c773815&project=4507062633365504&referrer=slack

<img width="1074" alt="Screenshot 2024-12-03 at 9 26 27 PM" src="https://github.com/user-attachments/assets/62adf521-b264-4073-9b38-8753f979b111">

**Comment by ouziel-slama** [comment]
fixed here https://github.com/CounterpartyXCP/counterparty-core/pull/2795/commits/3751afd9e5d82f95cfb0e8a511ecbc89a345c585
