### ISSUE TITLE
SQLError: no such column: asset_longname

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2805]
https://counterparty.sentry.io/issues/6070355395/?notification_uuid=352d9611-64c5-4912-b7c0-a985d923275f&project=4507062633365504&referrer=escalating_activity-email
<img width="1065" alt="Screenshot 2024-12-06 at 10 03 42 AM" src="https://github.com/user-attachments/assets/79c02af4-ffe3-424c-a6a4-e835f651d3f6">

**Comment by ouziel-slama** [comment]
Was a migration problem. Solved in the server.
