### ISSUE TITLE
`create_send` API call not working anymore

### ISSUE THREAD

**Issue by sorce** [CounterpartyXCP/counterparty-core#378]
I have a python script that was functioning running under counterpartyd v9.42 -- sending tokens via create_send, sign_tx and broadcast_tx (as is done in the 'python example' section in the documentation: http://counterparty.io/docs/counterpartyd/). After updating yesterday to v9.45, my script has broken. Calling the `create_send` command fails and returns:

```
{u'jsonrpc': u'2.0', u'id': 0, u'error': {u'message': u'Invalid params', u'code': -32602}}
```

The API documentation examples fail for me as well. This script returns the above error:

``` python
import os, sys
import json, requests
from requests.auth import HTTPBasicAuth

url = "http://127.0.0.1:4000/api/"
headers = {'content-type': 'application/json'}
auth = HTTPBasicAuth('my_rpc_username', 'my_rpc_password')

fromaddress = '1MBWZTzVQ3ivW7Qw7bntYY71SZfVhLUzPP'
toaddress = '18n864JtWHSihPYtAGV8bDsdCE6i3gGNqK'

def makerequest(payload):
  resp = requests.post(url, data=json.dumps(payload), headers=headers, auth=auth)
  return resp

payload = {
  "method": "create_send",
  "params": {
    "source": fromaddress,
    "destination": toaddress,
    "asset": "MYASSET",
    "quantity": 1 # non-divisible asset
  },
  "jsonrpc": "2.0",
  "id": 0
}

r = makerequest(payload)
print r.json()
```

Other calls work fine ('get_balances', 'get_running_info', etc.). Has something changed with the create_send command?

**Comment by snitko** [comment]
@adamkrellenstein @sorce could you please specify how do I update `pycoin` for the right virtual env? I did `pip3 install --upgrade pycoin`, it installed v 0.52 of pycoin, but it looks like counterparty-server is still using the old one after the restart, since it (presumably) runs in a different virtualenv.

I'm not familiar with either python or pip or virtualenv (although I spent a day today reading the relevant docs), so a detailed explanation would be very helpful. Thanks!

**Comment by sorce** [comment]
@snitko your pip command is correct, it just needs to be run from inside the counterparty virtual env (if indeed that is what you need to do). e.g. mine is at:

`/home/xcp/federatednode_build/env/bin/pip3 install --upgrade pycoin`

I'm not sure if you're running the whole node. You could also do something like `ps aux | grep counterparty` and see exactly which python environment is running the counterparty server.

You can do a `<counterparty env>/bin/pip3 freeze | grep pycoin` to see which version of pycoin is installed in the environment, to see if that is your problem.

**Comment by snitko** [comment]
@sorce Thanks for the explanation. Unfortunately, even though I did as you said and made sure the correct version of pycoin is installed, I'm still getting the same error when trying to access the JSON-RPC api. Here's the output of the command:

    ubuntu@my-server:/home/xcp/counterpartyd_build$ env/bin/pip3 freeze | grep pycoin
    Warning: cannot find svn location for apsw==3.8.2-r1
    pycoin==0.52
    ubuntu@my-server:/home/xcp/counterpartyd_build$ /home/xcp/federatednode_build/env/bin/pip3 install --upgrade pycoin
    Requirement already up-to-date: pycoin in /home/xcp/federatednode_build/env/lib/python3.4/site-packages/pycoin-0.52-py3.4.egg
    Cleaning up...
    ubuntu@my-server:/home/xcp/counterpartyd_build$ /home/xcp/counterpartyd_build/env/bin/pip3 install --upgrade pycoin
    Requirement already up-to-date: pycoin in ./env/lib/python3.4/site-packages
    Cleaning up...

My JSON-RPC request for `create_send` still results in:

    Server error -32601: Method not found

@adamkrellenstein any ideas?

**Comment by rippler** [comment]
@snitko I haven't had experience with fixing components inside of virtualenv, but could you rebuild? It takes a short time. If you can take a snapshot or backup you could easily revert in case it doesn't work.

**Comment by snitko** [comment]
@rippler yeah, I've done that. Re-installed counterparty. Same result.

**Comment by rippler** [comment]
@snitko did you nuke or move `/home/xcp/federatednode_build` prior to rebuilding?
If it's rebuilt it shouldn't matter, but I'm just asking to make sure what was your starting point.
How about other calls (`get_balance`) is it only this one call that doesn't work?
How did you get in that situation? (I'm asking this because pycoin<=0.52 is required by counterblockd (https://github.com/CounterpartyXCP/counterblock/blob/1cff508159f5deff1ebcdad75262cdd69064e269/setup.py) so I don't understand how you managed to install counterblockd although pycoin was outdated).
Did it `get_send` ever work for you? When did it stop working?

**Comment by snitko** [comment]
@rippler No, I didn't, but I can try.

`get_balance` does work. It is only `create_send` that doesn't. It used to work until after I upgraded Counterparty installation.

**Comment by rippler** [comment]
@snitko okay please try to move that existing to another and then rebuild.
I asked about before because I don't understand how could counterblock be installed with old pycoin when v0.52 is a requirement that it shouldn't have not ignored.

**Comment by snitko** [comment]
@rippler I deleted both the `federatednode_build` folder and the `counterpartyd_build` folder. Cloned the latter from Github, re-installed everything. Checked `pycoin version` within the federated node dir, it says `0.52`. I'm still getting the same `Server error -32601: Method not found` error.

**Comment by adamkrellenstein** [comment]
@snitko, are you running a Counterparty server? If not, then you shouldn't really be using the federated node system---it's unnecessarily complicated. Just use the `counterparty-lib` and `counterparty-cli` `pip` packages if you can. Beyond that, my advice is just to install `pycoin` globally (outside of the virtualenv).

**Comment by snitko** [comment]
@adamkrellenstein yes, I'm running a Counterparty server. As for pycoin, it's weird, but even globally, version 0.52 is installed. I checked `/usr/local/lib/python3.4/dist-packages` and the version installed there is definitely 0.52. As is the version installed inside `/home/xcp/federatednode_build/env/lib/python3.4/site-packages`

**Comment by adamkrellenstein** [comment]
Ah, I miswrote!. I meant "Are you running a Counter*wallet* server?". If not, then you shouldn't be running a fed node.

**Comment by robby-dermody** [comment]
Try deleting or moving the version installed in /usr/local/lib/python3.4/dist-packages

Fednode also builds for counterblock servers, and public counterparty servers. However, with the latter especially, it's not necessary anymore, as Adam noted.

**Comment by snitko** [comment]
@adamkrellenstein @robby-dermody I'm not sure. When I install counterparty by running `run.py` it gives me these options:

Enter the number for the role you want to build:
	1: Counterwallet server
	2: counterparty-server only
	3: counterblock basic (no Counterwallet)

I choose 2. `federatednode_build` dir is still created, but I'm not even sure it's running. How do I check? Furthermore, regardless of whether it's running or not, are you sure this will fix the error? It looks like the error isn't about whether I'm running a federated node or not.

@robby-dermody I've deleted `pycoin` dirs from `/usr/local/lib/python3.4/dist-packages`. Server started ok, but I'm still getting the same `Server error -32601: Method not found` error.

**Comment by adamkrellenstein** [comment]
@robby-dermody, @snitko, I would say abandon the build script entirely. Get rid of absolutely everything and just run `pip install counterparty-server`.

**Comment by snitko** [comment]
@adamkrellenstein @robby-dermody

I do apologize that maybe I'm doing something wrong, but here's the problem. Trying to install `counterparty-server` pip package, I get this:

    $ sudo pip3 install --upgrade counterparty-server
    Downloading/unpacking counterparty-server
      Could not find any downloads that satisfy the requirement counterparty-server
    Cleaning up...
    No distributions at all found for counterparty-server
    Storing debug log for failure in /home/ubuntu/.pip/pip.log

Ok, maybe the package is called differently. After googling around, I thought it might actually be called `counterparty-lib`. Installed it (along with `counterparty-cli`). Trying to run the server with `counterparty-server` results in file not found error. I'm completely confused by now. Is there a straightforward guide I can follow to install counterparty with pip3 and make it all work?

**Comment by adamkrellenstein** [comment]
There's no package `counterparty-server`. It's indeed just `counterparty-cli` and `counterparty-lib`. The docs for installing the CLI are here: https://github.com/CounterpartyXCP/Documentation/blob/master/CLI/counterparty-cli.md

**Comment by snitko** [comment]
Well, I've finally managed to install everything using pip3 (came across a number of bumps there too, for the reference for anyone who is going to read this: https://github.com/CounterpartyXCP/counterparty-cli/issues/23, https://github.com/CounterpartyXCP/counterpartyd/issues/711).

And still no luck. Same `Server error -32601: Method not found`. At this point, I don't even know what to think anymore.

**Comment by snitko** [comment]
There's a comment by @ouziel-slama above suggesting adding a catch exception clause into `api.py` to be able to see something in `api.log`. Unfortunately, the repo he gave the link to is no longer there. Although I've located `api.py` file that was installed with counterparty-lib package, I don't know where to insert that clause. My `api.log` file contains nothing useful except the time it takes to process `create_send` requests:

    [I 2015-03-13-T20:08:12+0000 wsgi:355] 200 POST /api/ (5.153.233.42) 2.56ms
    [I 2015-03-13-T20:08:25+0000 wsgi:355] 200 POST /api/ (5.153.233.42) 5287.92ms
    [I 2015-03-13-T20:08:25+0000 wsgi:355] 200 POST /api/ (5.153.233.42) 1.57ms
    [I 2015-03-13-T20:12:12+0000 wsgi:355] 200 POST /api/ (5.153.233.42) 2145.83ms
    [I 2015-03-13-T20:12:12+0000 wsgi:355] 200 POST /api/ (5.153.233.42) 0.91ms
    [I 2015-03-13-T20:14:01+0000 wsgi:355] 200 POST /api/ (5.153.233.42) 2.70ms
    [I 2015-03-13-T20:14:04+0000 wsgi:355] 200 POST /api/ (5.153.233.42) 478.12ms
    [I 2015-03-13-T20:14:05+0000 wsgi:355] 200 POST /api/ (5.153.233.42) 1.31ms

Should I open a new issue describing the problem?

**Comment by adamkrellenstein** [comment]
@snitko, I believe these are the lines that Ouziel meant you to wrap: https://github.com/CounterpartyXCP/counterpartyd/blob/master/counterpartylib/lib/api.py#L390-L411. If that doesn't work, you can open a new issue, yeah.
