### ISSUE TITLE
Change asset properties when owner controls 100% supply

### ISSUE THREAD

**Issue by jdogresorg** [CounterpartyXCP/counterparty-core#469]
Would it be possible to update Counterparty to allow the changing of certain asset properties like callable, call date/price, etc?

If this is possible, what could be changed? divisibility? locked? could existing supply be destroyed?

I think you would only want to allow this in the special case where the asset owner has 100% control of supply.

Example scenario:
- User registers MYPROMO asset for short-term promo and locks supply at 100.
- User has promo, pays users, and is now back in control of the 100 MYPROMO coins.
- User has no use for MYPROMO asset anymore, so he lists asset ownership for sale.
- No one wants to buy the MYPROMO asset because it is locked at 100 coins and un-usable for most projects.

I think adding the ability to edit certain asset properties when owner controls 100% supply would help encourage recycling/reuse of assets.

**Comment by sull** [comment]
I dont get it. The lock only makes sense if their are tokens issued and tokens sent out of address. else, lock can just be unlocked at discretion of asset owner. what is the harm in that? i think in this case, the protocol is too strict (dumb) for sake of simplicity at the cost of not thinking through what is common sense. 

No offense of course. Just how I see it. I believe in simplicity. But a protocol can also enjoy some slight flexibilities too.

**Comment by deweller** [comment]
Thought I'd drop some related links in this issue.

Here is the CIP:
https://github.com/CounterpartyXCP/cips/blob/master/cip-0003.md

Please see https://counterpartytalk.org/t/cip-reset-token-divisibility-statuses-for-unused-asset for the discussion.
