### ISSUE TITLE
Global 'CURRENT_BLOCK_INDEX' variable

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#596]
Instead of passing around `block_index` from `tx['block_index']`, we could just use a global variable that is the index of the block currently being parsed. This would be distinct from `util.last_block(db)['block_index']` which is the last block index in the database.
##

**Comment by ouziel-slama** [comment]
yeah!! and with a `CURRENT_BLOCK_INDEX` we can add easily a cache for some functions (refreshed each block) like in counterblockd (Particularly I think to `searchrawtransaction` for confirmed transactions).

**Comment by adamkrellenstein** [comment]
How would we handle API calls, though?

**Comment by ouziel-slama** [comment]
hum.. why `CURRENT_BLOCK_INDEX` should be a problem for the API ?

**Comment by adamkrellenstein** [comment]
Oh, maybe it wouldn't be! (You just don't handle any API calls during a reparse anyway.)

**Comment by adamkrellenstein** [comment]
This will make it harder to do conditional tests based on block index? At least, we'll have to add support to the test suite for changing `CURRENT_BLOCK_INDEX`.

**Comment by adamkrellenstein** [comment]
Need support in the test suite for manually changing `CURRENT_BLOCK_INDEX` for testing protocol changes.

**Comment by adamkrellenstein** [comment]
@millz0r, would you try to do this?

**Comment by adamkrellenstein** [comment]
*bump* (@millz0r)
