### ISSUE TITLE
Default to Allow Spending of Unconfirmed Coins?

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#751]
The issue is that usually with Counterparty you're only spending dust BTC (which people, esp. you yourself, are very unlikely to try to double-spend).

Another option: we could default to disallowing spending unconfirmed inputs only for significant amounts of BTC?

Another (more complicated) option: default to allowing spending unconfirmed change only.
##

**Comment by brighton36** [comment]
Running up against the error: 
Insufficient BTC at address msCXwsPVbv1Q1pc5AjXd5TdVwy3a1fSYB2. (Need approximately 0.0001543 BTC.) To spend unconfirmed coins, use the flag `--unconfirmed`. (Unconfirmed coins cannot be spent from multi-sig addresses.)
Is very common for anyone who's using Counterparty for a non-trivial number of transactions. It's a bit confusing, and since it's (in my experience) so common, It begs the question as to why it's not the default to begin with. What's the reason not to have it as a default, double-spends in the mempool? (does that only affect BTC?)

**Comment by super3** [comment]
When paying out SJCX expenses this is very annoying. This would make things much easier. 

Double-spends in mempool would have to be investigated. Run in testnet and see what happens?

**Comment by adamkrellenstein** [comment]
This question is completely independent of the mempool.

**Comment by adamkrellenstein** [comment]
@super3, why is it annoying? Do you not turn on unconfirmed spends?

**Comment by super3** [comment]
So is this spending unconfirmed XCP and assets? Not using unconfirmed BTC
in a transaction?

In either case this would be helpful.

**Comment by adamkrellenstein** [comment]
No, this is spending unconfirmed BTC only. (Though BTC are part of any Counterparty transaction.)

**Comment by brighton36** [comment]
Presumably unconfirmed inputs are unstandard for reason, what is the trade-off here by allowing this behavior? If there is no trade-off, then I think this probably isn't worth discussing, as then it could only improve the experience.

**Comment by rippler** [comment]
A bit strange is that in CW you can get the advice to use `--unconfirmed` although you can't really do that (IIRC that used to be possible in Options when BTC_Pay was available, but now there's no way to enable that in Options).

**Comment by brighton36** [comment]
This is related btw. Is one option (instead of making --unconfirmed default) to change the way UTXO's are allocated by Counterparty? https://counterpartytalk.org/t/is-your-cp-wallets-transactions-per-block-limited-to-the-number-of-utxos-in-that-address/1048

**Comment by adamkrellenstein** [comment]
@ouziel-slama, @btcdrak, your thoughts?

**Comment by ouziel-slama** [comment]
The only downside to make `--unconfirmed` the default is the speed (https://github.com/CounterpartyXCP/counterpartyd/blob/master/counterpartylib/lib/backend/addrindex.py#L91).
The error message is actually very explicit and clearly suggest to use `--unconfirmed` option, I'am not sure if it worth to make the `create_send` slower for everybody.

**Comment by adamkrellenstein** [comment]
Hm, yes. That's a problem. Currently, UTXO searches with `--unconfirmed` are very slow. This is an open issue: #715.

**Comment by rippler** [comment]
@ouziel-slama as I mentioned above, the explicit nature of the message doesn't work at all for Counterwallet because there's no way to pass the parameter from Counterwallet.

**Comment by robby-dermody** [comment]
Doesn't counterwallet give a helpful error message with this error though?

**Comment by rippler** [comment]
@robby-dermody yes it does (in my comment https://github.com/CounterpartyXCP/counterpartyd/issues/751#issuecomment-91903935 above), but it's not actionable - unless wait until the next block is considered actionable.

**Comment by brighton36** [comment]
IMO, it's usually more typical for projects to default to a reasonable fail-safe, then to default to a speed optimization. If a user is processing enough volume to be inhibited by the speed of searching the mempool, then they are invested enough in the platform to learn how to turn off unconfirmed spends. Meanwhile, a new user to the counterwallet software is apt to say "This is buggy, I'll try something else" when they run up against that error.

**Comment by ouziel-slama** [comment]
@rippler: I just opened an issue for that: https://github.com/CounterpartyXCP/counterwallet/issues/725

@brighton36: so maybe is just an interface problem. For instance in case of this error,  `counterparty-client` could display a nice message/question like "Do you wan to use unconfirmed outputs (y/N)" ?

**Comment by brighton36** [comment]
The problem I have with making that an interface question is that 1. It's scary looking to the uninitiated (I suspect they will perceive that unconfirmed == risk) 2. It's a distinction without a difference. The command completes for them either way, so the question appears tantamount to asking if they want the (already delayed) transaction to proceed slowly.

Perhaps we can default to confirmed transactions, unless none are available, and then slowly proceed thereafter with unconfirmed transactions?

**Comment by adamkrellenstein** [comment]
@brighton36, re: prompting the user, +1

**Comment by adamkrellenstein** [comment]
This whole issue is pretty tricky, because unconfirmed 'double-spends' are theoretically very easy to execute, but in practice, no one does them *yet*.

I'm worried about, in three months, if people start using unconfirmed outputs for their Counterparty transactions, and those transactions never get confirmed, because their inputs were double-spent. If we can deal with the speed issue (Ouziel's working on that now), then we can just deal with the double-spend problem later, though.

**Comment by adamkrellenstein** [comment]
I think a *lot* of people probably try making multiple spends in one block while having not enough UTXOs to do that without spending unconfirmed change. Of course, then the question becomes what we do with the *CLI*, which should ideally be as conservative as possible. Indeed, CW, e.g., should definitely default to using `--unconfirmed` always.

**Comment by adamkrellenstein** [comment]
It's a trade-off between being conservative and intuitive, perhaps? A CLI and an API should usually default to the former, but really, how many double-spends are there these days??

**Comment by brighton36** [comment]
Is there any easy explanation as to why every cp transaction requires a UTXO? Why can't we issue multiple CP transactions per UTXO? Alternatively, maybe we could have an official tool that will create a specified number of UTXOs on an address (by way of vanilla bitcoin spends to/from the same address)? That's a bit cludgy, but it'd be good to offer to people like @super3 at least...

**Comment by adamkrellenstein** [comment]
@brighton36: this issue really has nothing to do with Counterparty---it's a Bitcoin issue.

Bitcoin Core just plasters over the problem by distinguishing change outputs from other outputs.

**Comment by brighton36** [comment]
Note that a biggish problem we have right now is that new users deposit money into their counterwallet via a single transaction. Then they try to perform multiple transactions in the wallet, and quickly meet the error message "Insufficient BTC at address" , which is confusing to them.

Perhaps what could be done in counterwallet is to ask the user, upon receiving a transaction for the first time : "Would you like to fragment this wallet so that subsequent transactions confirm quicker and more reliably? (Recommended) The cost to do so is: 0.00X"

**Comment by brighton36** [comment]
For reference, this is poignant, but a user complaint that popped up today, which illustrates IMO the need to fix this : https://counterpartytalk.org/t/only-20-addresses-show-up-in-my-counterparty-wallet/1052/18?u=brighton36  Another option is to list the UTXO's in counterwallet, and allow the user to add more via an interface widget...

**Comment by adamkrellenstein** [comment]
This isn't a question about Counterwallet behaviour, but rather the default for the CLI and API.

**Comment by brighton36** [comment]
Hmmm. Well, I think the community could benefit from explicit clarity and standardization on how they can achieve higher throughput and reliability. Perhaps the API should have a available_transactions_per-block(address) and max_transactions_per_block(address) method . And perhaps the cli should have a reference command/implementation for an increase_max_transactions(address) function?

**Comment by ouziel-slama** [comment]
1) It's really a problem only to make several transactions one after the other with the same source, and I'am inclined to say that is an advanced feature not needed for most of the users. 
2) the mempool parsing (related to the unconfirmed UTXO search) consume a "lot" of server resources.
For these two reasons I think we should keep the `--unconfirmed` default value to False, and even disable by default the mempool parsing (see this PR: https://github.com/CounterpartyXCP/counterpartyd/pull/756).

**Comment by brighton36** [comment]
I respectfully disagree on point 1. I think that's one of the most common scenarios people run into when getting started with counterparty. I hear this complaint often, and in this thread I think I/we've finally figured out the issue I've been hearing about.

**Comment by ouziel-slama** [comment]
@brighton36: :-) yeah I humbly agree that it is not an indisputable statement!

**Comment by ouziel-slama** [comment]
Actually, because this PR https://github.com/CounterpartyXCP/counterpartyd/pull/760, it's impossible to disable the mempool. So the 2) is not valid anymore...

**Comment by adamkrellenstein** [comment]
This is really outside the scope of what Counterparty Core should do.
