### ISSUE TITLE
Divisible vs non-divisible balances

### ISSUE THREAD

**Issue by cryptonaut420** [CounterpartyXCP/counterparty-core#755]
This one isn't a huge deal, but it's something that I have found kind of annoying to deal with when developing stuff. Address balances and transaction quantities etc. are always given in the form of Satoshis, where 1 of a divisible asset = 100000000 and 1 of a non-divisible asset just = 1. I get the reasoning behind that, but it also means that any time you display a balance for an address or transaction quantity, you have to lookup that asset each time to check if it's divisible or not, and then do the proper conversion.

It would be nice if on any response that includes a balance or quantity, it includes a "asset_divisible" field with it. Or..  maybe even better, something like "formatted_quantity" which does the display conversion for you.

thoughts?
##

**Comment by ouziel-slama** [comment]
The API could return float for divisible assets and integer for non-divisible asset.

**Comment by adamkrellenstein** [comment]
floats make me :tired_face:

**Comment by adamkrellenstein** [comment]
We could return strings??

That doesn't address the issue of backwards-compatibility, though. :/

**Comment by deweller** [comment]
For backwards compatibility, can you add a new field to the Balance object (http://counterparty.io/docs/api/#balance-object) that includes a normalized value?  Call it say "float_quantity".

But I see the problem.  If you use floats, it might lead to floating point math errors and/or ugly JSON.  If you use an integer, then non-divisible assets could be too big to express as a 64 bit integer (right?).

So, hmmm.  Maybe just including a new field in the balance object called `asset_divisible` might be the best thing here.  At least we won't have to continually be making API calls to `bet_asset_info` - or the new equavilent - to decode the value.

**Comment by cryptonaut420** [comment]
asset_divisible feild might be the best option. For me at least it's more about the extra API call thats needed. Not a big deal to do the conversion, easy enough to create a simple wrapper function to handle that in the application.

**Comment by ouziel-slama** [comment]
Except for backwards-compatibility I can not see a problem to return float and integer (or why not a string).
In general, for the API, I think is too soon to try to completely avoid backwards incompatibilities.
However in this particular case, we could add an optional parameter to asked the API to return "human readable" quantities instead satoshis.

**Comment by deweller** [comment]
+1 for a "human readable" field.  It could be a float (or string) that returns `quantity / 100000000` for divisible assets and just `quantity` for non-divisible assets.

Since this is adding a field to the balance object and not changing any existing fields, the backwards compatibility issues would be negligible for me.

**Comment by robby-dermody** [comment]
+1 for a separate field with the human readable value. Not maintaining backwards compatibility here would break A LOT of things, plus in my mind it's not a kludge to have two fields... One is the raw value, the other is a human readable value that takes divisibility into account.

**Comment by adamkrellenstein** [comment]
@ouziel-slama is this fixed with API v2?

**Comment by ouziel-slama** [comment]
yep! with `verbose=true` all fields containing a quantity are accompanied by a `*_normalized` field containing the normalized quantity.

**Comment by adamkrellenstein** [comment]
🎉
