### ISSUE TITLE
IPFS support?

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#780]
Use for storing larger data payloads?

Primary concerns:
- Security
- Speed
##

**Comment by rippler** [comment]
Wanted to suggest that the other day, thought it wouldn't fly.
I tried it back in March, it's easy to use. It's not replicated, or at least it wasn't back in March, so if that's a requirement maybe other options should be considered as well.

**Comment by adamkrellenstein** [comment]
Yeah, what do you do if all of the nodes hosting a certain file (or a part of a file) go down??

**Comment by adamkrellenstein** [comment]
I guess we'd have to require every Counterparty node to host every file...

**Comment by ouziel-slama** [comment]
Right now, it's obvious that there IPFS is not enough mature to be used in production. But it seems to me very promising, and I think it's worth to test it combined with OP_RETURN as an alternative way to encode transactions data.

**Comment by rippler** [comment]
@ouziel, see https://github.com/namesystem/blockstore/issues/80, blockstore has OP_RETURN too

**Comment by rippler** [comment]
Can't edit previsoka comment from an outdated browser... "Right now, there’s an implementation on the Namecoin blockchain, but the protocol could just as easily be ported to sidechains, a logic-heavy blockchain like Ethereum, or protocols like Counterparty that build embedded chains of consensus on top of the Bitcoin blockchain (let’s call them topchains)." - http://blog.onename.com/blockstore-bitcoin/

**Comment by ouziel-slama** [comment]
@rippler, IPFS seems to me more powerful and flexible than blockstore and more adapted to our needs (for instance IPFS don't need an external blockchain to exist, is an immutable decentralized DHT).

**Comment by rippler** [comment]
@ouziel-slama I like IPFS, I set it up it as soon alpha version was announced, but it's going to be a few quarters (or more) before it gets persistence and replicas. They're planning to have their own coin for it (perhaps it'd be convenient if it existed on CP).

**Comment by unsystemizer** [comment]
IPFS may be supported as part of blockstack.

https://forum.blockstack.org/t/general-architecture-of-blockstack-initial-version/54

**Comment by adamkrellenstein** [comment]
We need something with guaranteed availability, ofc. :/
