### ISSUE TITLE
create_send support for checking mempool

### ISSUE THREAD

**Issue by jdogresorg** [CounterpartyXCP/counterparty-core#786]
Currently when users make create_send requests, the mempool is completely ignored, which means that users are able to create transactions that will more than likely fail, resulting in unnecessary transactions and wasted transaction fees.

Example : 
I have 100 TOKENS at an address
I make a create_send API call and send 100 TOKENS to some address and broadcast it.. transaction is broadcast and in mempool.
I then make a second create_send API call to send 100 tokens to some different address.. and the transaction is created and broadcast.

Since only 100 TOKENS are available, only one of the send transactions will succeed. The other will fail, but the user still has to pay for the transaction costs and is out the miners fee.

I would like to see an option added to create_send which handles checking the mempool for transactions and deducting pending quantity from available quantity. 

The user would specify an additional option in the create_send request like :
"mempool_quantity_locked": true

Counterparty-lib would then deduct any quantity in mempool from the available quantity, and issue an "insufficient funds"... just like it does when you have no funds to send.

Adding this option would help counterparty users cut down on unnecessary transaction costs.
##

**Comment by ouziel-slama** [comment]
So the problem comes from a bug fixed here: https://github.com/CounterpartyXCP/counterparty-lib/commit/4337ccf3d0021a085a5bb1213ab38c153b34ae9c
To use unconfirmed outputs from the mempool, you can just use the argument `allow_unconfirmed_inputs`..

..but you have a now a better solution to chain transaction faster with the new argument  `unspent_tx_hash`: you can just pass the tx_hash of the unconfirmed transactions that contains unspent outputs:
```
tx1 = create_send(...)
tx_hash1 = sendrawtransaction(tx1)
tx2 = create_send(..., unspent_tx_hash=tx_hash1)
tx_hash2 = sendrawtransaction(tx2)
tx3 = create_send(..., unspent_tx_hash=tx_hash3)
````
see https://github.com/CounterpartyXCP/counterparty-lib/commit/2e27587338124ea0b9087690b2695e6ca840eb8b and https://github.com/CounterpartyXCP/counterparty-lib/commit/bddc829f3db239becd58b2adae2bbeeb71846f7a

**Comment by jdogresorg** [comment]
This is handy to know... however, my issue is not with spending unconfirmed outputs. My issue is with the mempool not being checked when using create_send.

1.) I have ADDRESS1 with 100 TOKENS

2.) I send 100 TOKENS from ADDRESS1 to ADDRESS2... transaction is created and put in mempool
Transaction will succeed  because ADDRESS1 has 100 TOKENS to send

3.) I try to send 100 TOKENS FROM ADDRESS1 to ADDRESS3... transaction is created and put in mempool
Transaction will FAIL because ADDRESS1 has 0 TOKENS to send (tokens were used in step2)

What I am asking for is in step 3 when I make a create_send request, that counterparty-lib check the mempool for any asset quantity which is waiting to be sent, and deducts that from the available amount..... and returns a "insufficient funds" error... the same as it would if I had 0 TOKENS in my address and I tried to send 100 TOKENS.

**Comment by ouziel-slama** [comment]
oh! OK! I understand the problem.. but unless you are chaining transaction, we can't know what transaction will be first in the block.. for this reason when we are parsing the mempool we can't assume what will be the transaction order.. is why what you are asking seems to me very difficult...

**Comment by adamkrellenstein** [comment]
Yes, this would be difficult to implement, because of the order-dependence of transactions in the mempool. (Unconfirmed transactions are *extremely* unreliable.)
