### ISSUE TITLE
Asset ownership for multisig address not correctly stored in counterparty.db

### ISSUE THREAD

**Issue by unsystemizer** [CounterpartyXCP/counterparty-core#836]
For this multisig address there is no asset ownership:
http://blockscan.com/address?q=2_19w6yfu4hadhphiu12utcq9x93mn7g2eur_1zzzzxdja2p3jkohkp3dw8qgmjg8dxc6n_2

SQL:
`SELECT * FROM balances WHERE address = '2_19w6yfu4hadhphiu12utcq9x93mn7g2eur_1zzzzxdja2p3jkohkp3dw8qgmjg8dxc6n_2'`

But if you look at individual transactions of this address, such as http://blockscan.com/txInfo/11839854, you'll see that each of the 3 multisig transactions involving this multisig address received a small amount of Counterparty tokens.

However in `counterparty.db`, all 3 transactions don't show in results:
- `SELECT * FROM transactions WHERE tx_index = '11839854'`
- `SELECT * FROM transactions WHERE tx_index = '11844821'`
- `SELECT * FROM transactions WHERE tx_index = '11839854'`

While in the the `credits` table we have something:

SQL: 
`SELECT * FROM credits WHERE (asset = 'MRCBKK' AND address LIKE '2_19w6yfu4hadhphiu12utcq9x93mn7g2eur_1zzzzxdja2p3jkohkp3dw8qgmjg8dxc6n_2')`

```
BLOCK    ADDRESS      ASSET   QUANTITY CALLING-FUNCTION  EVENT
397639  2_19w6YFU4haDhPHiU12UtCQ9X93Mn7G2eUr_1zzzzXDjA2p3JKohKp3dW8qGmJG8Dxc6N_2    MRCBKK  50000000    send    89d08ae73390ae39119341ac213090338b6667ec972e5d85442cd752bda73099
397399  2_19w6YFU4haDhPHiU12UtCQ9X93Mn7G2eUr_1zzzzXDjA2p3JKohKp3dW8qGmJG8Dxc6N_2    MRCBKK  70000000    send    c3e6a3052bfae76e5dc4eb62a74432c790f797fcfbdc7e7d0b774d1108a5fc07
398557  2_19w6YFU4haDhPHiU12UtCQ9X93Mn7G2eUr_1zzzzXDjA2p3JKohKp3dW8qGmJG8Dxc6N_2    MRCBKK  50000000    send    f29bd7408f6a7ab5f4e70a695141c8e1556ca719f95aaaa9f96afdefcf662c9a
```

On the other hand some other multisig addresses such as http://blockscan.com/address/2_17fD8KNnT7tL6ZYKaHdA1nZVk23FnXKB7i_1zzzzXDjA2p3JKohKp3dW8qGmJG8Dxc6N_2 are shown to hold Counterparty asset balances (in this case `MRCBKK`)
##

**Comment by rubensayshi** [comment]
```
sqlite> select * FROM balances WHERE address = '2_19w6YFU4haDhPHiU12UtCQ9X93Mn7G2eUr_1zzzzXDjA2p3JKohKp3dW8qGmJG8Dxc6N_2';
2_19w6YFU4haDhPHiU12UtCQ9X93Mn7G2eUr_1zzzzXDjA2p3JKohKp3dW8qGmJG8Dxc6N_2|MRCBKK|170000000
```

could you `sqlite> select * FROM sends WHERE destination = '2_19w6YFU4haDhPHiU12UtCQ9X93Mn7G2eUr_1zzzzXDjA2p3JKohKp3dW8qGmJG8Dxc6N_2';
`

and tell us which version your counterparty you're running?

**Comment by unsystemizer** [comment]
This was with 9.53 before the bug struck and at the time blockscan.com was also running 9.53. 
Now blockscan.com has 9.54 and it still doesn't show (first link at the very top) any assets held at that multisig address.

On Sqlite DB from the time of reporting this bug, here's what I get from `select * FROM sends WHERE destination = '2_19w6YFU4haDhPHiU12UtCQ9X93Mn7G2eUr_1zzzzXDjA2p3JKohKp3dW8qGmJG8Dxc6N_2'; `

```
421363	c3e6a3052bfae76e5dc4eb62a74432c790f797fcfbdc7e7d0b774d1108a5fc07	397399	2_17fD8KNnT7tL6ZYKaHdA1nZVk23FnXKB7i_1zzzzXDjA2p3JKohKp3dW8qGmJG8Dxc6N_2	2_19w6YFU4haDhPHiU12UtCQ9X93Mn7G2eUr_1zzzzXDjA2p3JKohKp3dW8qGmJG8Dxc6N_2
422573	89d08ae73390ae39119341ac213090338b6667ec972e5d85442cd752bda73099	397639	2_17fD8KNnT7tL6ZYKaHdA1nZVk23FnXKB7i_1zzzzXDjA2p3JKohKp3dW8qGmJG8Dxc6N_2	2_19w6YFU4haDhPHiU12UtCQ9X93Mn7G2eUr_1zzzzXDjA2p3JKohKp3dW8qGmJG8Dxc6N_2
426330	f29bd7408f6a7ab5f4e70a695141c8e1556ca719f95aaaa9f96afdefcf662c9a	398557	2_17fD8KNnT7tL6ZYKaHdA1nZVk23FnXKB7i_1zzzzXDjA2p3JKohKp3dW8qGmJG8Dxc6N_2	2_19w6YFU4haDhPHiU12UtCQ9X93Mn7G2eUr_1zzzzXDjA2p3JKohKp3dW8qGmJG8Dxc6N_2
```

I could run it against the current DB from 9.54, if you think results could be different.

**Comment by adamkrellenstein** [comment]
This is a very old issue.
