### ISSUE TITLE
Prefix future releases with 'v'

### ISSUE THREAD

**Issue by unsystemizer** [CounterpartyXCP/counterparty-core#957]
Before `lib` and `cli` used to have tags with a `v` before each release and lately they don't. 

So now newer releases are all at the bottom of the "tags" list, while older `v*` releases is at the very top. 
Earlier today I spent some time trying to figure out how come release tags exist, but can't be navigated. 

![image](https://cloud.githubusercontent.com/assets/13134193/21963203/2971f3c8-db71-11e6-83e0-22e6bac6cb71.png)

On the same topic of Github management, Bounty Source plugin is buggy, we might as well remove it (if they can't fix it - it's been a while now and it's not eye-pleasing)

**Comment by adamkrellenstein** [comment]
@ouziel-slama FYI. We should standardize on this.

**Comment by adamkrellenstein** [comment]
Fixed
