### ISSUE TITLE
Forbidden words list prevents retrieving data on some assets via API

### ISSUE THREAD

**Issue by windsok** [CounterpartyXCP/counterparty-core#963]
There is a few assets that start with "pragma", such as PRAGMATIC: https://counterpartychain.io/asset/PRAGMATIC

When trying to extract details of this asset from the "get_assets" API, it returns an error response.

Example:
`curl -X POST http://public.coindaddy.io:4000/api/ --user rpc:1234 -H 'Content-Type: application/json; charset=UTF-8' -H 'Accept: application/json, text/javascript' --data-binary '{"method": "get_assets", "params": {"filters": [{"field": "asset_name", "op": "==", "value": "PRAGMATIC"}], "filterop": "or", "limit": 1000}, "jsonrpc": "2.0", "id": 0}'
`

Returns the reponse:
`{"id": 0, "error": {"message": "Server error", "code": -32000, "data": {"message": "Forbidden word in query: 'pragma'.", "args": ["Forbidden word in query: 'pragma'."], "type": "APIError"}}, "jsonrpc": "2.0"}`

This seems to be caused by the forbidden words list here:
https://github.com/CounterpartyXCP/counterparty-lib/blob/5498d891ffec270c64a5804a4273962d2c759fa5/counterpartylib/lib/api.py#L112

We should find a way to make the API correctly return details for real assets that contain the forbidden words.

**Comment by adamkrellenstein** [comment]
Related to #1327
