### ISSUE TITLE
testnet reorg reparse doesn't do full reparse

### ISSUE THREAD

**Issue by deweller** [CounterpartyXCP/counterparty-core#978]
When a testnet node has a reorg event that requires a full reparse, the node can crash.

This can happen when a new protocol change has been introduced while the node has been running.

The testnet full reparse after a reorg should clear the consensus hashes before reparsing.

Reference https://github.com/CounterpartyXCP/counterparty-lib/commit/5cd6bf1ae59602e4806ff60ac90c851cf5e0c684

[Update: fixed the reference link]

**Comment by deweller** [comment]
Reference:

https://github.com/CounterpartyXCP/counterparty-lib/commit/5cd6bf1ae59602e4806ff60ac90c851cf5e0c684

**Comment by unsystemizer** [comment]
Good point - I think this surfaced over and over again. 

The ref link is 404, by the way

**Comment by adamkrellenstein** [comment]
This was very likely fixed by killing the `undolog`.
