### ISSUE TITLE
CLI help for broadcast outdated

### ISSUE THREAD

**Issue by ghost** [CounterpartyXCP/counterparty-core#98]
`usage: counterpartyd broadcast [-h] --source SOURCE --text TEXT`
`[--value VALUE] [--fee-fraction FEE_FRACTION]`
`[--fee FEE]`

`counterpartyd v9.18.0`

Isn't `--fee` a thing of the past?
OS: Win 7 x64

**Comment by rippler** [comment]
`--fee-fraction` seems required in which case the brackets could be removed
